
var Tiro = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  
  return (
function(Tiro) {
  Tiro = Tiro || {};


var g;g||(g=typeof Tiro !== 'undefined' ? Tiro : {});var aa,ba;g.ready=new Promise(function(a,b){aa=a;ba=b});var ca={},r;for(r in g)g.hasOwnProperty(r)&&(ca[r]=g[r]);var da="./this.program",w="";"undefined"!==typeof document&&document.currentScript&&(w=document.currentScript.src);_scriptDir&&(w=_scriptDir);0!==w.indexOf("blob:")?w=w.substr(0,w.lastIndexOf("/")+1):w="";var ea=g.print||console.log.bind(console),x=g.printErr||console.warn.bind(console);
for(r in ca)ca.hasOwnProperty(r)&&(g[r]=ca[r]);ca=null;g.thisProgram&&(da=g.thisProgram);var y=0,fa;g.wasmBinary&&(fa=g.wasmBinary);var noExitRuntime=g.noExitRuntime||!0;"object"!==typeof WebAssembly&&z("no native wasm support detected");var ja,ka=!1,la="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ma(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&la)return la.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|k:(e&7)<<18|f<<12|k<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}
function na(a,b,c,d){if(0<d){d=c+d-1;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var k=a.charCodeAt(++e);f=65536+((f&1023)<<10)|k&1023}if(127>=f){if(c>=d)break;b[c++]=f}else{if(2047>=f){if(c+1>=d)break;b[c++]=192|f>>6}else{if(65535>=f){if(c+2>=d)break;b[c++]=224|f>>12}else{if(c+3>=d)break;b[c++]=240|f>>18;b[c++]=128|f>>12&63}b[c++]=128|f>>6&63}b[c++]=128|f&63}}b[c]=0}}
function oa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}var pa="undefined"!==typeof TextDecoder?new TextDecoder("utf-16le"):void 0;function qa(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&ra[c];)++c;c<<=1;if(32<c-a&&pa)return pa.decode(B.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=sa[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c}
function ta(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)sa[b>>1]=a.charCodeAt(e),b+=2;sa[b>>1]=0;return b-d}function ua(a){return 2*a.length}function va(a,b){for(var c=0,d="";!(c>=b/4);){var e=C[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}
function wa(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var k=a.charCodeAt(++e);f=65536+((f&1023)<<10)|k&1023}C[b>>2]=f;b+=4;if(b+4>c)break}C[b>>2]=0;return b-d}function xa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}var ya,E,B,sa,ra,C,G,za,Aa;
function Ba(){var a=ja.buffer;ya=a;g.HEAP8=E=new Int8Array(a);g.HEAP16=sa=new Int16Array(a);g.HEAP32=C=new Int32Array(a);g.HEAPU8=B=new Uint8Array(a);g.HEAPU16=ra=new Uint16Array(a);g.HEAPU32=G=new Uint32Array(a);g.HEAPF32=za=new Float32Array(a);g.HEAPF64=Aa=new Float64Array(a)}var H,Ca=[],Da=[],Ea=[],Fa=[];Da.push({ca:function(){Ga()}});function Ha(){var a=g.preRun.shift();Ca.unshift(a)}var I=0,Ia=null,Ja=null;g.preloadedImages={};g.preloadedAudios={};
function z(a){if(g.onAbort)g.onAbort(a);x(a);ka=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}function Ka(){var a=J;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var J="tiro.wasm";if(!Ka()){var La=J;J=g.locateFile?g.locateFile(La,w):w+La}
function Ma(){var a=J;try{if(a==J&&fa)return new Uint8Array(fa);throw"both async and sync fetching of the wasm failed";}catch(b){z(b)}}function Na(){return fa||"function"!==typeof fetch?Promise.resolve().then(function(){return Ma()}):fetch(J,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+J+"'";return a.arrayBuffer()}).catch(function(){return Ma()})}
function Oa(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(g);else{var c=b.ca;"number"===typeof c?void 0===b.T?H.get(c)():H.get(c)(b.T):c(void 0===b.T?null:b.T)}}}
function K(a){this.Y=a;this.b=a-16;this.ta=function(b){C[this.b+8>>2]=b};this.D=function(){return C[this.b+8>>2]};this.ra=function(b){C[this.b+0>>2]=b};this.ha=function(){return C[this.b+0>>2]};this.sa=function(){C[this.b+4>>2]=0};this.W=function(b){E[this.b+12>>0]=b?1:0};this.ga=function(){return 0!=E[this.b+12>>0]};this.N=function(b){E[this.b+13>>0]=b?1:0};this.Z=function(){return 0!=E[this.b+13>>0]};this.ka=function(b,c){this.ta(b);this.ra(c);this.sa();this.W(!1);this.N(!1)};this.S=function(){C[this.b+
4>>2]+=1};this.qa=function(){var b=C[this.b+4>>2];C[this.b+4>>2]=b-1;return 1===b}}function L(a){this.U=function(){M(this.b);this.b=0};this.H=function(b){C[this.b>>2]=b};this.v=function(){return C[this.b>>2]};this.G=function(b){C[this.b+4>>2]=b};this.fa=function(){return C[this.b+4>>2]};this.ia=function(){if(Pa(this.A().D()))return C[this.v()>>2];var b=this.fa();return 0!==b?b:this.v()};this.A=function(){return new K(this.v())};void 0===a?(this.b=Qa(8),this.G(0)):this.b=a}var N=[],Ra=0;
function Sa(a){return M((new K(a)).b)}function Ta(a){if(a.qa()&&!a.Z()){var b=a.ha();b&&H.get(b)(a.Y);Sa(a.Y)}}var O=0;function Ua(){var a=N.pop();a||z("no exception to throw");var b=a.A(),c=a.v();b.Z()?a.U():(N.push(a),b.N(!0),b.W(!1),Ra++);O=c;throw c;}function Va(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Wa=void 0;function P(a){for(var b="";B[a];)b+=Wa[B[a++]];return b}var Xa={},Ya={},Za={};
function $a(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function ab(a,b){a=$a(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function bb(a){var b=Error,c=ab(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var cb=void 0;function Q(a){throw new cb(a);}var db=void 0;function eb(a){throw new db(a);}
function fb(a,b,c){function d(l){l=c(l);l.length!==a.length&&eb("Mismatched type converter count");for(var n=0;n<a.length;++n)R(a[n],l[n])}a.forEach(function(l){Za[l]=b});var e=Array(b.length),f=[],k=0;b.forEach(function(l,n){Ya.hasOwnProperty(l)?e[n]=Ya[l]:(f.push(l),Xa.hasOwnProperty(l)||(Xa[l]=[]),Xa[l].push(function(){e[n]=Ya[l];++k;k===f.length&&d(e)}))});0===f.length&&d(e)}
function R(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||Q('type "'+d+'" must have a positive integer typeid pointer');if(Ya.hasOwnProperty(a)){if(c.ja)return;Q("Cannot register type '"+d+"' twice")}Ya[a]=b;delete Za[a];Xa.hasOwnProperty(a)&&(b=Xa[a],delete Xa[a],b.forEach(function(e){e()}))}function gb(a){return{count:a.count,u:a.u,F:a.F,b:a.b,f:a.f,h:a.h,i:a.i}}
function hb(a){Q(a.a.f.c.name+" instance already deleted")}var ib=!1;function jb(){}function kb(a){--a.count.value;0===a.count.value&&(a.h?a.i.s(a.h):a.f.c.s(a.b))}function lb(a){if("undefined"===typeof FinalizationGroup)return lb=function(b){return b},a;ib=new FinalizationGroup(function(b){for(var c=b.next();!c.done;c=b.next())c=c.value,c.b?kb(c):console.warn("object already deleted: "+c.b)});lb=function(b){ib.register(b,b.a,b.a);return b};jb=function(b){ib.unregister(b.a)};return lb(a)}
var mb=void 0,nb=[];function ob(){for(;nb.length;){var a=nb.pop();a.a.u=!1;a["delete"]()}}function S(){}var pb={};function qb(a,b,c){if(void 0===a[b].l){var d=a[b];a[b]=function(){a[b].l.hasOwnProperty(arguments.length)||Q("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].l+")!");return a[b].l[arguments.length].apply(this,arguments)};a[b].l=[];a[b].l[d.K]=d}}
function rb(a,b){g.hasOwnProperty(a)?(Q("Cannot register public name '"+a+"' twice"),qb(g,a,a),g.hasOwnProperty(void 0)&&Q("Cannot register multiple overloads of a function with the same number of arguments (undefined)!"),g[a].l[void 0]=b):g[a]=b}function sb(a,b,c,d,e,f,k,l){this.name=a;this.constructor=b;this.B=c;this.s=d;this.j=e;this.da=f;this.J=k;this.ba=l;this.ma=[]}
function tb(a,b,c){for(;b!==c;)b.J||Q("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.J(a),b=b.j;return a}function ub(a,b){if(null===b)return this.V&&Q("null is not a valid "+this.name),0;b.a||Q('Cannot pass "'+vb(b)+'" as a '+this.name);b.a.b||Q("Cannot pass deleted object as a pointer of type "+this.name);return tb(b.a.b,b.a.f.c,this.c)}
function wb(a,b){if(null===b){this.V&&Q("null is not a valid "+this.name);if(this.M){var c=this.na();null!==a&&a.push(this.s,c);return c}return 0}b.a||Q('Cannot pass "'+vb(b)+'" as a '+this.name);b.a.b||Q("Cannot pass deleted object as a pointer of type "+this.name);!this.L&&b.a.f.L&&Q("Cannot convert argument of type "+(b.a.i?b.a.i.name:b.a.f.name)+" to parameter type "+this.name);c=tb(b.a.b,b.a.f.c,this.c);if(this.M)switch(void 0===b.a.h&&Q("Passing raw pointer to smart pointer is illegal"),this.ua){case 0:b.a.i===
this?c=b.a.h:Q("Cannot convert argument of type "+(b.a.i?b.a.i.name:b.a.f.name)+" to parameter type "+this.name);break;case 1:c=b.a.h;break;case 2:if(b.a.i===this)c=b.a.h;else{var d=b.clone();c=this.oa(c,xb(function(){d["delete"]()}));null!==a&&a.push(this.s,c)}break;default:Q("Unsupporting sharing policy")}return c}
function yb(a,b){if(null===b)return this.V&&Q("null is not a valid "+this.name),0;b.a||Q('Cannot pass "'+vb(b)+'" as a '+this.name);b.a.b||Q("Cannot pass deleted object as a pointer of type "+this.name);b.a.f.L&&Q("Cannot convert argument of type "+b.a.f.name+" to parameter type "+this.name);return tb(b.a.b,b.a.f.c,this.c)}function zb(a){return this.fromWireType(G[a>>2])}function Ab(a,b,c){if(b===c)return a;if(void 0===c.j)return null;a=Ab(a,b,c.j);return null===a?null:c.ba(a)}var Bb={};
function Cb(a,b){for(void 0===b&&Q("ptr should not be undefined");a.j;)b=a.J(b),a=a.j;return Bb[b]}function Db(a,b){b.f&&b.b||eb("makeClassHandle requires ptr and ptrType");!!b.i!==!!b.h&&eb("Both smartPtrType and smartPtr must be specified");b.count={value:1};return lb(Object.create(a,{a:{value:b}}))}function T(a,b,c,d){this.name=a;this.c=b;this.V=c;this.L=d;this.M=!1;this.s=this.oa=this.na=this.$=this.ua=this.la=void 0;void 0!==b.j?this.toWireType=wb:(this.toWireType=d?ub:yb,this.m=null)}
function Eb(a,b){g.hasOwnProperty(a)||eb("Replacing nonexistant public symbol");g[a]=b;g[a].K=void 0}function Fb(a,b){var c=[];return function(){c.length=arguments.length;for(var d=0;d<arguments.length;d++)c[d]=arguments[d];-1!=a.indexOf("j")?(d=g["dynCall_"+a],d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)):d=H.get(b).apply(null,c);return d}}
function Gb(a,b){a=P(a);var c=-1!=a.indexOf("j")?Fb(a,b):H.get(b);"function"!==typeof c&&Q("unknown function pointer with signature "+a+": "+b);return c}var Hb=void 0;function Ib(a){a=Lb(a);var b=P(a);M(a);return b}function Mb(a,b){function c(f){e[f]||Ya[f]||(Za[f]?Za[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Hb(a+": "+d.map(Ib).join([", "]));}function Nb(a,b){for(var c=[],d=0;d<a;d++)c.push(C[(b>>2)+d]);return c}
function Ob(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function Pb(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=ab(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}var Qb=[],U=[{},{value:void 0},{value:null},{value:!0},{value:!1}];
function xb(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Qb.length?Qb.pop():U.length;U[b]={pa:1,value:a};return b}}function vb(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}function Rb(a,b){switch(b){case 2:return function(c){return this.fromWireType(za[c>>2])};case 3:return function(c){return this.fromWireType(Aa[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function Sb(a,b,c){switch(b){case 0:return c?function(d){return E[d]}:function(d){return B[d]};case 1:return c?function(d){return sa[d>>1]}:function(d){return ra[d>>1]};case 2:return c?function(d){return C[d>>2]}:function(d){return G[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var Tb;Tb=function(){return performance.now()};var Ub={};
function Vb(){if(!Wb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in Ub)a[b]=Ub[b];var c=[];for(b in a)c.push(b+"="+a[b]);Wb=c}return Wb}var Wb,Xb=[null,[],[]];function Yb(a){return 0===a%4&&(0!==a%100||0===a%400)}function Zb(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}
var $b=[31,29,31,30,31,30,31,31,30,31,30,31],ac=[31,28,31,30,31,30,31,31,30,31,30,31];function bc(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Yb(a.getFullYear())?$b:ac)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function cc(a,b,c,d){function e(h,p,v){for(h="number"===typeof h?h.toString():h||"";h.length<p;)h=v[0]+h;return h}function f(h,p){return e(h,p,"0")}function k(h,p){function v(D){return 0>D?-1:0<D?1:0}var t;0===(t=v(h.getFullYear()-p.getFullYear()))&&0===(t=v(h.getMonth()-p.getMonth()))&&(t=v(h.getDate()-p.getDate()));return t}function l(h){switch(h.getDay()){case 0:return new Date(h.getFullYear()-1,11,29);case 1:return h;case 2:return new Date(h.getFullYear(),0,3);case 3:return new Date(h.getFullYear(),
0,2);case 4:return new Date(h.getFullYear(),0,1);case 5:return new Date(h.getFullYear()-1,11,31);case 6:return new Date(h.getFullYear()-1,11,30)}}function n(h){h=bc(new Date(h.g+1900,0,1),h.R);var p=new Date(h.getFullYear()+1,0,4),v=l(new Date(h.getFullYear(),0,4));p=l(p);return 0>=k(v,h)?0>=k(p,h)?h.getFullYear()+1:h.getFullYear():h.getFullYear()-1}var m=C[d+40>>2];d={xa:C[d>>2],wa:C[d+4>>2],O:C[d+8>>2],I:C[d+12>>2],C:C[d+16>>2],g:C[d+20>>2],P:C[d+24>>2],R:C[d+28>>2],Aa:C[d+32>>2],va:C[d+36>>2],
ya:m?m?ma(B,m,void 0):"":""};c=c?ma(B,c,void 0):"";m={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var q in m)c=c.replace(new RegExp(q,"g"),m[q]);var A="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
u="January February March April May June July August September October November December".split(" ");m={"%a":function(h){return A[h.P].substring(0,3)},"%A":function(h){return A[h.P]},"%b":function(h){return u[h.C].substring(0,3)},"%B":function(h){return u[h.C]},"%C":function(h){return f((h.g+1900)/100|0,2)},"%d":function(h){return f(h.I,2)},"%e":function(h){return e(h.I,2," ")},"%g":function(h){return n(h).toString().substring(2)},"%G":function(h){return n(h)},"%H":function(h){return f(h.O,2)},"%I":function(h){h=
h.O;0==h?h=12:12<h&&(h-=12);return f(h,2)},"%j":function(h){return f(h.I+Zb(Yb(h.g+1900)?$b:ac,h.C-1),3)},"%m":function(h){return f(h.C+1,2)},"%M":function(h){return f(h.wa,2)},"%n":function(){return"\n"},"%p":function(h){return 0<=h.O&&12>h.O?"AM":"PM"},"%S":function(h){return f(h.xa,2)},"%t":function(){return"\t"},"%u":function(h){return h.P||7},"%U":function(h){var p=new Date(h.g+1900,0,1),v=0===p.getDay()?p:bc(p,7-p.getDay());h=new Date(h.g+1900,h.C,h.I);return 0>k(v,h)?f(Math.ceil((31-v.getDate()+
(Zb(Yb(h.getFullYear())?$b:ac,h.getMonth()-1)-31)+h.getDate())/7),2):0===k(v,p)?"01":"00"},"%V":function(h){var p=new Date(h.g+1901,0,4),v=l(new Date(h.g+1900,0,4));p=l(p);var t=bc(new Date(h.g+1900,0,1),h.R);return 0>k(t,v)?"53":0>=k(p,t)?"01":f(Math.ceil((v.getFullYear()<h.g+1900?h.R+32-v.getDate():h.R+1-v.getDate())/7),2)},"%w":function(h){return h.P},"%W":function(h){var p=new Date(h.g,0,1),v=1===p.getDay()?p:bc(p,0===p.getDay()?1:7-p.getDay()+1);h=new Date(h.g+1900,h.C,h.I);return 0>k(v,h)?f(Math.ceil((31-
v.getDate()+(Zb(Yb(h.getFullYear())?$b:ac,h.getMonth()-1)-31)+h.getDate())/7),2):0===k(v,p)?"01":"00"},"%y":function(h){return(h.g+1900).toString().substring(2)},"%Y":function(h){return h.g+1900},"%z":function(h){h=h.va;var p=0<=h;h=Math.abs(h)/60;return(p?"+":"-")+String("0000"+(h/60*100+h%60)).slice(-4)},"%Z":function(h){return h.ya},"%%":function(){return"%"}};for(q in m)0<=c.indexOf(q)&&(c=c.replace(new RegExp(q,"g"),m[q](d)));q=dc(c);if(q.length>b)return 0;E.set(q,a);return q.length-1}
for(var ec=Array(256),fc=0;256>fc;++fc)ec[fc]=String.fromCharCode(fc);Wa=ec;cb=g.BindingError=bb("BindingError");db=g.InternalError=bb("InternalError");S.prototype.isAliasOf=function(a){if(!(this instanceof S&&a instanceof S))return!1;var b=this.a.f.c,c=this.a.b,d=a.a.f.c;for(a=a.a.b;b.j;)c=b.J(c),b=b.j;for(;d.j;)a=d.J(a),d=d.j;return b===d&&c===a};
S.prototype.clone=function(){this.a.b||hb(this);if(this.a.F)return this.a.count.value+=1,this;var a=lb(Object.create(Object.getPrototypeOf(this),{a:{value:gb(this.a)}}));a.a.count.value+=1;a.a.u=!1;return a};S.prototype["delete"]=function(){this.a.b||hb(this);this.a.u&&!this.a.F&&Q("Object already scheduled for deletion");jb(this);kb(this.a);this.a.F||(this.a.h=void 0,this.a.b=void 0)};S.prototype.isDeleted=function(){return!this.a.b};
S.prototype.deleteLater=function(){this.a.b||hb(this);this.a.u&&!this.a.F&&Q("Object already scheduled for deletion");nb.push(this);1===nb.length&&mb&&mb(ob);this.a.u=!0;return this};T.prototype.ea=function(a){this.$&&(a=this.$(a));return a};T.prototype.X=function(a){this.s&&this.s(a)};T.prototype.argPackAdvance=8;T.prototype.readValueFromPointer=zb;T.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
T.prototype.fromWireType=function(a){function b(){return this.M?Db(this.c.B,{f:this.la,b:c,i:this,h:a}):Db(this.c.B,{f:this,b:a})}var c=this.ea(a);if(!c)return this.X(a),null;var d=Cb(this.c,c);if(void 0!==d){if(0===d.a.count.value)return d.a.b=c,d.a.h=a,d.clone();d=d.clone();this.X(a);return d}d=this.c.da(c);d=pb[d];if(!d)return b.call(this);d=this.L?d.aa:d.pointerType;var e=Ab(c,this.c,d.c);return null===e?b.call(this):this.M?Db(d.c.B,{f:d,b:e,i:this,h:a}):Db(d.c.B,{f:d,b:e})};
g.getInheritedInstanceCount=function(){return Object.keys(Bb).length};g.getLiveInheritedInstances=function(){var a=[],b;for(b in Bb)Bb.hasOwnProperty(b)&&a.push(Bb[b]);return a};g.flushPendingDeletes=ob;g.setDelayFunction=function(a){mb=a;nb.length&&mb&&mb(ob)};Hb=g.UnboundTypeError=bb("UnboundTypeError");g.count_emval_handles=function(){for(var a=0,b=5;b<U.length;++b)void 0!==U[b]&&++a;return a};g.get_first_emval=function(){for(var a=5;a<U.length;++a)if(void 0!==U[a])return U[a];return null};
function dc(a){var b=Array(oa(a)+1);na(a,b,0,b.length);return b}
var Rc={__cxa_allocate_exception:function(a){return Qa(a+16)+16},__cxa_atexit:function(){},__cxa_begin_catch:function(a){a=new L(a);var b=a.A();b.ga()||(b.W(!0),Ra--);b.N(!1);N.push(a);b.S();return a.ia()},__cxa_current_primary_exception:function(){if(!N.length)return 0;var a=N[N.length-1];a.A().S();return a.v()},__cxa_decrement_exception_refcount:function(a){a&&Ta(new K(a))},__cxa_end_catch:function(){V(0);var a=N.pop();Ta(a.A());a.U();O=0},__cxa_find_matching_catch_2:function(){var a=O;if(!a)return y=
0;var b=(new K(a)).D(),c=new L;c.H(a);if(!b)return y=0,c.b|0;var d=Array.prototype.slice.call(arguments),e=Y(),f=gc(4);C[f>>2]=a;for(var k=0;k<d.length;k++){var l=d[k];if(0===l||l===b)break;if(hc(l,b,f))return b=C[f>>2],a!==b&&c.G(b),y=l|0,c.b|0}Z(e);y=b|0;return c.b|0},__cxa_find_matching_catch_3:function(){var a=O;if(!a)return y=0;var b=(new K(a)).D(),c=new L;c.H(a);if(!b)return y=0,c.b|0;var d=Array.prototype.slice.call(arguments),e=Y(),f=gc(4);C[f>>2]=a;for(var k=0;k<d.length;k++){var l=d[k];
if(0===l||l===b)break;if(hc(l,b,f))return b=C[f>>2],a!==b&&c.G(b),y=l|0,c.b|0}Z(e);y=b|0;return c.b|0},__cxa_find_matching_catch_4:function(){var a=O;if(!a)return y=0;var b=(new K(a)).D(),c=new L;c.H(a);if(!b)return y=0,c.b|0;var d=Array.prototype.slice.call(arguments),e=Y(),f=gc(4);C[f>>2]=a;for(var k=0;k<d.length;k++){var l=d[k];if(0===l||l===b)break;if(hc(l,b,f))return b=C[f>>2],a!==b&&c.G(b),y=l|0,c.b|0}Z(e);y=b|0;return c.b|0},__cxa_find_matching_catch_6:function(){var a=O;if(!a)return y=0;var b=
(new K(a)).D(),c=new L;c.H(a);if(!b)return y=0,c.b|0;var d=Array.prototype.slice.call(arguments),e=Y(),f=gc(4);C[f>>2]=a;for(var k=0;k<d.length;k++){var l=d[k];if(0===l||l===b)break;if(hc(l,b,f))return b=C[f>>2],a!==b&&c.G(b),y=l|0,c.b|0}Z(e);y=b|0;return c.b|0},__cxa_free_exception:Sa,__cxa_increment_exception_refcount:function(a){a&&(new K(a)).S()},__cxa_rethrow:Ua,__cxa_rethrow_primary_exception:function(a){if(a){var b=new L;b.H(a);a=b.A();N.push(b);a.N(!0);Ua()}},__cxa_throw:function(a,b,c){(new K(a)).ka(b,
c);O=a;Ra++;throw a;},__cxa_uncaught_exceptions:function(){return Ra},__resumeException:function(a){a=new L(a);var b=a.v();O||(O=b);a.U();throw b;},_embind_register_bool:function(a,b,c,d,e){var f=Va(c);b=P(b);R(a,{name:b,fromWireType:function(k){return!!k},toWireType:function(k,l){return l?d:e},argPackAdvance:8,readValueFromPointer:function(k){if(1===c)var l=E;else if(2===c)l=sa;else if(4===c)l=C;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(l[k>>f])},m:null})},
_embind_register_class:function(a,b,c,d,e,f,k,l,n,m,q,A,u){q=P(q);f=Gb(e,f);l&&(l=Gb(k,l));m&&(m=Gb(n,m));u=Gb(A,u);var h=$a(q);rb(h,function(){Mb("Cannot construct "+q+" due to unbound types",[d])});fb([a,b,c],d?[d]:[],function(p){p=p[0];if(d){var v=p.c;var t=v.B}else t=S.prototype;p=ab(h,function(){if(Object.getPrototypeOf(this)!==D)throw new cb("Use 'new' to construct "+q);if(void 0===F.o)throw new cb(q+" has no accessible constructor");var W=F.o[arguments.length];if(void 0===W)throw new cb("Tried to invoke ctor of "+
q+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(F.o).toString()+") parameters instead!");return W.apply(this,arguments)});var D=Object.create(t,{constructor:{value:p}});p.prototype=D;var F=new sb(q,p,D,u,v,f,l,m);v=new T(q,F,!0,!1);t=new T(q+"*",F,!1,!1);var ha=new T(q+" const*",F,!1,!0);pb[a]={pointerType:t,aa:ha};Eb(h,p);return[v,t,ha]})},_embind_register_class_constructor:function(a,b,c,d,e,f){0<b||z("Assertion failed: undefined");var k=Nb(b,c);e=Gb(d,e);
var l=[f],n=[];fb([],[a],function(m){m=m[0];var q="constructor "+m.name;void 0===m.c.o&&(m.c.o=[]);if(void 0!==m.c.o[b-1])throw new cb("Cannot register multiple constructors with identical number of parameters ("+(b-1)+") for class '"+m.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");m.c.o[b-1]=function(){Mb("Cannot construct "+m.name+" due to unbound types",k)};fb([],k,function(A){m.c.o[b-1]=function(){arguments.length!==b-1&&Q(q+" called with "+
arguments.length+" arguments, expected "+(b-1));n.length=0;l.length=b;for(var u=1;u<b;++u)l[u]=A[u].toWireType(n,arguments[u-1]);u=e.apply(null,l);Ob(n);return A[0].fromWireType(u)};return[]});return[]})},_embind_register_class_function:function(a,b,c,d,e,f,k,l){var n=Nb(c,d);b=P(b);f=Gb(e,f);fb([],[a],function(m){function q(){Mb("Cannot call "+A+" due to unbound types",n)}m=m[0];var A=m.name+"."+b;l&&m.c.ma.push(b);var u=m.c.B,h=u[b];void 0===h||void 0===h.l&&h.className!==m.name&&h.K===c-2?(q.K=
c-2,q.className=m.name,u[b]=q):(qb(u,b,A),u[b].l[c-2]=q);fb([],n,function(p){var v=A,t=m,D=f,F=p.length;2>F&&Q("argTypes array size mismatch! Must at least get return value and 'this' types!");var ha=null!==p[1]&&null!==t,W=!1;for(t=1;t<p.length;++t)if(null!==p[t]&&void 0===p[t].m){W=!0;break}var Jb="void"!==p[0].name,X="",ia="";for(t=0;t<F-2;++t)X+=(0!==t?", ":"")+"arg"+t,ia+=(0!==t?", ":"")+"arg"+t+"Wired";v="return function "+$a(v)+"("+X+") {\nif (arguments.length !== "+(F-2)+") {\nthrowBindingError('function "+
v+" called with ' + arguments.length + ' arguments, expected "+(F-2)+" args!');\n}\n";W&&(v+="var destructors = [];\n");var Kb=W?"destructors":"null";X="throwBindingError invoker fn runDestructors retType classParam".split(" ");D=[Q,D,k,Ob,p[0],p[1]];ha&&(v+="var thisWired = classParam.toWireType("+Kb+", this);\n");for(t=0;t<F-2;++t)v+="var arg"+t+"Wired = argType"+t+".toWireType("+Kb+", arg"+t+"); // "+p[t+2].name+"\n",X.push("argType"+t),D.push(p[t+2]);ha&&(ia="thisWired"+(0<ia.length?", ":"")+
ia);v+=(Jb?"var rv = ":"")+"invoker(fn"+(0<ia.length?", ":"")+ia+");\n";if(W)v+="runDestructors(destructors);\n";else for(t=ha?1:2;t<p.length;++t)F=1===t?"thisWired":"arg"+(t-2)+"Wired",null!==p[t].m&&(v+=F+"_dtor("+F+"); // "+p[t].name+"\n",X.push(F+"_dtor"),D.push(p[t].m));Jb&&(v+="var ret = retType.fromWireType(rv);\nreturn ret;\n");X.push(v+"}\n");p=Pb(X).apply(null,D);void 0===u[b].l?(p.K=c-2,u[b]=p):u[b].l[c-2]=p;return[]});return[]})},_embind_register_emval:function(a,b){b=P(b);R(a,{name:b,
fromWireType:function(c){var d=U[c].value;4<c&&0===--U[c].pa&&(U[c]=void 0,Qb.push(c));return d},toWireType:function(c,d){return xb(d)},argPackAdvance:8,readValueFromPointer:zb,m:null})},_embind_register_float:function(a,b,c){c=Va(c);b=P(b);R(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,e){if("number"!==typeof e&&"boolean"!==typeof e)throw new TypeError('Cannot convert "'+vb(e)+'" to '+this.name);return e},argPackAdvance:8,readValueFromPointer:Rb(b,c),m:null})},_embind_register_integer:function(a,
b,c,d,e){function f(m){return m}b=P(b);-1===e&&(e=4294967295);var k=Va(c);if(0===d){var l=32-8*c;f=function(m){return m<<l>>>l}}var n=-1!=b.indexOf("unsigned");R(a,{name:b,fromWireType:f,toWireType:function(m,q){if("number"!==typeof q&&"boolean"!==typeof q)throw new TypeError('Cannot convert "'+vb(q)+'" to '+this.name);if(q<d||q>e)throw new TypeError('Passing a number "'+vb(q)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+e+"]!");return n?
q>>>0:q|0},argPackAdvance:8,readValueFromPointer:Sb(b,k,0!==d),m:null})},_embind_register_memory_view:function(a,b,c){function d(f){f>>=2;var k=G;return new e(ya,k[f+1],k[f])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=P(c);R(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{ja:!0})},_embind_register_std_string:function(a,b){b=P(b);var c="std::string"===b;R(a,{name:b,fromWireType:function(d){var e=G[d>>2];if(c)for(var f=
d+4,k=0;k<=e;++k){var l=d+4+k;if(k==e||0==B[l]){f=f?ma(B,f,l-f):"";if(void 0===n)var n=f;else n+=String.fromCharCode(0),n+=f;f=l+1}}else{n=Array(e);for(k=0;k<e;++k)n[k]=String.fromCharCode(B[d+4+k]);n=n.join("")}M(d);return n},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"===typeof e;f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array||Q("Cannot pass non-string to std::string");var k=(c&&f?function(){return oa(e)}:function(){return e.length})(),
l=Qa(4+k+1);G[l>>2]=k;if(c&&f)na(e,B,l+4,k+1);else if(f)for(f=0;f<k;++f){var n=e.charCodeAt(f);255<n&&(M(l),Q("String has UTF-16 code units that do not fit in 8 bits"));B[l+4+f]=n}else for(f=0;f<k;++f)B[l+4+f]=e[f];null!==d&&d.push(M,l);return l},argPackAdvance:8,readValueFromPointer:zb,m:function(d){M(d)}})},_embind_register_std_wstring:function(a,b,c){c=P(c);if(2===b){var d=qa;var e=ta;var f=ua;var k=function(){return ra};var l=1}else 4===b&&(d=va,e=wa,f=xa,k=function(){return G},l=2);R(a,{name:c,
fromWireType:function(n){for(var m=G[n>>2],q=k(),A,u=n+4,h=0;h<=m;++h){var p=n+4+h*b;if(h==m||0==q[p>>l])u=d(u,p-u),void 0===A?A=u:(A+=String.fromCharCode(0),A+=u),u=p+b}M(n);return A},toWireType:function(n,m){"string"!==typeof m&&Q("Cannot pass non-string to C++ string type "+c);var q=f(m),A=Qa(4+q+b);G[A>>2]=q>>l;e(m,A+4,q+b);null!==n&&n.push(M,A);return A},argPackAdvance:8,readValueFromPointer:zb,m:function(n){M(n)}})},_embind_register_void:function(a,b){b=P(b);R(a,{za:!0,name:b,argPackAdvance:0,
fromWireType:function(){},toWireType:function(){}})},abort:function(){z()},clock_gettime:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=Tb();else return C[ic()>>2]=28,-1;C[b>>2]=a/1E3|0;C[b+4>>2]=a%1E3*1E6|0;return 0},emscripten_memcpy_big:function(a,b,c){B.copyWithin(a,b,b+c)},emscripten_resize_heap:function(a){var b=B.length;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{ja.grow(Math.min(2147483648,
d)-ya.byteLength+65535>>>16);Ba();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},environ_get:function(a,b){var c=0;Vb().forEach(function(d,e){var f=b+c;e=C[a+4*e>>2]=f;for(f=0;f<d.length;++f)E[e++>>0]=d.charCodeAt(f);E[e>>0]=0;c+=d.length+1});return 0},environ_sizes_get:function(a,b){var c=Vb();C[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});C[b>>2]=d;return 0},fd_write:function(a,b,c,d){for(var e=0,f=0;f<c;f++){for(var k=C[b+8*f>>2],l=C[b+(8*f+4)>>2],n=0;n<l;n++){var m=
B[k+n],q=Xb[a];0===m||10===m?((1===a?ea:x)(ma(q,0)),q.length=0):q.push(m)}e+=l}C[d>>2]=e;return 0},getTempRet0:function(){return y|0},invoke_diii:jc,invoke_fiii:kc,invoke_i:lc,invoke_idiii:mc,invoke_ii:nc,invoke_iid:oc,invoke_iif:pc,invoke_iii:qc,invoke_iiii:rc,invoke_iiiii:sc,invoke_iiiiii:tc,invoke_iiiiiii:uc,invoke_iiiiiiii:vc,invoke_iiiiiiiiiii:wc,invoke_iiiiiiiiiiii:xc,invoke_iiiiiiiiiiiii:yc,invoke_iij:zc,invoke_iijj:Ac,invoke_ijj:Bc,invoke_ijjiii:Cc,invoke_ji:Dc,invoke_jii:Ec,invoke_jiiii:Fc,
invoke_v:Gc,invoke_vi:Hc,invoke_vii:Ic,invoke_viid:Jc,invoke_viii:Kc,invoke_viiii:Lc,invoke_viiiii:Mc,invoke_viiiiii:Nc,invoke_viiiiiii:Oc,invoke_viiiiiiiiii:Pc,invoke_viiiiiiiiiiiiiii:Qc,llvm_eh_typeid_for:function(a){return a},setTempRet0:function(a){y=a|0},strftime_l:function(a,b,c,d){return cc(a,b,c,d)}};
(function(){function a(e){g.asm=e.exports;ja=g.asm.memory;Ba();H=g.asm.__indirect_function_table;I--;g.monitorRunDependencies&&g.monitorRunDependencies(I);0==I&&(null!==Ia&&(clearInterval(Ia),Ia=null),Ja&&(e=Ja,Ja=null,e()))}function b(e){a(e.instance)}function c(e){return Na().then(function(f){return WebAssembly.instantiate(f,d)}).then(e,function(f){x("failed to asynchronously prepare wasm: "+f);z(f)})}var d={env:Rc,wasi_snapshot_preview1:Rc};I++;g.monitorRunDependencies&&g.monitorRunDependencies(I);
if(g.instantiateWasm)try{return g.instantiateWasm(d,a)}catch(e){return x("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return fa||"function"!==typeof WebAssembly.instantiateStreaming||Ka()||"function"!==typeof fetch?c(b):fetch(J,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){x("wasm streaming compile failed: "+f);x("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ba);return{}})();
var Ga=g.___wasm_call_ctors=function(){return(Ga=g.___wasm_call_ctors=g.asm.__wasm_call_ctors).apply(null,arguments)};g._memset=function(){return(g._memset=g.asm.memset).apply(null,arguments)};
var ic=g.___errno_location=function(){return(ic=g.___errno_location=g.asm.__errno_location).apply(null,arguments)},M=g._free=function(){return(M=g._free=g.asm.free).apply(null,arguments)},Qa=g._malloc=function(){return(Qa=g._malloc=g.asm.malloc).apply(null,arguments)},Lb=g.___getTypeName=function(){return(Lb=g.___getTypeName=g.asm.__getTypeName).apply(null,arguments)};
g.___embind_register_native_and_builtin_types=function(){return(g.___embind_register_native_and_builtin_types=g.asm.__embind_register_native_and_builtin_types).apply(null,arguments)};g.__get_tzname=function(){return(g.__get_tzname=g.asm._get_tzname).apply(null,arguments)};g.__get_daylight=function(){return(g.__get_daylight=g.asm._get_daylight).apply(null,arguments)};g.__get_timezone=function(){return(g.__get_timezone=g.asm._get_timezone).apply(null,arguments)};
var Y=g.stackSave=function(){return(Y=g.stackSave=g.asm.stackSave).apply(null,arguments)},Z=g.stackRestore=function(){return(Z=g.stackRestore=g.asm.stackRestore).apply(null,arguments)},gc=g.stackAlloc=function(){return(gc=g.stackAlloc=g.asm.stackAlloc).apply(null,arguments)},V=g._setThrew=function(){return(V=g._setThrew=g.asm.setThrew).apply(null,arguments)},hc=g.___cxa_can_catch=function(){return(hc=g.___cxa_can_catch=g.asm.__cxa_can_catch).apply(null,arguments)},Pa=g.___cxa_is_pointer_type=function(){return(Pa=
g.___cxa_is_pointer_type=g.asm.__cxa_is_pointer_type).apply(null,arguments)};g._memalign=function(){return(g._memalign=g.asm.memalign).apply(null,arguments)};g.dynCall_viijii=function(){return(g.dynCall_viijii=g.asm.dynCall_viijii).apply(null,arguments)};
var Sc=g.dynCall_iij=function(){return(Sc=g.dynCall_iij=g.asm.dynCall_iij).apply(null,arguments)},Tc=g.dynCall_ijj=function(){return(Tc=g.dynCall_ijj=g.asm.dynCall_ijj).apply(null,arguments)},Uc=g.dynCall_ijjiii=function(){return(Uc=g.dynCall_ijjiii=g.asm.dynCall_ijjiii).apply(null,arguments)},Vc=g.dynCall_ji=function(){return(Vc=g.dynCall_ji=g.asm.dynCall_ji).apply(null,arguments)},Wc=g.dynCall_iijj=function(){return(Wc=g.dynCall_iijj=g.asm.dynCall_iijj).apply(null,arguments)};
g.dynCall_jiji=function(){return(g.dynCall_jiji=g.asm.dynCall_jiji).apply(null,arguments)};var Xc=g.dynCall_jiiii=function(){return(Xc=g.dynCall_jiiii=g.asm.dynCall_jiiii).apply(null,arguments)};g.dynCall_iiiiij=function(){return(g.dynCall_iiiiij=g.asm.dynCall_iiiiij).apply(null,arguments)};g.dynCall_iiiiijj=function(){return(g.dynCall_iiiiijj=g.asm.dynCall_iiiiijj).apply(null,arguments)};g.dynCall_iiiiiijj=function(){return(g.dynCall_iiiiiijj=g.asm.dynCall_iiiiiijj).apply(null,arguments)};
var Yc=g.dynCall_jii=function(){return(Yc=g.dynCall_jii=g.asm.dynCall_jii).apply(null,arguments)};function nc(a,b){var c=Y();try{return H.get(a)(b)}catch(d){Z(c);if(d!==d+0&&"longjmp"!==d)throw d;V(1,0)}}function qc(a,b,c){var d=Y();try{return H.get(a)(b,c)}catch(e){Z(d);if(e!==e+0&&"longjmp"!==e)throw e;V(1,0)}}function Nc(a,b,c,d,e,f,k){var l=Y();try{H.get(a)(b,c,d,e,f,k)}catch(n){Z(l);if(n!==n+0&&"longjmp"!==n)throw n;V(1,0)}}
function Lc(a,b,c,d,e){var f=Y();try{H.get(a)(b,c,d,e)}catch(k){Z(f);if(k!==k+0&&"longjmp"!==k)throw k;V(1,0)}}function Ic(a,b,c){var d=Y();try{H.get(a)(b,c)}catch(e){Z(d);if(e!==e+0&&"longjmp"!==e)throw e;V(1,0)}}function Hc(a,b){var c=Y();try{H.get(a)(b)}catch(d){Z(c);if(d!==d+0&&"longjmp"!==d)throw d;V(1,0)}}function Kc(a,b,c,d){var e=Y();try{H.get(a)(b,c,d)}catch(f){Z(e);if(f!==f+0&&"longjmp"!==f)throw f;V(1,0)}}
function Gc(a){var b=Y();try{H.get(a)()}catch(c){Z(b);if(c!==c+0&&"longjmp"!==c)throw c;V(1,0)}}function rc(a,b,c,d){var e=Y();try{return H.get(a)(b,c,d)}catch(f){Z(e);if(f!==f+0&&"longjmp"!==f)throw f;V(1,0)}}function tc(a,b,c,d,e,f){var k=Y();try{return H.get(a)(b,c,d,e,f)}catch(l){Z(k);if(l!==l+0&&"longjmp"!==l)throw l;V(1,0)}}function lc(a){var b=Y();try{return H.get(a)()}catch(c){Z(b);if(c!==c+0&&"longjmp"!==c)throw c;V(1,0)}}
function sc(a,b,c,d,e){var f=Y();try{return H.get(a)(b,c,d,e)}catch(k){Z(f);if(k!==k+0&&"longjmp"!==k)throw k;V(1,0)}}function uc(a,b,c,d,e,f,k){var l=Y();try{return H.get(a)(b,c,d,e,f,k)}catch(n){Z(l);if(n!==n+0&&"longjmp"!==n)throw n;V(1,0)}}function Mc(a,b,c,d,e,f){var k=Y();try{H.get(a)(b,c,d,e,f)}catch(l){Z(k);if(l!==l+0&&"longjmp"!==l)throw l;V(1,0)}}function oc(a,b,c){var d=Y();try{return H.get(a)(b,c)}catch(e){Z(d);if(e!==e+0&&"longjmp"!==e)throw e;V(1,0)}}
function mc(a,b,c,d,e){var f=Y();try{return H.get(a)(b,c,d,e)}catch(k){Z(f);if(k!==k+0&&"longjmp"!==k)throw k;V(1,0)}}function pc(a,b,c){var d=Y();try{return H.get(a)(b,c)}catch(e){Z(d);if(e!==e+0&&"longjmp"!==e)throw e;V(1,0)}}function vc(a,b,c,d,e,f,k,l){var n=Y();try{return H.get(a)(b,c,d,e,f,k,l)}catch(m){Z(n);if(m!==m+0&&"longjmp"!==m)throw m;V(1,0)}}function wc(a,b,c,d,e,f,k,l,n,m,q){var A=Y();try{return H.get(a)(b,c,d,e,f,k,l,n,m,q)}catch(u){Z(A);if(u!==u+0&&"longjmp"!==u)throw u;V(1,0)}}
function yc(a,b,c,d,e,f,k,l,n,m,q,A,u){var h=Y();try{return H.get(a)(b,c,d,e,f,k,l,n,m,q,A,u)}catch(p){Z(h);if(p!==p+0&&"longjmp"!==p)throw p;V(1,0)}}function kc(a,b,c,d){var e=Y();try{return H.get(a)(b,c,d)}catch(f){Z(e);if(f!==f+0&&"longjmp"!==f)throw f;V(1,0)}}function jc(a,b,c,d){var e=Y();try{return H.get(a)(b,c,d)}catch(f){Z(e);if(f!==f+0&&"longjmp"!==f)throw f;V(1,0)}}
function Oc(a,b,c,d,e,f,k,l){var n=Y();try{H.get(a)(b,c,d,e,f,k,l)}catch(m){Z(n);if(m!==m+0&&"longjmp"!==m)throw m;V(1,0)}}function xc(a,b,c,d,e,f,k,l,n,m,q,A){var u=Y();try{return H.get(a)(b,c,d,e,f,k,l,n,m,q,A)}catch(h){Z(u);if(h!==h+0&&"longjmp"!==h)throw h;V(1,0)}}function Pc(a,b,c,d,e,f,k,l,n,m,q){var A=Y();try{H.get(a)(b,c,d,e,f,k,l,n,m,q)}catch(u){Z(A);if(u!==u+0&&"longjmp"!==u)throw u;V(1,0)}}
function Qc(a,b,c,d,e,f,k,l,n,m,q,A,u,h,p,v){var t=Y();try{H.get(a)(b,c,d,e,f,k,l,n,m,q,A,u,h,p,v)}catch(D){Z(t);if(D!==D+0&&"longjmp"!==D)throw D;V(1,0)}}function Jc(a,b,c,d){var e=Y();try{H.get(a)(b,c,d)}catch(f){Z(e);if(f!==f+0&&"longjmp"!==f)throw f;V(1,0)}}function zc(a,b,c,d){var e=Y();try{return Sc(a,b,c,d)}catch(f){Z(e);if(f!==f+0&&"longjmp"!==f)throw f;V(1,0)}}function Bc(a,b,c,d,e){var f=Y();try{return Tc(a,b,c,d,e)}catch(k){Z(f);if(k!==k+0&&"longjmp"!==k)throw k;V(1,0)}}
function Cc(a,b,c,d,e,f,k,l){var n=Y();try{return Uc(a,b,c,d,e,f,k,l)}catch(m){Z(n);if(m!==m+0&&"longjmp"!==m)throw m;V(1,0)}}function Dc(a,b){var c=Y();try{return Vc(a,b)}catch(d){Z(c);if(d!==d+0&&"longjmp"!==d)throw d;V(1,0)}}function Ac(a,b,c,d,e,f){var k=Y();try{return Wc(a,b,c,d,e,f)}catch(l){Z(k);if(l!==l+0&&"longjmp"!==l)throw l;V(1,0)}}function Fc(a,b,c,d,e){var f=Y();try{return Xc(a,b,c,d,e)}catch(k){Z(f);if(k!==k+0&&"longjmp"!==k)throw k;V(1,0)}}
function Ec(a,b,c){var d=Y();try{return Yc(a,b,c)}catch(e){Z(d);if(e!==e+0&&"longjmp"!==e)throw e;V(1,0)}}var Zc;Ja=function $c(){Zc||ad();Zc||(Ja=$c)};
function ad(){function a(){if(!Zc&&(Zc=!0,g.calledRun=!0,!ka)){Oa(Da);Oa(Ea);aa(g);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var b=g.postRun.shift();Fa.unshift(b)}Oa(Fa)}}if(!(0<I)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Ha();Oa(Ca);0<I||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);a()},1)):a())}}
g.run=ad;if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();ad();


  return Tiro.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = Tiro;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return Tiro; });
else if (typeof exports === 'object')
  exports["Tiro"] = Tiro;
