
var Tiro = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  
  return (
function(Tiro) {
  Tiro = Tiro || {};


var f;f||(f=typeof Tiro !== 'undefined' ? Tiro : {});var aa,ba;f.ready=new Promise(function(a,b){aa=a;ba=b});var ca={},da;for(da in f)f.hasOwnProperty(da)&&(ca[da]=f[da]);var ea="./this.program",fa="";document.currentScript&&(fa=document.currentScript.src);_scriptDir&&(fa=_scriptDir);0!==fa.indexOf("blob:")?fa=fa.substr(0,fa.lastIndexOf("/")+1):fa="";var ha=f.print||console.log.bind(console),p=f.printErr||console.warn.bind(console);for(da in ca)ca.hasOwnProperty(da)&&(f[da]=ca[da]);
ca=null;f.thisProgram&&(ea=f.thisProgram);var q=0,ia;f.wasmBinary&&(ia=f.wasmBinary);var noExitRuntime;f.noExitRuntime&&(noExitRuntime=f.noExitRuntime);"object"!==typeof WebAssembly&&y("no native wasm support detected");var ja,ka=new WebAssembly.Table({initial:2033,maximum:2033,element:"anyfunc"}),la=!1;function ma(a,b){a||y("Assertion failed: "+b)}var na="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function oa(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&na)return na.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|h:(e&7)<<18|g<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}
function pa(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var l=a.charCodeAt(++g);h=65536+((h&1023)<<10)|l&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}
function qa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}var ra="undefined"!==typeof TextDecoder?new TextDecoder("utf-16le"):void 0;function sa(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&ta[c];)++c;c<<=1;if(32<c-a&&ra)return ra.decode(z.subarray(a,c));c=0;for(d="";;){var e=A[a+2*c>>1];if(0==e||c==b/2)return d;++c;d+=String.fromCharCode(e)}}
function ua(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)A[b>>1]=a.charCodeAt(e),b+=2;A[b>>1]=0;return b-d}function va(a){return 2*a.length}function wa(a,b){for(var c=0,d="";!(c>=b/4);){var e=B[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}
function xa(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var g=a.charCodeAt(e);if(55296<=g&&57343>=g){var h=a.charCodeAt(++e);g=65536+((g&1023)<<10)|h&1023}B[b>>2]=g;b+=4;if(b+4>c)break}B[b>>2]=0;return b-d}function ya(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}var za,C,z,A,ta,B,Aa,Ba,Ca;
function Ea(a){za=a;f.HEAP8=C=new Int8Array(a);f.HEAP16=A=new Int16Array(a);f.HEAP32=B=new Int32Array(a);f.HEAPU8=z=new Uint8Array(a);f.HEAPU16=ta=new Uint16Array(a);f.HEAPU32=Aa=new Uint32Array(a);f.HEAPF32=Ba=new Float32Array(a);f.HEAPF64=Ca=new Float64Array(a)}var Fa=f.INITIAL_MEMORY||16777216;f.wasmMemory?ja=f.wasmMemory:ja=new WebAssembly.Memory({initial:Fa/65536,maximum:32768});ja&&(za=ja.buffer);Fa=za.byteLength;Ea(za);B[27380]=5352576;
function Ga(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(f);else{var c=b.qb;"number"===typeof c?void 0===b.Ka?f.dynCall_v(c):f.dynCall_vi(c,b.Ka):c(void 0===b.Ka?null:b.Ka)}}}var Ha=[],Ia=[],Ja=[],Ka=[];function La(){var a=f.preRun.shift();Ha.unshift(a)}var Ma=Math.abs,Na=Math.ceil,Oa=Math.floor,Pa=Math.min,Qa=0,Ra=null,Sa=null;f.preloadedImages={};f.preloadedAudios={};
function y(a){if(f.onAbort)f.onAbort(a);p(a);la=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}function Ta(){var a=Ua;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var Ua="tiro.wasm";if(!Ta()){var Va=Ua;Ua=f.locateFile?f.locateFile(Va,fa):fa+Va}
function Wa(){try{if(ia)return new Uint8Array(ia);throw"both async and sync fetching of the wasm failed";}catch(a){y(a)}}function Xa(){return ia||"function"!==typeof fetch?new Promise(function(a){a(Wa())}):fetch(Ua,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+Ua+"'";return a.arrayBuffer()}).catch(function(){return Wa()})}var Ya,Za;Ia.push({qb:function(){$a()}});var D={},ab=[];
function bb(a){if(!a||D[a])return a;for(var b in D)for(var c=+b,d=D[c].ra,e=d.length,g=0;g<e;g++)if(d[g]===a)return c;return a}function cb(a){if(a){var b=D[a];b.Z--;0!==b.Z||b.oa||(b.ga&&f.dynCall_ii(b.ga,a),delete D[a],F(a))}}var db=0;function eb(){var a=ab.pop();a=bb(a);D[a].oa||(ab.push(a),D[a].oa=!0);db=a;throw a;}function fb(a){B[gb()>>2]=a}
function hb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function ib(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=hb(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function jb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function kb(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function lb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=hb(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var mb=[];function nb(a,b){mb[a]={input:[],B:[],ba:b};ob(a,pb)}
var pb={open:function(a){var b=mb[a.node.Da];if(!b)throw new G(43);a.v=b;a.seekable=!1},close:function(a){a.v.ba.flush(a.v)},flush:function(a){a.v.ba.flush(a.v)},read:function(a,b,c,d){if(!a.v||!a.v.ba.bb)throw new G(60);for(var e=0,g=0;g<d;g++){try{var h=a.v.ba.bb(a.v)}catch(l){throw new G(29);}if(void 0===h&&0===e)throw new G(6);if(null===h||void 0===h)break;e++;b[c+g]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.v||!a.v.ba.Na)throw new G(60);try{for(var e=0;e<d;e++)a.v.ba.Na(a.v,
b[c+e])}catch(g){throw new G(29);}d&&(a.node.timestamp=Date.now());return e}},sb={bb:function(a){if(!a.input.length){var b=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=qb(b,!0)}return a.input.shift()},Na:function(a,b){null===b||10===b?(ha(oa(a.B,0)),a.B=[]):0!=b&&a.B.push(b)},flush:function(a){a.B&&0<a.B.length&&(ha(oa(a.B,0)),a.B=[])}},tb=
{Na:function(a,b){null===b||10===b?(p(oa(a.B,0)),a.B=[]):0!=b&&a.B.push(b)},flush:function(a){a.B&&0<a.B.length&&(p(oa(a.B,0)),a.B=[])}},K={P:null,J:function(){return K.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new G(63);K.P||(K.P={dir:{node:{V:K.h.V,T:K.h.T,ia:K.h.ia,za:K.h.za,ib:K.h.ib,kb:K.h.kb,jb:K.h.jb,gb:K.h.gb,Ea:K.h.Ea},stream:{X:K.c.X}},file:{node:{V:K.h.V,T:K.h.T},stream:{X:K.c.X,read:K.c.read,write:K.c.write,Va:K.c.Va,Aa:K.c.Aa,
Ca:K.c.Ca}},link:{node:{V:K.h.V,T:K.h.T,na:K.h.na},stream:{}},Xa:{node:{V:K.h.V,T:K.h.T},stream:ub}});c=vb(a,b,c,d);16384===(c.mode&61440)?(c.h=K.P.dir.node,c.c=K.P.dir.stream,c.f={}):32768===(c.mode&61440)?(c.h=K.P.file.node,c.c=K.P.file.stream,c.m=0,c.f=null):40960===(c.mode&61440)?(c.h=K.P.link.node,c.c=K.P.link.stream):8192===(c.mode&61440)&&(c.h=K.P.Xa.node,c.c=K.P.Xa.stream);c.timestamp=Date.now();a&&(a.f[b]=c);return c},Ub:function(a){if(a.f&&a.f.subarray){for(var b=[],c=0;c<a.m;++c)b.push(a.f[c]);
return b}return a.f},Vb:function(a){return a.f?a.f.subarray?a.f.subarray(0,a.m):new Uint8Array(a.f):new Uint8Array(0)},Za:function(a,b){var c=a.f?a.f.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.f,a.f=new Uint8Array(b),0<a.m&&a.f.set(c.subarray(0,a.m),0))},Gb:function(a,b){if(a.m!=b)if(0==b)a.f=null,a.m=0;else{if(!a.f||a.f.subarray){var c=a.f;a.f=new Uint8Array(b);c&&a.f.set(c.subarray(0,Math.min(b,a.m)))}else if(a.f||(a.f=[]),a.f.length>b)a.f.length=b;else for(;a.f.length<
b;)a.f.push(0);a.m=b}},h:{V:function(a){var b={};b.Sb=8192===(a.mode&61440)?a.id:1;b.Yb=a.id;b.mode=a.mode;b.ac=1;b.uid=0;b.Xb=0;b.Da=a.Da;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.m:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.Pb=new Date(a.timestamp);b.$b=new Date(a.timestamp);b.Rb=new Date(a.timestamp);b.lb=4096;b.Qb=Math.ceil(b.size/b.lb);return b},T:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&
K.Gb(a,b.size)},ia:function(){throw wb[44];},za:function(a,b,c,d){return K.createNode(a,b,c,d)},ib:function(a,b,c){if(16384===(a.mode&61440)){try{var d=xb(b,c)}catch(g){}if(d)for(var e in d.f)throw new G(55);}delete a.parent.f[a.name];a.name=c;b.f[c]=a;a.parent=b},kb:function(a,b){delete a.f[b]},jb:function(a,b){var c=xb(a,b),d;for(d in c.f)throw new G(55);delete a.f[b]},gb:function(a){var b=[".",".."],c;for(c in a.f)a.f.hasOwnProperty(c)&&b.push(c);return b},Ea:function(a,b,c){a=K.createNode(a,b,
41471,0);a.link=c;return a},na:function(a){if(40960!==(a.mode&61440))throw new G(28);return a.link}},c:{read:function(a,b,c,d,e){var g=a.node.f;if(e>=a.node.m)return 0;a=Math.min(a.node.m-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write:function(a,b,c,d,e,g){b.buffer===C.buffer&&(g=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.f||a.f.subarray)){if(g)return a.f=b.subarray(c,c+d),a.m=d;if(0===a.m&&0===e)return a.f=b.slice(c,
c+d),a.m=d;if(e+d<=a.m)return a.f.set(b.subarray(c,c+d),e),d}K.Za(a,e+d);if(a.f.subarray&&b.subarray)a.f.set(b.subarray(c,c+d),e);else for(g=0;g<d;g++)a.f[e+g]=b[c+g];a.m=Math.max(a.m,e+d);return d},X:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.m);if(0>b)throw new G(28);return b},Va:function(a,b,c){K.Za(a.node,b+c);a.node.m=Math.max(a.node.m,b+c)},Aa:function(a,b,c,d,e,g){ma(0===b);if(32768!==(a.node.mode&61440))throw new G(43);a=a.node.f;if(g&2||a.buffer!==
za){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;g=16384*Math.ceil(c/16384);for(b=yb(g);c<g;)C[b+c++]=0;c=b;if(!c)throw new G(48);C.set(a,c)}else d=!1,c=a.byteOffset;return{i:c,Ja:d}},Ca:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new G(43);if(e&2)return 0;K.c.write(a,b,0,d,c,!1);return 0}}},zb=null,Ab={},Bb=[],Cb=1,Db=null,Eb=!0,Fb={},G=null,wb={};
function Gb(a,b){a=lb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={ab:!0,Oa:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.Oa)throw new G(32);a=hb(a.split("/").filter(function(h){return!!h}),!1);var e=zb;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;e=xb(e,a[d]);c=ib(c+"/"+a[d]);e.Ba&&(!g||g&&b.ab)&&(e=e.Ba.root);if(!g||b.$a)for(g=0;40960===(e.mode&61440);)if(e=Hb(c),c=lb(jb(c),e),e=Gb(c,{Oa:b.Oa}).node,40<g++)throw new G(32);}return{path:c,node:e}}
function Ib(a){for(var b;;){if(a===a.parent)return a=a.J.eb,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Jb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Db.length}function xb(a,b){var c;if(c=(c=Kb(a,"x"))?c:a.h.ia?0:2)throw new G(c,a);for(c=Db[Jb(a.id,b)];c;c=c.zb){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.h.ia(a,b)}function vb(a,b,c,d){a=new Lb(a,b,c,d);b=Jb(a.parent.id,a.name);a.zb=Db[b];return Db[b]=a}
var Mb={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Nb(a){var b=Mb[a];if("undefined"===typeof b)throw Error("Unknown file open mode: "+a);return b}function Ob(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Kb(a,b){if(Eb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0}
function Pb(a,b){try{return xb(a,b),20}catch(c){}return Kb(a,"wx")}function Qb(a,b){b=b||4096;for(a=a||0;a<=b;a++)if(!Bb[a])return a;throw new G(33);}function Rb(a,b,c){Sb||(Sb=function(){},Sb.prototype={});var d=new Sb,e;for(e in a)d[e]=a[e];a=d;b=Qb(b,c);a.A=b;return Bb[b]=a}var ub={open:function(a){a.c=Ab[a.node.Da].c;a.c.open&&a.c.open(a)},X:function(){throw new G(70);}};function ob(a,b){Ab[a]={c:b}}
function Wb(a,b){var c="/"===b,d=!b;if(c&&zb)throw new G(10);if(!c&&!d){var e=Gb(b,{ab:!1});b=e.path;e=e.node;if(e.Ba)throw new G(10);if(16384!==(e.mode&61440))throw new G(54);}b={type:a,bc:{},eb:b,yb:[]};a=a.J(b);a.J=b;b.root=a;c?zb=a:e&&(e.Ba=b,e.J&&e.J.yb.push(b));return a}function Xb(a,b,c){var d=Gb(a,{parent:!0}).node;a=kb(a);if(!a||"."===a||".."===a)throw new G(28);var e=Pb(d,a);if(e)throw new G(e);if(!d.h.za)throw new G(63);return d.h.za(d,a,b,c)}function Yb(a){Xb(a,16895,0)}
function Zb(a,b,c){"undefined"===typeof c&&(c=b,b=438);Xb(a,b|8192,c)}function $b(a,b){if(!lb(a))throw new G(44);var c=Gb(b,{parent:!0}).node;if(!c)throw new G(44);b=kb(b);var d=Pb(c,b);if(d)throw new G(d);if(!c.h.Ea)throw new G(63);c.h.Ea(c,b,a)}function Hb(a){a=Gb(a).node;if(!a)throw new G(44);if(!a.h.na)throw new G(28);return lb(Ib(a.parent),a.h.na(a))}
function ac(a,b,c,d){if(""===a)throw new G(44);b="string"===typeof b?Nb(b):b;c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var e=a;else{a=ib(a);try{e=Gb(a,{$a:!(b&131072)}).node}catch(l){}}var g=!1;if(b&64)if(e){if(b&128)throw new G(20);}else e=Xb(a,c,0),g=!0;if(!e)throw new G(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new G(54);if(!g&&(c=e?40960===(e.mode&61440)?32:16384===(e.mode&61440)&&("r"!==Ob(b)||b&512)?31:Kb(e,Ob(b)):44))throw new G(c);
if(b&512){c=e;var h;"string"===typeof c?h=Gb(c,{$a:!0}).node:h=c;if(!h.h.T)throw new G(63);if(16384===(h.mode&61440))throw new G(31);if(32768!==(h.mode&61440))throw new G(28);if(c=Kb(h,"w"))throw new G(c);h.h.T(h,{size:0,timestamp:Date.now()})}b&=-131713;d=Rb({node:e,path:Ib(e),flags:b,seekable:!0,position:0,c:e.c,Nb:[],error:!1},d,void 0);d.c.open&&d.c.open(d);!f.logReadFiles||b&1||(bc||(bc={}),a in bc||(bc[a]=1,p("FS.trackingDelegate error on read file: "+a)));try{Fb.onOpenFile&&(e=0,1!==(b&2097155)&&
(e|=1),0!==(b&2097155)&&(e|=2),Fb.onOpenFile(a,e))}catch(l){p("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+l.message)}return d}function cc(a,b,c){if(null===a.A)throw new G(8);if(!a.seekable||!a.c.X)throw new G(70);if(0!=c&&1!=c&&2!=c)throw new G(28);a.position=a.c.X(a,b,c);a.Nb=[]}
function dc(a,b,c,d){var e=C;if(0>c||0>d)throw new G(28);if(null===a.A)throw new G(8);if(1===(a.flags&2097155))throw new G(8);if(16384===(a.node.mode&61440))throw new G(31);if(!a.c.read)throw new G(28);var g="undefined"!==typeof d;if(!g)d=a.position;else if(!a.seekable)throw new G(70);b=a.c.read(a,e,b,c,d);g||(a.position+=b);return b}
function ec(a,b,c,d){var e=C;if(0>c||0>d)throw new G(28);if(null===a.A)throw new G(8);if(0===(a.flags&2097155))throw new G(8);if(16384===(a.node.mode&61440))throw new G(31);if(!a.c.write)throw new G(28);a.seekable&&a.flags&1024&&cc(a,0,2);var g="undefined"!==typeof d;if(!g)d=a.position;else if(!a.seekable)throw new G(70);b=a.c.write(a,e,b,c,d,void 0);g||(a.position+=b);try{if(a.path&&Fb.onWriteToFile)Fb.onWriteToFile(a.path)}catch(h){p("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+
h.message)}return b}function fc(){G||(G=function(a,b){this.node=b;this.Hb=function(c){this.l=c};this.Hb(a);this.message="FS error"},G.prototype=Error(),G.prototype.constructor=G,[44].forEach(function(a){wb[a]=new G(a);wb[a].stack="<generic error, no stack>"}))}var gc;function hc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function ic(a,b,c){a=ib("/dev/"+a);var d=hc(!!b,!!c);jc||(jc=64);var e=jc++<<8|0;ob(e,{open:function(g){g.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(g,h,l,n){for(var m=0,t=0;t<n;t++){try{var w=b()}catch(u){throw new G(29);}if(void 0===w&&0===m)throw new G(6);if(null===w||void 0===w)break;m++;h[l+t]=w}m&&(g.node.timestamp=Date.now());return m},write:function(g,h,l,n){for(var m=0;m<n;m++)try{c(h[l+m])}catch(t){throw new G(29);}n&&(g.node.timestamp=Date.now());return m}});
Zb(a,d,e)}var jc,L={},Sb,bc,kc={},lc=void 0;function O(){lc+=4;return B[lc-4>>2]}function mc(a){a=Bb[a];if(!a)throw new G(8);return a}
var S={H:8192,J:function(){return vb(null,"/",16895,0)},nb:function(){var a={s:[]};a.s.push({buffer:new Uint8Array(S.H),offset:0,K:0});var b=S.O(),c=S.O(),d=vb(S.root,b,4096,0),e=vb(S.root,c,4096,0);d.ka=a;e.ka=a;a=Rb({path:b,node:d,flags:Nb("r"),seekable:!1,c:S.c});d.stream=a;c=Rb({path:c,node:e,flags:Nb("w"),seekable:!1,c:S.c});e.stream=c;return{Fb:a.A,Ob:c.A}},c:{la:function(a){var b=a.node.ka;if(1===(a.flags&2097155))return 260;if(0<b.s.length)for(a=0;a<b.s.length;a++){var c=b.s[a];if(0<c.offset-
c.K)return 65}return 0},ha:function(){return 28},Tb:function(){return 28},read:function(a,b,c,d){a=a.node.ka;for(var e=0,g=0;g<a.s.length;g++){var h=a.s[g];e+=h.offset-h.K}ma(b instanceof ArrayBuffer||ArrayBuffer.isView(b));b=b.subarray(c,c+d);if(0>=d)return 0;if(0==e)throw new G(6);c=d=Math.min(e,d);for(g=e=0;g<a.s.length;g++){h=a.s[g];var l=h.offset-h.K;if(d<=l){var n=h.buffer.subarray(h.K,h.offset);d<l?(n=n.subarray(0,d),h.K+=d):e++;b.set(n);break}else n=h.buffer.subarray(h.K,h.offset),b.set(n),
b=b.subarray(n.byteLength),d-=n.byteLength,e++}e&&e==a.s.length&&(e--,a.s[e].offset=0,a.s[e].K=0);a.s.splice(0,e);return c},write:function(a,b,c,d){a=a.node.ka;ma(b instanceof ArrayBuffer||ArrayBuffer.isView(b));b=b.subarray(c,c+d);c=b.byteLength;if(0>=c)return 0;0==a.s.length?(d={buffer:new Uint8Array(S.H),offset:0,K:0},a.s.push(d)):d=a.s[a.s.length-1];ma(d.offset<=S.H);var e=S.H-d.offset;if(e>=c)return d.buffer.set(b,d.offset),d.offset+=c,c;0<e&&(d.buffer.set(b.subarray(0,e),d.offset),d.offset+=
e,b=b.subarray(e,b.byteLength));d=b.byteLength/S.H|0;e=b.byteLength%S.H;for(var g=0;g<d;g++){var h={buffer:new Uint8Array(S.H),offset:S.H,K:0};a.s.push(h);h.buffer.set(b.subarray(0,S.H));b=b.subarray(S.H,b.byteLength)}0<e&&(h={buffer:new Uint8Array(S.H),offset:b.byteLength,K:0},a.s.push(h),h.buffer.set(b));return c},close:function(a){a.node.ka.s=null}},O:function(){S.O.current||(S.O.current=0);return"pipe["+S.O.current++ +"]"}},T={J:function(){f.websocket=f.websocket&&"object"===typeof f.websocket?
f.websocket:{};f.websocket.Ia={};f.websocket.on=function(a,b){"function"===typeof b&&(this.Ia[a]=b);return this};f.websocket.ua=function(a,b){"function"===typeof this.Ia[a]&&this.Ia[a].call(this,b)};return vb(null,"/",16895,0)},ob:function(a,b,c){b&=-526337;c&&ma(1==b==(6==c));a={family:a,type:b,protocol:c,S:null,error:null,ja:{},pending:[],ca:[],C:T.G};b=T.O();c=vb(T.root,b,49152,0);c.da=a;b=Rb({path:b,node:c,flags:Nb("r+"),seekable:!1,c:T.c});a.stream=b;return a},tb:function(a){return(a=Bb[a])&&
49152===(a.node.mode&49152)?a.node.da:null},c:{la:function(a){a=a.node.da;return a.C.la(a)},ha:function(a,b,c){a=a.node.da;return a.C.ha(a,b,c)},read:function(a,b,c,d){a=a.node.da;d=a.C.Pa(a,d);if(!d)return 0;b.set(d.buffer,c);return d.buffer.length},write:function(a,b,c,d){a=a.node.da;return a.C.Ra(a,b,c,d)},close:function(a){a=a.node.da;a.C.close(a)}},O:function(){T.O.current||(T.O.current=0);return"socket["+T.O.current++ +"]"},G:{Ya:function(a,b,c){if("object"===typeof b){var d=b;c=b=null}if(d)if(d.Ta)b=
d.Ta.cc,c=d.Ta.dc;else{c=/ws[s]?:\/\/([^:]+):(\d+)/.exec(d.url);if(!c)throw Error("WebSocket URL must be in the format ws(s)://address:port");b=c[1];c=parseInt(c[2],10)}else try{var e=f.websocket&&"object"===typeof f.websocket,g="ws:#".replace("#","//");e&&"string"===typeof f.websocket.url&&(g=f.websocket.url);if("ws://"===g||"wss://"===g){var h=b.split("/");g=g+h[0]+":"+c+"/"+h.slice(1).join("/")}h="binary";e&&"string"===typeof f.websocket.subprotocol&&(h=f.websocket.subprotocol);var l=void 0;"null"!==
h&&(l=h=h.replace(/^ +| +$/g,"").split(/ *, */));e&&null===f.websocket.subprotocol&&(l=void 0);d=new WebSocket(g,l);d.binaryType="arraybuffer"}catch(n){throw new G(23);}b={o:b,port:c,g:d,ta:[]};T.G.Ua(a,b);T.G.ub(a,b);2===a.type&&"undefined"!==typeof a.ea&&b.ta.push(new Uint8Array([255,255,255,255,112,111,114,116,(a.ea&65280)>>8,a.ea&255]));return b},va:function(a,b,c){return a.ja[b+":"+c]},Ua:function(a,b){a.ja[b.o+":"+b.port]=b},hb:function(a,b){delete a.ja[b.o+":"+b.port]},ub:function(a,b){var c=
!0;b.g.onopen=function(){f.websocket.ua("open",a.stream.A);try{for(var d=b.ta.shift();d;)b.g.send(d),d=b.ta.shift()}catch(e){b.g.close()}};b.g.onclose=function(){f.websocket.ua("close",a.stream.A)};b.g.onmessage=function(d){a:{d=d.data;if("string"===typeof d)d=(new TextEncoder).encode(d);else{ma(void 0!==d.byteLength);if(0==d.byteLength)break a;d=new Uint8Array(d)}var e=c;c=!1;e&&10===d.length&&255===d[0]&&255===d[1]&&255===d[2]&&255===d[3]&&112===d[4]&&111===d[5]&&114===d[6]&&116===d[7]?(d=d[8]<<
8|d[9],T.G.hb(a,b),b.port=d,T.G.Ua(a,b)):(a.ca.push({o:b.o,port:b.port,data:d}),f.websocket.ua("message",a.stream.A))}};b.g.onerror=function(){a.error=14;f.websocket.ua("error",[a.stream.A,a.error,"ECONNREFUSED: Connection refused"])}},la:function(a){if(1===a.type&&a.S)return a.pending.length?65:0;var b=0,c=1===a.type?T.G.va(a,a.I,a.N):null;if(a.ca.length||!c||c&&c.g.readyState===c.g.CLOSING||c&&c.g.readyState===c.g.CLOSED)b|=65;if(!c||c&&c.g.readyState===c.g.OPEN)b|=4;if(c&&c.g.readyState===c.g.CLOSING||
c&&c.g.readyState===c.g.CLOSED)b|=16;return b},ha:function(a,b,c){switch(b){case 21531:return b=0,a.ca.length&&(b=a.ca[0].data.length),B[c>>2]=b,0;default:return 28}},close:function(a){if(a.S){try{a.S.close()}catch(e){}a.S=null}for(var b=Object.keys(a.ja),c=0;c<b.length;c++){var d=a.ja[b[c]];try{d.g.close()}catch(e){}T.G.hb(a,d)}return 0},bind:function(a,b,c){if("undefined"!==typeof a.Qa||"undefined"!==typeof a.ea)throw new G(28);a.Qa=b;a.ea=c;if(2===a.type){a.S&&(a.S.close(),a.S=null);try{a.C.cb(a,
0)}catch(d){if(!(d instanceof G))throw d;if(138!==d.l)throw d;}}},connect:function(a,b,c){if(a.S)throw new G(138);if("undefined"!==typeof a.I&&"undefined"!==typeof a.N){var d=T.G.va(a,a.I,a.N);if(d){if(d.g.readyState===d.g.CONNECTING)throw new G(7);throw new G(30);}}b=T.G.Ya(a,b,c);a.I=b.o;a.N=b.port;throw new G(26);},cb:function(){throw new G(138);},accept:function(a){if(!a.S)throw new G(28);var b=a.pending.shift();b.stream.flags=a.stream.flags;return b},Wb:function(a,b){if(b){if(void 0===a.I||void 0===
a.N)throw new G(53);b=a.I;a=a.N}else b=a.Qa||0,a=a.ea||0;return{o:b,port:a}},Ra:function(a,b,c,d,e,g){if(2===a.type){if(void 0===e||void 0===g)e=a.I,g=a.N;if(void 0===e||void 0===g)throw new G(17);}else e=a.I,g=a.N;var h=T.G.va(a,e,g);if(1===a.type){if(!h||h.g.readyState===h.g.CLOSING||h.g.readyState===h.g.CLOSED)throw new G(53);if(h.g.readyState===h.g.CONNECTING)throw new G(6);}ArrayBuffer.isView(b)&&(c+=b.byteOffset,b=b.buffer);b=b.slice(c,c+d);if(2===a.type&&(!h||h.g.readyState!==h.g.OPEN))return h&&
h.g.readyState!==h.g.CLOSING&&h.g.readyState!==h.g.CLOSED||(h=T.G.Ya(a,e,g)),h.ta.push(b),d;try{return h.g.send(b),d}catch(l){throw new G(28);}},Pa:function(a,b){if(1===a.type&&a.S)throw new G(53);var c=a.ca.shift();if(!c){if(1===a.type){if(a=T.G.va(a,a.I,a.N)){if(a.g.readyState===a.g.CLOSING||a.g.readyState===a.g.CLOSED)return null;throw new G(6);}throw new G(53);}throw new G(6);}var d=c.data.byteLength||c.data.length,e=c.data.byteOffset||0,g=c.data.buffer||c.data;b=Math.min(b,d);var h={buffer:new Uint8Array(g,
e,b),o:c.o,port:c.port};1===a.type&&b<d&&(c.data=new Uint8Array(g,e+b,d-b),a.ca.unshift(c));return h}}};function nc(a){a=a.split(".");for(var b=0;4>b;b++){var c=Number(a[b]);if(isNaN(c))return null;a[b]=c}return(a[0]|a[1]<<8|a[2]<<16|a[3]<<24)>>>0}
function oc(a){var b,c,d=[];if(!/^((?=.*::)(?!.*::.+::)(::)?([\dA-F]{1,4}:(:|\b)|){5}|([\dA-F]{1,4}:){6})((([\dA-F]{1,4}((?!\3)::|:\b|$))|(?!\2\3)){2}|(((2[0-4]|1\d|[1-9])?\d|25[0-5])\.?\b){4})$/i.test(a))return null;if("::"===a)return[0,0,0,0,0,0,0,0];a=0===a.indexOf("::")?a.replace("::","Z:"):a.replace("::",":Z:");0<a.indexOf(".")?(a=a.replace(/[.]/g,":"),a=a.split(":"),a[a.length-4]=parseInt(a[a.length-4])+256*parseInt(a[a.length-3]),a[a.length-3]=parseInt(a[a.length-2])+256*parseInt(a[a.length-
1]),a=a.slice(0,a.length-2)):a=a.split(":");for(b=c=0;b<a.length;b++)if("string"===typeof a[b])if("Z"===a[b]){for(c=0;c<8-a.length+1;c++)d[b+c]=0;--c}else d[b+c]=pc(parseInt(a[b],16));else d[b+c]=a[b];return[d[1]<<16|d[0],d[3]<<16|d[2],d[5]<<16|d[4],d[7]<<16|d[6]]}var qc=1,rc={},sc={};function tc(a){var b=nc(a);if(null!==b)return a;b=oc(a);if(null!==b)return a;rc[a]?b=rc[a]:(b=qc++,ma(65535>b,"exceeded max address mappings of 65535"),b="172.29."+(b&255)+"."+(b&65280),sc[b]=a,rc[a]=b);return b}
function uc(a){return sc[a]?sc[a]:null}function vc(a){return(a&255)+"."+(a>>8&255)+"."+(a>>16&255)+"."+(a>>24&255)}
function wc(a,b){var c=A[a>>1],d=xc(ta[a+2>>1]);switch(c){case 2:if(16!==b)return{l:28};var e=B[a+4>>2];e=vc(e);break;case 10:if(28!==b)return{l:28};e=[B[a+8>>2],B[a+12>>2],B[a+16>>2],B[a+20>>2]];a:{a="";var g,h=b=0,l=0,n=0;e=[e[0]&65535,e[0]>>16,e[1]&65535,e[1]>>16,e[2]&65535,e[2]>>16,e[3]&65535,e[3]>>16];var m=!0;for(g=0;5>g;g++)if(0!==e[g]){m=!1;break}if(m){g=vc(e[6]|e[7]<<16);if(-1===e[5]){e="::ffff:"+g;break a}if(0===e[5]){"0.0.0.0"===g&&(g="");"0.0.0.1"===g&&(g="1");e="::"+g;break a}}for(g=
0;8>g;g++)0===e[g]&&(1<g-h&&(n=0),h=g,n++),n>b&&(b=n,l=g-b+1);for(g=0;8>g;g++)1<b&&0===e[g]&&g>=l&&g<l+b?g===l&&(a+=":",0===l&&(a+=":")):(a+=Number(xc(e[g]&65535)).toString(16),a+=7>g?":":"");e=a}break;default:return{l:5}}return{family:c,o:e,port:d}}function yc(a,b,c,d){switch(b){case 2:c=nc(c);A[a>>1]=b;B[a+4>>2]=c;A[a+2>>1]=pc(d);break;case 10:c=oc(c),B[a>>2]=b,B[a+8>>2]=c[0],B[a+12>>2]=c[1],B[a+16>>2]=c[2],B[a+20>>2]=c[3],A[a+2>>1]=pc(d),B[a+4>>2]=0,B[a+24>>2]=0}}
function zc(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Ac=void 0;function U(a){for(var b="";z[a];)b+=Ac[z[a++]];return b}var Bc={},Cc={},Dc={};function Ec(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}
function Fc(a,b){a=Ec(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}function Gc(a){var b=Error,c=Fc(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}
var Hc=void 0;function V(a){throw new Hc(a);}var Ic=void 0;function Jc(a){throw new Ic(a);}function Kc(a,b,c){function d(l){l=c(l);l.length!==a.length&&Jc("Mismatched type converter count");for(var n=0;n<a.length;++n)Lc(a[n],l[n])}a.forEach(function(l){Dc[l]=b});var e=Array(b.length),g=[],h=0;b.forEach(function(l,n){Cc.hasOwnProperty(l)?e[n]=Cc[l]:(g.push(l),Bc.hasOwnProperty(l)||(Bc[l]=[]),Bc[l].push(function(){e[n]=Cc[l];++h;h===g.length&&d(e)}))});0===g.length&&d(e)}
function Lc(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||V('type "'+d+'" must have a positive integer typeid pointer');if(Cc.hasOwnProperty(a)){if(c.vb)return;V("Cannot register type '"+d+"' twice")}Cc[a]=b;delete Dc[a];Bc.hasOwnProperty(a)&&(b=Bc[a],delete Bc[a],b.forEach(function(e){e()}))}function Mc(a){return{count:a.count,$:a.$,ma:a.ma,i:a.i,u:a.u,F:a.F,L:a.L}}
function Nc(a){V(a.b.u.j.name+" instance already deleted")}var Oc=!1;function Pc(){}function Qc(a){--a.count.value;0===a.count.value&&(a.F?a.L.Y(a.F):a.u.j.Y(a.i))}function Rc(a){if("undefined"===typeof FinalizationGroup)return Rc=function(b){return b},a;Oc=new FinalizationGroup(function(b){for(var c=b.next();!c.done;c=b.next())c=c.value,c.i?Qc(c):console.warn("object already deleted: "+c.i)});Rc=function(b){Oc.register(b,b.b,b.b);return b};Pc=function(b){Oc.unregister(b.b)};return Rc(a)}
var Sc=void 0,Tc=[];function Uc(){for(;Tc.length;){var a=Tc.pop();a.b.$=!1;a["delete"]()}}function Vc(){}var Wc={};function Xc(a,b,c){if(void 0===a[b].R){var d=a[b];a[b]=function(){a[b].R.hasOwnProperty(arguments.length)||V("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].R+")!");return a[b].R[arguments.length].apply(this,arguments)};a[b].R=[];a[b].R[d.sa]=d}}
function Yc(a,b){f.hasOwnProperty(a)?(V("Cannot register public name '"+a+"' twice"),Xc(f,a,a),f.hasOwnProperty(void 0)&&V("Cannot register multiple overloads of a function with the same number of arguments (undefined)!"),f[a].R[void 0]=b):f[a]=b}function Zc(a,b,c,d,e,g,h,l){this.name=a;this.constructor=b;this.aa=c;this.Y=d;this.M=e;this.rb=g;this.qa=h;this.pb=l;this.Cb=[]}
function $c(a,b,c){for(;b!==c;)b.qa||V("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.qa(a),b=b.M;return a}function ad(a,b){if(null===b)return this.Ma&&V("null is not a valid "+this.name),0;b.b||V('Cannot pass "'+bd(b)+'" as a '+this.name);b.b.i||V("Cannot pass deleted object as a pointer of type "+this.name);return $c(b.b.i,b.b.u.j,this.j)}
function cd(a,b){if(null===b){this.Ma&&V("null is not a valid "+this.name);if(this.ya){var c=this.Db();null!==a&&a.push(this.Y,c);return c}return 0}b.b||V('Cannot pass "'+bd(b)+'" as a '+this.name);b.b.i||V("Cannot pass deleted object as a pointer of type "+this.name);!this.wa&&b.b.u.wa&&V("Cannot convert argument of type "+(b.b.L?b.b.L.name:b.b.u.name)+" to parameter type "+this.name);c=$c(b.b.i,b.b.u.j,this.j);if(this.ya)switch(void 0===b.b.F&&V("Passing raw pointer to smart pointer is illegal"),
this.Ib){case 0:b.b.L===this?c=b.b.F:V("Cannot convert argument of type "+(b.b.L?b.b.L.name:b.b.u.name)+" to parameter type "+this.name);break;case 1:c=b.b.F;break;case 2:if(b.b.L===this)c=b.b.F;else{var d=b.clone();c=this.Eb(c,dd(function(){d["delete"]()}));null!==a&&a.push(this.Y,c)}break;default:V("Unsupporting sharing policy")}return c}
function gd(a,b){if(null===b)return this.Ma&&V("null is not a valid "+this.name),0;b.b||V('Cannot pass "'+bd(b)+'" as a '+this.name);b.b.i||V("Cannot pass deleted object as a pointer of type "+this.name);b.b.u.wa&&V("Cannot convert argument of type "+b.b.u.name+" to parameter type "+this.name);return $c(b.b.i,b.b.u.j,this.j)}function hd(a){return this.fromWireType(Aa[a>>2])}function id(a,b,c){if(b===c)return a;if(void 0===c.M)return null;a=id(a,b,c.M);return null===a?null:c.pb(a)}var jd={};
function kd(a,b){for(void 0===b&&V("ptr should not be undefined");a.M;)b=a.qa(b),a=a.M;return jd[b]}function ld(a,b){b.u&&b.i||Jc("makeClassHandle requires ptr and ptrType");!!b.L!==!!b.F&&Jc("Both smartPtrType and smartPtr must be specified");b.count={value:1};return Rc(Object.create(a,{b:{value:b}}))}
function md(a,b,c,d){this.name=a;this.j=b;this.Ma=c;this.wa=d;this.ya=!1;this.Y=this.Eb=this.Db=this.fb=this.Ib=this.Ab=void 0;void 0!==b.M?this.toWireType=cd:(this.toWireType=d?ad:gd,this.U=null)}function nd(a,b){f.hasOwnProperty(a)||Jc("Replacing nonexistant public symbol");f[a]=b;f[a].sa=void 0}
function od(a,b){a=U(a);var c=f["dynCall_"+a];for(var d=[],e=1;e<a.length;++e)d.push("a"+e);e="return function dynCall_"+(a+"_"+b)+"("+d.join(", ")+") {\n";e+="    return dynCall(rawFunction"+(d.length?", ":"")+d.join(", ")+");\n";c=(new Function("dynCall","rawFunction",e+"};\n"))(c,b);"function"!==typeof c&&V("unknown function pointer with signature "+a+": "+b);return c}var pd=void 0;function qd(a){a=rd(a);var b=U(a);F(a);return b}
function sd(a,b){function c(g){e[g]||Cc[g]||(Dc[g]?Dc[g].forEach(c):(d.push(g),e[g]=!0))}var d=[],e={};b.forEach(c);throw new pd(a+": "+d.map(qd).join([", "]));}function td(a,b){for(var c=[],d=0;d<a;d++)c.push(B[(b>>2)+d]);return c}function ud(a){for(;a.length;){var b=a.pop();a.pop()(b)}}
function vd(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=Fc(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}var wd=[],W=[{},{value:void 0},{value:null},{value:!0},{value:!1}];
function dd(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=wd.length?wd.pop():W.length;W[b]={Z:1,value:a};return b}}function bd(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}function xd(a,b){switch(b){case 2:return function(c){return this.fromWireType(Ba[c>>2])};case 3:return function(c){return this.fromWireType(Ca[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function yd(a,b,c){switch(b){case 0:return c?function(d){return C[d]}:function(d){return z[d]};case 1:return c?function(d){return A[d>>1]}:function(d){return ta[d>>1]};case 2:return c?function(d){return B[d>>2]}:function(d){return Aa[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var zd;zd=function(){return performance.now()};var Ad={};
function Bd(){if(!Cd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in Ad)a[b]=Ad[b];var c=[];for(b in a)c.push(b+"="+a[b]);Cd=c}return Cd}var Cd;function Dd(a){return 0===a%4&&(0!==a%100||0===a%400)}function Ed(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}
var Fd=[31,29,31,30,31,30,31,31,30,31,30,31],Gd=[31,28,31,30,31,30,31,31,30,31,30,31];function Hd(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Dd(a.getFullYear())?Fd:Gd)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function Id(a,b,c,d){function e(k,r,x){for(k="number"===typeof k?k.toString():k||"";k.length<r;)k=x[0]+k;return k}function g(k,r){return e(k,r,"0")}function h(k,r){function x(H){return 0>H?-1:0<H?1:0}var v;0===(v=x(k.getFullYear()-r.getFullYear()))&&0===(v=x(k.getMonth()-r.getMonth()))&&(v=x(k.getDate()-r.getDate()));return v}function l(k){switch(k.getDay()){case 0:return new Date(k.getFullYear()-1,11,29);case 1:return k;case 2:return new Date(k.getFullYear(),0,3);case 3:return new Date(k.getFullYear(),
0,2);case 4:return new Date(k.getFullYear(),0,1);case 5:return new Date(k.getFullYear()-1,11,31);case 6:return new Date(k.getFullYear()-1,11,30)}}function n(k){k=Hd(new Date(k.D+1900,0,1),k.Ha);var r=new Date(k.getFullYear()+1,0,4),x=l(new Date(k.getFullYear(),0,4));r=l(r);return 0>=h(x,k)?0>=h(r,k)?k.getFullYear()+1:k.getFullYear():k.getFullYear()-1}var m=B[d+40>>2];d={Lb:B[d>>2],Kb:B[d+4>>2],Fa:B[d+8>>2],pa:B[d+12>>2],fa:B[d+16>>2],D:B[d+20>>2],Ga:B[d+24>>2],Ha:B[d+28>>2],ec:B[d+32>>2],Jb:B[d+36>>
2],Mb:m?m?oa(z,m,void 0):"":""};c=c?oa(z,c,void 0):"";m={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var t in m)c=c.replace(new RegExp(t,"g"),m[t]);var w="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
u="January February March April May June July August September October November December".split(" ");m={"%a":function(k){return w[k.Ga].substring(0,3)},"%A":function(k){return w[k.Ga]},"%b":function(k){return u[k.fa].substring(0,3)},"%B":function(k){return u[k.fa]},"%C":function(k){return g((k.D+1900)/100|0,2)},"%d":function(k){return g(k.pa,2)},"%e":function(k){return e(k.pa,2," ")},"%g":function(k){return n(k).toString().substring(2)},"%G":function(k){return n(k)},"%H":function(k){return g(k.Fa,
2)},"%I":function(k){k=k.Fa;0==k?k=12:12<k&&(k-=12);return g(k,2)},"%j":function(k){return g(k.pa+Ed(Dd(k.D+1900)?Fd:Gd,k.fa-1),3)},"%m":function(k){return g(k.fa+1,2)},"%M":function(k){return g(k.Kb,2)},"%n":function(){return"\n"},"%p":function(k){return 0<=k.Fa&&12>k.Fa?"AM":"PM"},"%S":function(k){return g(k.Lb,2)},"%t":function(){return"\t"},"%u":function(k){return k.Ga||7},"%U":function(k){var r=new Date(k.D+1900,0,1),x=0===r.getDay()?r:Hd(r,7-r.getDay());k=new Date(k.D+1900,k.fa,k.pa);return 0>
h(x,k)?g(Math.ceil((31-x.getDate()+(Ed(Dd(k.getFullYear())?Fd:Gd,k.getMonth()-1)-31)+k.getDate())/7),2):0===h(x,r)?"01":"00"},"%V":function(k){var r=new Date(k.D+1901,0,4),x=l(new Date(k.D+1900,0,4));r=l(r);var v=Hd(new Date(k.D+1900,0,1),k.Ha);return 0>h(v,x)?"53":0>=h(r,v)?"01":g(Math.ceil((x.getFullYear()<k.D+1900?k.Ha+32-x.getDate():k.Ha+1-x.getDate())/7),2)},"%w":function(k){return k.Ga},"%W":function(k){var r=new Date(k.D,0,1),x=1===r.getDay()?r:Hd(r,0===r.getDay()?1:7-r.getDay()+1);k=new Date(k.D+
1900,k.fa,k.pa);return 0>h(x,k)?g(Math.ceil((31-x.getDate()+(Ed(Dd(k.getFullYear())?Fd:Gd,k.getMonth()-1)-31)+k.getDate())/7),2):0===h(x,r)?"01":"00"},"%y":function(k){return(k.D+1900).toString().substring(2)},"%Y":function(k){return k.D+1900},"%z":function(k){k=k.Jb;var r=0<=k;k=Math.abs(k)/60;return(r?"+":"-")+String("0000"+(k/60*100+k%60)).slice(-4)},"%Z":function(k){return k.Mb},"%%":function(){return"%"}};for(t in m)0<=c.indexOf(t)&&(c=c.replace(new RegExp(t,"g"),m[t](d)));t=qb(c,!1);if(t.length>
b)return 0;C.set(t,a);return t.length-1}function Lb(a,b,c,d){a||(a=this);this.parent=a;this.J=a.J;this.Ba=null;this.id=Cb++;this.name=b;this.mode=c;this.h={};this.c={};this.Da=d}Object.defineProperties(Lb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});fc();Db=Array(4096);Wb(K,"/");Yb("/tmp");Yb("/home");Yb("/home/web_user");
(function(){Yb("/dev");ob(259,{read:function(){return 0},write:function(c,d,e,g){return g}});Zb("/dev/null",259);nb(1280,sb);nb(1536,tb);Zb("/dev/tty",1280);Zb("/dev/tty1",1536);if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}b||(b=function(){y("random_device")});ic("random",b);ic("urandom",b);Yb("/dev/shm");Yb("/dev/shm/tmp")})();Yb("/proc");Yb("/proc/self");Yb("/proc/self/fd");
Wb({J:function(){var a=vb("/proc/self","fd",16895,73);a.h={ia:function(b,c){var d=Bb[+c];if(!d)throw new G(8);b={parent:null,J:{eb:"fake"},h:{na:function(){return d.path}}};return b.parent=b}};return a}},"/proc/self/fd");for(var Jd=Array(256),Kd=0;256>Kd;++Kd)Jd[Kd]=String.fromCharCode(Kd);Ac=Jd;Hc=f.BindingError=Gc("BindingError");Ic=f.InternalError=Gc("InternalError");
Vc.prototype.isAliasOf=function(a){if(!(this instanceof Vc&&a instanceof Vc))return!1;var b=this.b.u.j,c=this.b.i,d=a.b.u.j;for(a=a.b.i;b.M;)c=b.qa(c),b=b.M;for(;d.M;)a=d.qa(a),d=d.M;return b===d&&c===a};Vc.prototype.clone=function(){this.b.i||Nc(this);if(this.b.ma)return this.b.count.value+=1,this;var a=Rc(Object.create(Object.getPrototypeOf(this),{b:{value:Mc(this.b)}}));a.b.count.value+=1;a.b.$=!1;return a};
Vc.prototype["delete"]=function(){this.b.i||Nc(this);this.b.$&&!this.b.ma&&V("Object already scheduled for deletion");Pc(this);Qc(this.b);this.b.ma||(this.b.F=void 0,this.b.i=void 0)};Vc.prototype.isDeleted=function(){return!this.b.i};Vc.prototype.deleteLater=function(){this.b.i||Nc(this);this.b.$&&!this.b.ma&&V("Object already scheduled for deletion");Tc.push(this);1===Tc.length&&Sc&&Sc(Uc);this.b.$=!0;return this};md.prototype.sb=function(a){this.fb&&(a=this.fb(a));return a};
md.prototype.ga=function(a){this.Y&&this.Y(a)};md.prototype.argPackAdvance=8;md.prototype.readValueFromPointer=hd;md.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
md.prototype.fromWireType=function(a){function b(){return this.ya?ld(this.j.aa,{u:this.Ab,i:c,L:this,F:a}):ld(this.j.aa,{u:this,i:a})}var c=this.sb(a);if(!c)return this.ga(a),null;var d=kd(this.j,c);if(void 0!==d){if(0===d.b.count.value)return d.b.i=c,d.b.F=a,d.clone();d=d.clone();this.ga(a);return d}d=this.j.rb(c);d=Wc[d];if(!d)return b.call(this);d=this.wa?d.mb:d.pointerType;var e=id(c,this.j,d.j);return null===e?b.call(this):this.ya?ld(d.j.aa,{u:d,i:e,L:this,F:a}):ld(d.j.aa,{u:d,i:e})};
f.getInheritedInstanceCount=function(){return Object.keys(jd).length};f.getLiveInheritedInstances=function(){var a=[],b;for(b in jd)jd.hasOwnProperty(b)&&a.push(jd[b]);return a};f.flushPendingDeletes=Uc;f.setDelayFunction=function(a){Sc=a;Tc.length&&Sc&&Sc(Uc)};pd=f.UnboundTypeError=Gc("UnboundTypeError");f.count_emval_handles=function(){for(var a=0,b=5;b<W.length;++b)void 0!==W[b]&&++a;return a};f.get_first_emval=function(){for(var a=5;a<W.length;++a)if(void 0!==W[a])return W[a];return null};
function qb(a,b){var c=Array(qa(a)+1);a=pa(a,c,0,c.length);b&&(c.length=a);return c}
var ye={__cxa_allocate_exception:function(a){return yb(a)},__cxa_atexit:function(){},__cxa_begin_catch:function(a){var b=D[a];b&&!b.Wa&&(b.Wa=!0,Ld.Sa--);b&&(b.oa=!1);ab.push(a);(b=bb(a))&&D[b].Z++;return a},__cxa_current_primary_exception:function(){var a=ab[ab.length-1]||0;if(a){var b=bb(a);b&&D[b].Z++}return a},__cxa_decrement_exception_refcount:function(a){cb(bb(a))},__cxa_end_catch:function(){X(0);var a=ab.pop();a&&(cb(bb(a)),db=0)},__cxa_find_matching_catch_2:function(){var a=db;if(!a)return q=
0;var b=D[a],c=b.type;if(!c)return q=0,a|0;var d=Array.prototype.slice.call(arguments);Md(c);B[27420]=a;a=109680;for(var e=0;e<d.length;e++)if(d[e]&&Nd(d[e],c,a))return a=B[a>>2],b.ra.push(a),q=d[e],a|0;a=B[a>>2];q=c;return a|0},__cxa_find_matching_catch_3:function(){var a=db;if(!a)return q=0;var b=D[a],c=b.type;if(!c)return q=0,a|0;var d=Array.prototype.slice.call(arguments);Md(c);B[27420]=a;a=109680;for(var e=0;e<d.length;e++)if(d[e]&&Nd(d[e],c,a))return a=B[a>>2],b.ra.push(a),q=d[e],a|0;a=B[a>>
2];q=c;return a|0},__cxa_find_matching_catch_6:function(){var a=db;if(!a)return q=0;var b=D[a],c=b.type;if(!c)return q=0,a|0;var d=Array.prototype.slice.call(arguments);Md(c);B[27420]=a;a=109680;for(var e=0;e<d.length;e++)if(d[e]&&Nd(d[e],c,a))return a=B[a>>2],b.ra.push(a),q=d[e],a|0;a=B[a>>2];q=c;return a|0},__cxa_free_exception:function(a){return F(a)},__cxa_increment_exception_refcount:function(a){(a=bb(a))&&D[a].Z++},__cxa_rethrow:eb,__cxa_rethrow_primary_exception:function(a){a&&(a=bb(a),ab.push(a),
D[a].oa=!0,eb())},__cxa_throw:function(a,b,c){D[a]={i:a,ra:[a],type:b,ga:c,Z:0,Wa:!1,oa:!1};db=a;"uncaught_exception"in Ld?Ld.Sa++:Ld.Sa=1;throw a;},__cxa_uncaught_exceptions:function(){return Ld.Sa},__map_file:function(){fb(63);return-1},__resumeException:function(a){db||(db=a);throw a;},__sys__newselect:function(a,b,c,d){try{for(var e=0,g=b?B[b>>2]:0,h=b?B[b+4>>2]:0,l=c?B[c>>2]:0,n=c?B[c+4>>2]:0,m=d?B[d>>2]:0,t=d?B[d+4>>2]:0,w=0,u=0,k=0,r=0,x=0,v=0,H=(b?B[b>>2]:0)|(c?B[c>>2]:0)|(d?B[d>>2]:0),I=
(b?B[b+4>>2]:0)|(c?B[c+4>>2]:0)|(d?B[d+4>>2]:0),J=0;J<a;J++){var E=1<<J%32;if(32>J?H&E:I&E){var P=Bb[J];if(!P)throw new G(8);var M=5;P.c.la&&(M=P.c.la(P));M&1&&(32>J?g&E:h&E)&&(32>J?w|=E:u|=E,e++);M&4&&(32>J?l&E:n&E)&&(32>J?k|=E:r|=E,e++);M&2&&(32>J?m&E:t&E)&&(32>J?x|=E:v|=E,e++)}}b&&(B[b>>2]=w,B[b+4>>2]=u);c&&(B[c>>2]=k,B[c+4>>2]=r);d&&(B[d>>2]=x,B[d+4>>2]=v);return e}catch(Q){return"undefined"!==typeof L&&Q instanceof G||y(Q),-Q.l}},__sys_fcntl64:function(a,b,c){lc=c;try{var d=mc(a);switch(b){case 0:var e=
O();return 0>e?-28:ac(d.path,d.flags,0,e).A;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=O(),d.flags|=e,0;case 12:return e=O(),A[e+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return fb(28),-1;default:return-28}}catch(g){return"undefined"!==typeof L&&g instanceof G||y(g),-g.l}},__sys_ioctl:function(a,b,c){lc=c;try{var d=mc(a);switch(b){case 21509:case 21505:return d.v?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.v?0:-59;case 21519:if(!d.v)return-59;
var e=O();return B[e>>2]=0;case 21520:return d.v?-28:-59;case 21531:a=e=O();if(!d.c.ha)throw new G(59);return d.c.ha(d,b,a);case 21523:return d.v?0:-59;case 21524:return d.v?0:-59;default:y("bad ioctl syscall "+b)}}catch(g){return"undefined"!==typeof L&&g instanceof G||y(g),-g.l}},__sys_mmap2:function(a,b,c,d,e,g){try{a:{g<<=12;var h=!1;if(0!==(d&16)&&0!==a%16384)var l=-28;else{if(0!==(d&32)){var n=Od(16384,b);if(!n){l=-48;break a}Pd(n,0,b);h=!0}else{var m=Bb[e];if(!m){l=-8;break a}var t=g;if(0!==
(c&2)&&0===(d&2)&&2!==(m.flags&2097155))throw new G(2);if(1===(m.flags&2097155))throw new G(2);if(!m.c.Aa)throw new G(43);var w=m.c.Aa(m,a,b,t,c,d);n=w.i;h=w.Ja}kc[n]={xb:n,wb:b,Ja:h,A:e,Bb:c,flags:d,offset:g};l=n}}return l}catch(u){return"undefined"!==typeof L&&u instanceof G||y(u),-u.l}},__sys_munmap:function(a,b){try{if(-1===(a|0)||0===b)var c=-28;else{var d=kc[a];if(d&&b===d.wb){var e=Bb[d.A];d.Bb&2&&e&&e.c.Ca&&e.c.Ca(e,z.slice(a,a+b),d.offset,b,d.flags);kc[a]=null;d.Ja&&F(d.xb)}c=0}return c}catch(g){return"undefined"!==
typeof L&&g instanceof G||y(g),-g.l}},__sys_pause:function(){return-27},__sys_pipe:function(a){try{if(0==a)throw new G(21);var b=S.nb();B[a>>2]=b.Fb;B[a+4>>2]=b.Ob;return 0}catch(c){return"undefined"!==typeof L&&c instanceof G||y(c),-c.l}},__sys_read:function(a,b,c){try{var d=mc(a);return dc(d,b,c)}catch(e){return"undefined"!==typeof L&&e instanceof G||y(e),-e.l}},__sys_socketcall:function(a,b){try{lc=b;b=function(){var R=T.tb(O());if(!R)throw new G(8);return R};var c=function(R){var ed=O(),Be=O();
if(R&&0===ed)return null;R=wc(ed,Be);if(R.l)throw new G(R.l);R.o=uc(R.o)||R.o;return R};switch(a){case 1:var d=O(),e=O(),g=O(),h=T.ob(d,e,g);return h.stream.A;case 2:h=b();var l=c();h.C.bind(h,l.o,l.port);return 0;case 3:return h=b(),l=c(),h.C.connect(h,l.o,l.port),0;case 4:h=b();var n=O();h.C.cb(h,n);return 0;case 5:h=b();var m=O();O();var t=h.C.accept(h);m&&yc(m,t.family,tc(t.I),t.N);return t.stream.A;case 6:return h=b(),m=O(),O(),yc(m,h.family,tc(h.Qa||"0.0.0.0"),h.ea),0;case 7:h=b();m=O();O();
if(!h.I)return-53;yc(m,h.family,tc(h.I),h.N);return 0;case 11:h=b();var w=O(),u=O();O();var k=c(!0);return k?h.C.Ra(h,C,w,u,k.o,k.port):ec(h.stream,w,u);case 12:h=b();var r=O(),x=O();O();m=O();O();var v=h.C.Pa(h,x);if(!v)return 0;m&&yc(m,h.family,tc(v.o),v.port);z.set(v.buffer,r);return v.buffer.byteLength;case 14:return-50;case 15:h=b();var H=O(),I=O(),J=O(),E=O();return 1===H&&4===I?(B[J>>2]=h.error,B[E>>2]=4,h.error=null,0):-50;case 16:h=b();w=O();O();var P=B[w+8>>2],M=B[w+12>>2],Q=B[w>>2],rb=
B[w+4>>2];if(Q){l=wc(Q,rb);if(l.l)return-l.l;var Ce=l.port;m=uc(l.o)||l.o}for(var Da=0,N=0;N<M;N++)Da+=B[P+(8*N+4)>>2];var fd=new Uint8Array(Da);for(N=u=0;N<M;N++){var Tb=B[P+8*N>>2],Ub=B[P+(8*N+4)>>2];for(r=0;r<Ub;r++)fd[u++]=C[Tb+r>>0]}return h.C.Ra(h,fd,0,Da,m,Ce);case 17:h=b();w=O();O();P=B[w+8>>2];M=B[w+12>>2];for(N=Da=0;N<M;N++)Da+=B[P+(8*N+4)>>2];v=h.C.Pa(h,Da);if(!v)return 0;(Q=B[w>>2])&&yc(Q,h.family,tc(v.o),v.port);h=0;var Vb=v.buffer.byteLength;for(N=0;0<Vb&&N<M;N++)if(Tb=B[P+8*N>>2],Ub=
B[P+(8*N+4)>>2])u=Math.min(Ub,Vb),r=v.buffer.subarray(h,h+u),z.set(r,Tb+h),h+=u,Vb-=u;return h;default:return-52}}catch(R){return"undefined"!==typeof L&&R instanceof G||y(R),-R.l}},_embind_register_bool:function(a,b,c,d,e){var g=zc(c);b=U(b);Lc(a,{name:b,fromWireType:function(h){return!!h},toWireType:function(h,l){return l?d:e},argPackAdvance:8,readValueFromPointer:function(h){if(1===c)var l=C;else if(2===c)l=A;else if(4===c)l=B;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(l[h>>
g])},U:null})},_embind_register_class:function(a,b,c,d,e,g,h,l,n,m,t,w,u){t=U(t);g=od(e,g);l&&(l=od(h,l));m&&(m=od(n,m));u=od(w,u);var k=Ec(t);Yc(k,function(){sd("Cannot construct "+t+" due to unbound types",[d])});Kc([a,b,c],d?[d]:[],function(r){r=r[0];if(d){var x=r.j;var v=x.aa}else v=Vc.prototype;r=Fc(k,function(){if(Object.getPrototypeOf(this)!==H)throw new Hc("Use 'new' to construct "+t);if(void 0===I.W)throw new Hc(t+" has no accessible constructor");var E=I.W[arguments.length];if(void 0===
E)throw new Hc("Tried to invoke ctor of "+t+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(I.W).toString()+") parameters instead!");return E.apply(this,arguments)});var H=Object.create(v,{constructor:{value:r}});r.prototype=H;var I=new Zc(t,r,H,u,x,g,l,m);x=new md(t,I,!0,!1);v=new md(t+"*",I,!1,!1);var J=new md(t+" const*",I,!1,!0);Wc[a]={pointerType:v,mb:J};nd(k,r);return[x,v,J]})},_embind_register_class_constructor:function(a,b,c,d,e,g){ma(0<b);var h=td(b,c);
e=od(d,e);var l=[g],n=[];Kc([],[a],function(m){m=m[0];var t="constructor "+m.name;void 0===m.j.W&&(m.j.W=[]);if(void 0!==m.j.W[b-1])throw new Hc("Cannot register multiple constructors with identical number of parameters ("+(b-1)+") for class '"+m.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");m.j.W[b-1]=function(){sd("Cannot construct "+m.name+" due to unbound types",h)};Kc([],h,function(w){m.j.W[b-1]=function(){arguments.length!==b-1&&
V(t+" called with "+arguments.length+" arguments, expected "+(b-1));n.length=0;l.length=b;for(var u=1;u<b;++u)l[u]=w[u].toWireType(n,arguments[u-1]);u=e.apply(null,l);ud(n);return w[0].fromWireType(u)};return[]});return[]})},_embind_register_class_function:function(a,b,c,d,e,g,h,l){var n=td(c,d);b=U(b);g=od(e,g);Kc([],[a],function(m){function t(){sd("Cannot call "+w+" due to unbound types",n)}m=m[0];var w=m.name+"."+b;l&&m.j.Cb.push(b);var u=m.j.aa,k=u[b];void 0===k||void 0===k.R&&k.className!==m.name&&
k.sa===c-2?(t.sa=c-2,t.className=m.name,u[b]=t):(Xc(u,b,w),u[b].R[c-2]=t);Kc([],n,function(r){var x=w,v=m,H=g,I=r.length;2>I&&V("argTypes array size mismatch! Must at least get return value and 'this' types!");var J=null!==r[1]&&null!==v,E=!1;for(v=1;v<r.length;++v)if(null!==r[v]&&void 0===r[v].U){E=!0;break}var P="void"!==r[0].name,M="",Q="";for(v=0;v<I-2;++v)M+=(0!==v?", ":"")+"arg"+v,Q+=(0!==v?", ":"")+"arg"+v+"Wired";x="return function "+Ec(x)+"("+M+") {\nif (arguments.length !== "+(I-2)+") {\nthrowBindingError('function "+
x+" called with ' + arguments.length + ' arguments, expected "+(I-2)+" args!');\n}\n";E&&(x+="var destructors = [];\n");var rb=E?"destructors":"null";M="throwBindingError invoker fn runDestructors retType classParam".split(" ");H=[V,H,h,ud,r[0],r[1]];J&&(x+="var thisWired = classParam.toWireType("+rb+", this);\n");for(v=0;v<I-2;++v)x+="var arg"+v+"Wired = argType"+v+".toWireType("+rb+", arg"+v+"); // "+r[v+2].name+"\n",M.push("argType"+v),H.push(r[v+2]);J&&(Q="thisWired"+(0<Q.length?", ":"")+Q);x+=
(P?"var rv = ":"")+"invoker(fn"+(0<Q.length?", ":"")+Q+");\n";if(E)x+="runDestructors(destructors);\n";else for(v=J?1:2;v<r.length;++v)I=1===v?"thisWired":"arg"+(v-2)+"Wired",null!==r[v].U&&(x+=I+"_dtor("+I+"); // "+r[v].name+"\n",M.push(I+"_dtor"),H.push(r[v].U));P&&(x+="var ret = retType.fromWireType(rv);\nreturn ret;\n");M.push(x+"}\n");r=vd(M).apply(null,H);void 0===u[b].R?(r.sa=c-2,u[b]=r):u[b].R[c-2]=r;return[]});return[]})},_embind_register_emval:function(a,b){b=U(b);Lc(a,{name:b,fromWireType:function(c){var d=
W[c].value;4<c&&0===--W[c].Z&&(W[c]=void 0,wd.push(c));return d},toWireType:function(c,d){return dd(d)},argPackAdvance:8,readValueFromPointer:hd,U:null})},_embind_register_float:function(a,b,c){c=zc(c);b=U(b);Lc(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,e){if("number"!==typeof e&&"boolean"!==typeof e)throw new TypeError('Cannot convert "'+bd(e)+'" to '+this.name);return e},argPackAdvance:8,readValueFromPointer:xd(b,c),U:null})},_embind_register_integer:function(a,b,c,d,e){function g(m){return m}
b=U(b);-1===e&&(e=4294967295);var h=zc(c);if(0===d){var l=32-8*c;g=function(m){return m<<l>>>l}}var n=-1!=b.indexOf("unsigned");Lc(a,{name:b,fromWireType:g,toWireType:function(m,t){if("number"!==typeof t&&"boolean"!==typeof t)throw new TypeError('Cannot convert "'+bd(t)+'" to '+this.name);if(t<d||t>e)throw new TypeError('Passing a number "'+bd(t)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+e+"]!");return n?t>>>0:t|0},argPackAdvance:8,readValueFromPointer:yd(b,
h,0!==d),U:null})},_embind_register_memory_view:function(a,b,c){function d(g){g>>=2;var h=Aa;return new e(za,h[g+1],h[g])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=U(c);Lc(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{vb:!0})},_embind_register_std_string:function(a,b){b=U(b);var c="std::string"===b;Lc(a,{name:b,fromWireType:function(d){var e=Aa[d>>2];if(c)for(var g=d+4,h=0;h<=e;++h){var l=d+4+h;if(h==e||0==z[l]){g=
g?oa(z,g,l-g):"";if(void 0===n)var n=g;else n+=String.fromCharCode(0),n+=g;g=l+1}}else{n=Array(e);for(h=0;h<e;++h)n[h]=String.fromCharCode(z[d+4+h]);n=n.join("")}F(d);return n},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var g="string"===typeof e;g||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array||V("Cannot pass non-string to std::string");var h=(c&&g?function(){return qa(e)}:function(){return e.length})(),l=yb(4+h+1);Aa[l>>2]=h;if(c&&g)pa(e,
z,l+4,h+1);else if(g)for(g=0;g<h;++g){var n=e.charCodeAt(g);255<n&&(F(l),V("String has UTF-16 code units that do not fit in 8 bits"));z[l+4+g]=n}else for(g=0;g<h;++g)z[l+4+g]=e[g];null!==d&&d.push(F,l);return l},argPackAdvance:8,readValueFromPointer:hd,U:function(d){F(d)}})},_embind_register_std_wstring:function(a,b,c){c=U(c);if(2===b){var d=sa;var e=ua;var g=va;var h=function(){return ta};var l=1}else 4===b&&(d=wa,e=xa,g=ya,h=function(){return Aa},l=2);Lc(a,{name:c,fromWireType:function(n){for(var m=
Aa[n>>2],t=h(),w,u=n+4,k=0;k<=m;++k){var r=n+4+k*b;if(k==m||0==t[r>>l])u=d(u,r-u),void 0===w?w=u:(w+=String.fromCharCode(0),w+=u),u=r+b}F(n);return w},toWireType:function(n,m){"string"!==typeof m&&V("Cannot pass non-string to C++ string type "+c);var t=g(m),w=yb(4+t+b);Aa[w>>2]=t>>l;e(m,w+4,t+b);null!==n&&n.push(F,w);return w},argPackAdvance:8,readValueFromPointer:hd,U:function(n){F(n)}})},_embind_register_void:function(a,b){b=U(b);Lc(a,{Zb:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},
abort:function(){y()},clock_gettime:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=zd();else return fb(28),-1;B[b>>2]=a/1E3|0;B[b+4>>2]=a%1E3*1E6|0;return 0},emscripten_get_sbrk_ptr:function(){return 109520},emscripten_memcpy_big:function(a,b,c){z.copyWithin(a,b,b+c)},emscripten_resize_heap:function(a){a>>>=0;var b=z.length;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(16777216,a,d);0<d%65536&&(d+=65536-d%65536);a:{try{ja.grow(Math.min(2147483648,
d)-za.byteLength+65535>>>16);Ea(ja.buffer);var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1},environ_get:function(a,b){var c=0;Bd().forEach(function(d,e){var g=b+c;e=B[a+4*e>>2]=g;for(g=0;g<d.length;++g)C[e++>>0]=d.charCodeAt(g);C[e>>0]=0;c+=d.length+1});return 0},environ_sizes_get:function(a,b){var c=Bd();B[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});B[b>>2]=d;return 0},fd_close:function(a){try{var b=mc(a);if(null===b.A)throw new G(8);b.La&&(b.La=null);try{b.c.close&&b.c.close(b)}catch(c){throw c;
}finally{Bb[b.A]=null}b.A=null;return 0}catch(c){return"undefined"!==typeof L&&c instanceof G||y(c),c.l}},fd_read:function(a,b,c,d){try{a:{for(var e=mc(a),g=a=0;g<c;g++){var h=B[b+(8*g+4)>>2],l=dc(e,B[b+8*g>>2],h,void 0);if(0>l){var n=-1;break a}a+=l;if(l<h)break}n=a}B[d>>2]=n;return 0}catch(m){return"undefined"!==typeof L&&m instanceof G||y(m),m.l}},fd_seek:function(a,b,c,d,e){try{var g=mc(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;cc(g,a,d);Za=[g.position>>>
0,(Ya=g.position,1<=+Ma(Ya)?0<Ya?(Pa(+Oa(Ya/4294967296),4294967295)|0)>>>0:~~+Na((Ya-+(~~Ya>>>0))/4294967296)>>>0:0)];B[e>>2]=Za[0];B[e+4>>2]=Za[1];g.La&&0===a&&0===d&&(g.La=null);return 0}catch(h){return"undefined"!==typeof L&&h instanceof G||y(h),h.l}},fd_write:function(a,b,c,d){try{a:{for(var e=mc(a),g=a=0;g<c;g++){var h=ec(e,B[b+8*g>>2],B[b+(8*g+4)>>2],void 0);if(0>h){var l=-1;break a}a+=h}l=a}B[d>>2]=l;return 0}catch(n){return"undefined"!==typeof L&&n instanceof G||y(n),n.l}},getTempRet0:function(){return q|
0},invoke_diii:Qd,invoke_fiii:Rd,invoke_i:Sd,invoke_idiii:Td,invoke_ii:Ud,invoke_iid:Vd,invoke_iif:Wd,invoke_iii:Xd,invoke_iiii:Yd,invoke_iiiii:Zd,invoke_iiiiii:$d,invoke_iiiiiii:ae,invoke_iiiiiiii:be,invoke_iiiiiiiiiii:ce,invoke_iiiiiiiiiiii:de,invoke_iiiiiiiiiiiii:ee,invoke_iiiiiij:fe,invoke_iij:ge,invoke_iijj:he,invoke_ijj:ie,invoke_ijjiii:je,invoke_ji:ke,invoke_jii:le,invoke_jiiii:me,invoke_v:ne,invoke_vi:oe,invoke_vii:pe,invoke_viid:qe,invoke_viii:re,invoke_viiii:se,invoke_viiiii:te,invoke_viiiiii:ue,
invoke_viiiiiii:ve,invoke_viiiiiiiiii:we,invoke_viiiiiiiiiiiiiii:xe,llvm_eh_typeid_for:function(a){return a},memory:ja,nanosleep:function(a,b){if(0===a)return fb(28),-1;var c=B[a>>2];a=B[a+4>>2];if(0>a||999999999<a||0>c)return fb(28),-1;0!==b&&(B[b>>2]=0,B[b+4>>2]=0);b=1E6*c+a/1E3;for(c=zd();zd()-c<b/1E3;);},pthread_condattr_init:function(){return 0},pthread_condattr_setclock:function(){return 0},pthread_create:function(){return 6},pthread_detach:function(){},pthread_join:function(){},pthread_sigmask:function(){p("pthread_sigmask() is not supported: this is a no-op.");
return 0},setTempRet0:function(a){q=a|0},sigfillset:function(a){B[a>>2]=4294967295;return 0},strftime_l:function(a,b,c,d){return Id(a,b,c,d)},sysconf:function(a){switch(a){case 30:return 16384;case 85:return 131072;case 132:case 133:case 12:case 137:case 138:case 15:case 235:case 16:case 17:case 18:case 19:case 20:case 149:case 13:case 10:case 236:case 153:case 9:case 21:case 22:case 159:case 154:case 14:case 77:case 78:case 139:case 80:case 81:case 82:case 68:case 67:case 164:case 11:case 29:case 47:case 48:case 95:case 52:case 51:case 46:case 79:return 200809;
case 27:case 246:case 127:case 128:case 23:case 24:case 160:case 161:case 181:case 182:case 242:case 183:case 184:case 243:case 244:case 245:case 165:case 178:case 179:case 49:case 50:case 168:case 169:case 175:case 170:case 171:case 172:case 97:case 76:case 32:case 173:case 35:return-1;case 176:case 177:case 7:case 155:case 8:case 157:case 125:case 126:case 92:case 93:case 129:case 130:case 131:case 94:case 91:return 1;case 74:case 60:case 69:case 70:case 4:return 1024;case 31:case 42:case 72:return 32;
case 87:case 26:case 33:return 2147483647;case 34:case 1:return 47839;case 38:case 36:return 99;case 43:case 37:return 2048;case 0:return 2097152;case 3:return 65536;case 28:return 32768;case 44:return 32767;case 75:return 16384;case 39:return 1E3;case 89:return 700;case 71:return 256;case 40:return 255;case 2:return 100;case 180:return 64;case 25:return 20;case 5:return 16;case 6:return 6;case 73:return 4;case 84:return"object"===typeof navigator?navigator.hardwareConcurrency||1:1}fb(28);return-1},
table:ka};
(function(){function a(e){f.asm=e.exports;Qa--;f.monitorRunDependencies&&f.monitorRunDependencies(Qa);0==Qa&&(null!==Ra&&(clearInterval(Ra),Ra=null),Sa&&(e=Sa,Sa=null,e()))}function b(e){a(e.instance)}function c(e){return Xa().then(function(g){return WebAssembly.instantiate(g,d)}).then(e,function(g){p("failed to asynchronously prepare wasm: "+g);y(g)})}var d={env:ye,wasi_snapshot_preview1:ye};Qa++;f.monitorRunDependencies&&f.monitorRunDependencies(Qa);if(f.instantiateWasm)try{return f.instantiateWasm(d,a)}catch(e){return p("Module.instantiateWasm callback failed with error: "+
e),!1}(function(){if(ia||"function"!==typeof WebAssembly.instantiateStreaming||Ta()||"function"!==typeof fetch)return c(b);fetch(Ua,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(g){p("wasm streaming compile failed: "+g);p("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();
var $a=f.___wasm_call_ctors=function(){return($a=f.___wasm_call_ctors=f.asm.__wasm_call_ctors).apply(null,arguments)},F=f._free=function(){return(F=f._free=f.asm.free).apply(null,arguments)},Pd=f._memset=function(){return(Pd=f._memset=f.asm.memset).apply(null,arguments)},gb=f.___errno_location=function(){return(gb=f.___errno_location=f.asm.__errno_location).apply(null,arguments)},yb=f._malloc=function(){return(yb=f._malloc=f.asm.malloc).apply(null,arguments)},pc=f._htons=function(){return(pc=f._htons=
f.asm.htons).apply(null,arguments)};f._htonl=function(){return(f._htonl=f.asm.htonl).apply(null,arguments)};var xc=f._ntohs=function(){return(xc=f._ntohs=f.asm.ntohs).apply(null,arguments)},rd=f.___getTypeName=function(){return(rd=f.___getTypeName=f.asm.__getTypeName).apply(null,arguments)};f.___embind_register_native_and_builtin_types=function(){return(f.___embind_register_native_and_builtin_types=f.asm.__embind_register_native_and_builtin_types).apply(null,arguments)};
f.__get_tzname=function(){return(f.__get_tzname=f.asm._get_tzname).apply(null,arguments)};f.__get_daylight=function(){return(f.__get_daylight=f.asm._get_daylight).apply(null,arguments)};f.__get_timezone=function(){return(f.__get_timezone=f.asm._get_timezone).apply(null,arguments)};
var X=f._setThrew=function(){return(X=f._setThrew=f.asm.setThrew).apply(null,arguments)},Y=f.stackSave=function(){return(Y=f.stackSave=f.asm.stackSave).apply(null,arguments)},Z=f.stackRestore=function(){return(Z=f.stackRestore=f.asm.stackRestore).apply(null,arguments)};f.stackAlloc=function(){return(f.stackAlloc=f.asm.stackAlloc).apply(null,arguments)};
var Ld=f.__ZSt18uncaught_exceptionv=function(){return(Ld=f.__ZSt18uncaught_exceptionv=f.asm._ZSt18uncaught_exceptionv).apply(null,arguments)},Nd=f.___cxa_can_catch=function(){return(Nd=f.___cxa_can_catch=f.asm.__cxa_can_catch).apply(null,arguments)},Md=f.___cxa_is_pointer_type=function(){return(Md=f.___cxa_is_pointer_type=f.asm.__cxa_is_pointer_type).apply(null,arguments)},Od=f._memalign=function(){return(Od=f._memalign=f.asm.memalign).apply(null,arguments)};
f._emscripten_main_thread_process_queued_calls=function(){return(f._emscripten_main_thread_process_queued_calls=f.asm.emscripten_main_thread_process_queued_calls).apply(null,arguments)};
var ze=f.dynCall_v=function(){return(ze=f.dynCall_v=f.asm.dynCall_v).apply(null,arguments)},Ae=f.dynCall_vi=function(){return(Ae=f.dynCall_vi=f.asm.dynCall_vi).apply(null,arguments)},De=f.dynCall_vii=function(){return(De=f.dynCall_vii=f.asm.dynCall_vii).apply(null,arguments)},Ee=f.dynCall_viii=function(){return(Ee=f.dynCall_viii=f.asm.dynCall_viii).apply(null,arguments)},Fe=f.dynCall_viiii=function(){return(Fe=f.dynCall_viiii=f.asm.dynCall_viiii).apply(null,arguments)},Ge=f.dynCall_viiiii=function(){return(Ge=
f.dynCall_viiiii=f.asm.dynCall_viiiii).apply(null,arguments)},He=f.dynCall_viiiiii=function(){return(He=f.dynCall_viiiiii=f.asm.dynCall_viiiiii).apply(null,arguments)},Ie=f.dynCall_viiiiiii=function(){return(Ie=f.dynCall_viiiiiii=f.asm.dynCall_viiiiiii).apply(null,arguments)},Je=f.dynCall_viiiiiiiiii=function(){return(Je=f.dynCall_viiiiiiiiii=f.asm.dynCall_viiiiiiiiii).apply(null,arguments)},Ke=f.dynCall_viiiiiiiiiiiiiii=function(){return(Ke=f.dynCall_viiiiiiiiiiiiiii=f.asm.dynCall_viiiiiiiiiiiiiii).apply(null,
arguments)},Le=f.dynCall_viid=function(){return(Le=f.dynCall_viid=f.asm.dynCall_viid).apply(null,arguments)},Me=f.dynCall_i=function(){return(Me=f.dynCall_i=f.asm.dynCall_i).apply(null,arguments)},Ne=f.dynCall_ii=function(){return(Ne=f.dynCall_ii=f.asm.dynCall_ii).apply(null,arguments)},Oe=f.dynCall_iii=function(){return(Oe=f.dynCall_iii=f.asm.dynCall_iii).apply(null,arguments)},Pe=f.dynCall_iiii=function(){return(Pe=f.dynCall_iiii=f.asm.dynCall_iiii).apply(null,arguments)},Qe=f.dynCall_iiiii=function(){return(Qe=
f.dynCall_iiiii=f.asm.dynCall_iiiii).apply(null,arguments)},Re=f.dynCall_iiiiii=function(){return(Re=f.dynCall_iiiiii=f.asm.dynCall_iiiiii).apply(null,arguments)},Se=f.dynCall_iiiiiii=function(){return(Se=f.dynCall_iiiiiii=f.asm.dynCall_iiiiiii).apply(null,arguments)},Te=f.dynCall_iiiiiiii=function(){return(Te=f.dynCall_iiiiiiii=f.asm.dynCall_iiiiiiii).apply(null,arguments)},Ue=f.dynCall_iiiiiiiiiii=function(){return(Ue=f.dynCall_iiiiiiiiiii=f.asm.dynCall_iiiiiiiiiii).apply(null,arguments)},Ve=f.dynCall_iiiiiiiiiiii=
function(){return(Ve=f.dynCall_iiiiiiiiiiii=f.asm.dynCall_iiiiiiiiiiii).apply(null,arguments)},We=f.dynCall_iiiiiiiiiiiii=function(){return(We=f.dynCall_iiiiiiiiiiiii=f.asm.dynCall_iiiiiiiiiiiii).apply(null,arguments)},Xe=f.dynCall_iiiiiij=function(){return(Xe=f.dynCall_iiiiiij=f.asm.dynCall_iiiiiij).apply(null,arguments)},Ye=f.dynCall_iij=function(){return(Ye=f.dynCall_iij=f.asm.dynCall_iij).apply(null,arguments)},Ze=f.dynCall_iijj=function(){return(Ze=f.dynCall_iijj=f.asm.dynCall_iijj).apply(null,
arguments)},$e=f.dynCall_iif=function(){return($e=f.dynCall_iif=f.asm.dynCall_iif).apply(null,arguments)},af=f.dynCall_iid=function(){return(af=f.dynCall_iid=f.asm.dynCall_iid).apply(null,arguments)},bf=f.dynCall_ijj=function(){return(bf=f.dynCall_ijj=f.asm.dynCall_ijj).apply(null,arguments)},cf=f.dynCall_ijjiii=function(){return(cf=f.dynCall_ijjiii=f.asm.dynCall_ijjiii).apply(null,arguments)},df=f.dynCall_idiii=function(){return(df=f.dynCall_idiii=f.asm.dynCall_idiii).apply(null,arguments)},ef=f.dynCall_ji=
function(){return(ef=f.dynCall_ji=f.asm.dynCall_ji).apply(null,arguments)},ff=f.dynCall_jii=function(){return(ff=f.dynCall_jii=f.asm.dynCall_jii).apply(null,arguments)},gf=f.dynCall_jiiii=function(){return(gf=f.dynCall_jiiii=f.asm.dynCall_jiiii).apply(null,arguments)},hf=f.dynCall_fiii=function(){return(hf=f.dynCall_fiii=f.asm.dynCall_fiii).apply(null,arguments)},jf=f.dynCall_diii=function(){return(jf=f.dynCall_diii=f.asm.dynCall_diii).apply(null,arguments)};
f.__growWasmMemory=function(){return(f.__growWasmMemory=f.asm.__growWasmMemory).apply(null,arguments)};f.dynCall_vj=function(){return(f.dynCall_vj=f.asm.dynCall_vj).apply(null,arguments)};f.dynCall_viij=function(){return(f.dynCall_viij=f.asm.dynCall_viij).apply(null,arguments)};f.dynCall_vij=function(){return(f.dynCall_vij=f.asm.dynCall_vij).apply(null,arguments)};f.dynCall_iidiiii=function(){return(f.dynCall_iidiiii=f.asm.dynCall_iidiiii).apply(null,arguments)};
f.dynCall_jiji=function(){return(f.dynCall_jiji=f.asm.dynCall_jiji).apply(null,arguments)};f.dynCall_viijii=function(){return(f.dynCall_viijii=f.asm.dynCall_viijii).apply(null,arguments)};f.dynCall_iiiiiiiii=function(){return(f.dynCall_iiiiiiiii=f.asm.dynCall_iiiiiiiii).apply(null,arguments)};f.dynCall_iiiiij=function(){return(f.dynCall_iiiiij=f.asm.dynCall_iiiiij).apply(null,arguments)};f.dynCall_iiiiid=function(){return(f.dynCall_iiiiid=f.asm.dynCall_iiiiid).apply(null,arguments)};
f.dynCall_iiiiijj=function(){return(f.dynCall_iiiiijj=f.asm.dynCall_iiiiijj).apply(null,arguments)};f.dynCall_iiiiiijj=function(){return(f.dynCall_iiiiiijj=f.asm.dynCall_iiiiiijj).apply(null,arguments)};function Ud(a,b){var c=Y();try{return Ne(a,b)}catch(d){Z(c);if(d!==d+0&&"longjmp"!==d)throw d;X(1,0)}}function se(a,b,c,d,e){var g=Y();try{Fe(a,b,c,d,e)}catch(h){Z(g);if(h!==h+0&&"longjmp"!==h)throw h;X(1,0)}}
function Xd(a,b,c){var d=Y();try{return Oe(a,b,c)}catch(e){Z(d);if(e!==e+0&&"longjmp"!==e)throw e;X(1,0)}}function pe(a,b,c){var d=Y();try{De(a,b,c)}catch(e){Z(d);if(e!==e+0&&"longjmp"!==e)throw e;X(1,0)}}function oe(a,b){var c=Y();try{Ae(a,b)}catch(d){Z(c);if(d!==d+0&&"longjmp"!==d)throw d;X(1,0)}}function re(a,b,c,d){var e=Y();try{Ee(a,b,c,d)}catch(g){Z(e);if(g!==g+0&&"longjmp"!==g)throw g;X(1,0)}}
function Zd(a,b,c,d,e){var g=Y();try{return Qe(a,b,c,d,e)}catch(h){Z(g);if(h!==h+0&&"longjmp"!==h)throw h;X(1,0)}}function Yd(a,b,c,d){var e=Y();try{return Pe(a,b,c,d)}catch(g){Z(e);if(g!==g+0&&"longjmp"!==g)throw g;X(1,0)}}function ne(a){var b=Y();try{ze(a)}catch(c){Z(b);if(c!==c+0&&"longjmp"!==c)throw c;X(1,0)}}function ue(a,b,c,d,e,g,h){var l=Y();try{He(a,b,c,d,e,g,h)}catch(n){Z(l);if(n!==n+0&&"longjmp"!==n)throw n;X(1,0)}}
function $d(a,b,c,d,e,g){var h=Y();try{return Re(a,b,c,d,e,g)}catch(l){Z(h);if(l!==l+0&&"longjmp"!==l)throw l;X(1,0)}}function Sd(a){var b=Y();try{return Me(a)}catch(c){Z(b);if(c!==c+0&&"longjmp"!==c)throw c;X(1,0)}}function Td(a,b,c,d,e){var g=Y();try{return df(a,b,c,d,e)}catch(h){Z(g);if(h!==h+0&&"longjmp"!==h)throw h;X(1,0)}}function te(a,b,c,d,e,g){var h=Y();try{Ge(a,b,c,d,e,g)}catch(l){Z(h);if(l!==l+0&&"longjmp"!==l)throw l;X(1,0)}}
function Vd(a,b,c){var d=Y();try{return af(a,b,c)}catch(e){Z(d);if(e!==e+0&&"longjmp"!==e)throw e;X(1,0)}}function ve(a,b,c,d,e,g,h,l){var n=Y();try{Ie(a,b,c,d,e,g,h,l)}catch(m){Z(n);if(m!==m+0&&"longjmp"!==m)throw m;X(1,0)}}function be(a,b,c,d,e,g,h,l){var n=Y();try{return Te(a,b,c,d,e,g,h,l)}catch(m){Z(n);if(m!==m+0&&"longjmp"!==m)throw m;X(1,0)}}function ae(a,b,c,d,e,g,h){var l=Y();try{return Se(a,b,c,d,e,g,h)}catch(n){Z(l);if(n!==n+0&&"longjmp"!==n)throw n;X(1,0)}}
function Wd(a,b,c){var d=Y();try{return $e(a,b,c)}catch(e){Z(d);if(e!==e+0&&"longjmp"!==e)throw e;X(1,0)}}function ce(a,b,c,d,e,g,h,l,n,m,t){var w=Y();try{return Ue(a,b,c,d,e,g,h,l,n,m,t)}catch(u){Z(w);if(u!==u+0&&"longjmp"!==u)throw u;X(1,0)}}function ee(a,b,c,d,e,g,h,l,n,m,t,w,u){var k=Y();try{return We(a,b,c,d,e,g,h,l,n,m,t,w,u)}catch(r){Z(k);if(r!==r+0&&"longjmp"!==r)throw r;X(1,0)}}function Rd(a,b,c,d){var e=Y();try{return hf(a,b,c,d)}catch(g){Z(e);if(g!==g+0&&"longjmp"!==g)throw g;X(1,0)}}
function Qd(a,b,c,d){var e=Y();try{return jf(a,b,c,d)}catch(g){Z(e);if(g!==g+0&&"longjmp"!==g)throw g;X(1,0)}}function de(a,b,c,d,e,g,h,l,n,m,t,w){var u=Y();try{return Ve(a,b,c,d,e,g,h,l,n,m,t,w)}catch(k){Z(u);if(k!==k+0&&"longjmp"!==k)throw k;X(1,0)}}function we(a,b,c,d,e,g,h,l,n,m,t){var w=Y();try{Je(a,b,c,d,e,g,h,l,n,m,t)}catch(u){Z(w);if(u!==u+0&&"longjmp"!==u)throw u;X(1,0)}}
function xe(a,b,c,d,e,g,h,l,n,m,t,w,u,k,r,x){var v=Y();try{Ke(a,b,c,d,e,g,h,l,n,m,t,w,u,k,r,x)}catch(H){Z(v);if(H!==H+0&&"longjmp"!==H)throw H;X(1,0)}}function qe(a,b,c,d){var e=Y();try{Le(a,b,c,d)}catch(g){Z(e);if(g!==g+0&&"longjmp"!==g)throw g;X(1,0)}}function ie(a,b,c,d,e){var g=Y();try{return bf(a,b,c,d,e)}catch(h){Z(g);if(h!==h+0&&"longjmp"!==h)throw h;X(1,0)}}function je(a,b,c,d,e,g,h,l){var n=Y();try{return cf(a,b,c,d,e,g,h,l)}catch(m){Z(n);if(m!==m+0&&"longjmp"!==m)throw m;X(1,0)}}
function ge(a,b,c,d){var e=Y();try{return Ye(a,b,c,d)}catch(g){Z(e);if(g!==g+0&&"longjmp"!==g)throw g;X(1,0)}}function ke(a,b){var c=Y();try{return ef(a,b)}catch(d){Z(c);if(d!==d+0&&"longjmp"!==d)throw d;X(1,0)}}function fe(a,b,c,d,e,g,h,l){var n=Y();try{return Xe(a,b,c,d,e,g,h,l)}catch(m){Z(n);if(m!==m+0&&"longjmp"!==m)throw m;X(1,0)}}function he(a,b,c,d,e,g){var h=Y();try{return Ze(a,b,c,d,e,g)}catch(l){Z(h);if(l!==l+0&&"longjmp"!==l)throw l;X(1,0)}}
function le(a,b,c){var d=Y();try{return ff(a,b,c)}catch(e){Z(d);if(e!==e+0&&"longjmp"!==e)throw e;X(1,0)}}function me(a,b,c,d,e){var g=Y();try{return gf(a,b,c,d,e)}catch(h){Z(g);if(h!==h+0&&"longjmp"!==h)throw h;X(1,0)}}var kf;Sa=function lf(){kf||mf();kf||(Sa=lf)};
function mf(){function a(){if(!kf&&(kf=!0,f.calledRun=!0,!la)){f.noFSInit||gc||(gc=!0,fc(),f.stdin=f.stdin,f.stdout=f.stdout,f.stderr=f.stderr,f.stdin?ic("stdin",f.stdin):$b("/dev/tty","/dev/stdin"),f.stdout?ic("stdout",null,f.stdout):$b("/dev/tty","/dev/stdout"),f.stderr?ic("stderr",null,f.stderr):$b("/dev/tty1","/dev/stderr"),ac("/dev/stdin","r"),ac("/dev/stdout","w"),ac("/dev/stderr","w"));S.root=Wb(S,null);T.root=Wb(T,null);Ga(Ia);Eb=!1;Ga(Ja);aa(f);if(f.onRuntimeInitialized)f.onRuntimeInitialized();
if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var b=f.postRun.shift();Ka.unshift(b)}Ga(Ka)}}if(!(0<Qa)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)La();Ga(Ha);0<Qa||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);a()},1)):a())}}f.run=mf;if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();
noExitRuntime=!0;mf();


  return Tiro.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
      module.exports = Tiro;
    else if (typeof define === 'function' && define['amd'])
      define([], function() { return Tiro; });
    else if (typeof exports === 'object')
      exports["Tiro"] = Tiro;
    