
var Tiro = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  
  return (
function(Tiro) {
  Tiro = Tiro || {};


var f;f||(f=typeof Tiro !== 'undefined' ? Tiro : {});var aa,ba;f.ready=new Promise(function(a,b){aa=a;ba=b});var ca={},p;for(p in f)f.hasOwnProperty(p)&&(ca[p]=f[p]);var da="./this.program",v="";document.currentScript&&(v=document.currentScript.src);_scriptDir&&(v=_scriptDir);0!==v.indexOf("blob:")?v=v.substr(0,v.lastIndexOf("/")+1):v="";var ha=f.print||console.log.bind(console),y=f.printErr||console.warn.bind(console);for(p in ca)ca.hasOwnProperty(p)&&(f[p]=ca[p]);ca=null;
f.thisProgram&&(da=f.thisProgram);var z=0,ia;f.wasmBinary&&(ia=f.wasmBinary);var noExitRuntime;f.noExitRuntime&&(noExitRuntime=f.noExitRuntime);"object"!==typeof WebAssembly&&A("no native wasm support detected");var B,ja=new WebAssembly.Table({initial:1895,maximum:1895,element:"anyfunc"}),ka=!1;function la(a){a||A("Assertion failed: undefined")}var ma="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function C(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&ma)return ma.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|h:(e&7)<<18|g<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}
function na(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var l=a.charCodeAt(++g);h=65536+((h&1023)<<10)|l&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}
function oa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}var pa="undefined"!==typeof TextDecoder?new TextDecoder("utf-16le"):void 0;function qa(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&ta[c];)++c;c<<=1;if(32<c-a&&pa)return pa.decode(D.subarray(a,c));c=0;for(d="";;){var e=ua[a+2*c>>1];if(0==e||c==b/2)return d;++c;d+=String.fromCharCode(e)}}
function va(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)ua[b>>1]=a.charCodeAt(e),b+=2;ua[b>>1]=0;return b-d}function wa(a){return 2*a.length}function xa(a,b){for(var c=0,d="";!(c>=b/4);){var e=E[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}
function ya(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var g=a.charCodeAt(e);if(55296<=g&&57343>=g){var h=a.charCodeAt(++e);g=65536+((g&1023)<<10)|h&1023}E[b>>2]=g;b+=4;if(b+4>c)break}E[b>>2]=0;return b-d}function za(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}var G,I,D,ua,ta,E,J,Aa,Ba;
function Ca(a){G=a;f.HEAP8=I=new Int8Array(a);f.HEAP16=ua=new Int16Array(a);f.HEAP32=E=new Int32Array(a);f.HEAPU8=D=new Uint8Array(a);f.HEAPU16=ta=new Uint16Array(a);f.HEAPU32=J=new Uint32Array(a);f.HEAPF32=Aa=new Float32Array(a);f.HEAPF64=Ba=new Float64Array(a)}var Da=f.INITIAL_MEMORY||16777216;f.wasmMemory?B=f.wasmMemory:B=new WebAssembly.Memory({initial:Da/65536,maximum:32768});B&&(G=B.buffer);Da=G.byteLength;Ca(G);E[27412]=5352704;
function Ea(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(f);else{var c=b.Ka;"number"===typeof c?void 0===b.na?f.dynCall_v(c):f.dynCall_vi(c,b.na):c(void 0===b.na?null:b.na)}}}var Fa=[],Ga=[],Ha=[],Ia=[];function Ja(){var a=f.preRun.shift();Fa.unshift(a)}var Ka=Math.abs,La=Math.ceil,Ma=Math.floor,Na=Math.min,K=0,Oa=null,Pa=null;f.preloadedImages={};f.preloadedAudios={};
function A(a){if(f.onAbort)f.onAbort(a);y(a);ka=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}function Qa(){var a=Ra;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var Ra="tiro.wasm";if(!Qa()){var Sa=Ra;Ra=f.locateFile?f.locateFile(Sa,v):v+Sa}
function Ta(){try{if(ia)return new Uint8Array(ia);throw"both async and sync fetching of the wasm failed";}catch(a){A(a)}}function Ua(){return ia||"function"!==typeof fetch?new Promise(function(a){a(Ta())}):fetch(Ra,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+Ra+"'";return a.arrayBuffer()}).catch(function(){return Ta()})}var Va,Wa;Ga.push({Ka:function(){Xa()}});var L={},Ya=[];
function Za(a){if(!a||L[a])return a;for(var b in L)for(var c=+b,d=L[c].T,e=d.length,g=0;g<e;g++)if(d[g]===a)return c;return a}function $a(a){if(a){var b=L[a];b.M--;0!==b.M||b.Y||(b.U&&f.dynCall_ii(b.U,a),delete L[a],M(a))}}var N=0;function ab(){var a=Ya.pop();a=Za(a);L[a].Y||(Ya.push(a),L[a].Y=!0);N=a;throw a;}function bb(a){E[cb()>>2]=a}
function db(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function eb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=db(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function fb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function gb(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function hb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=db(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var ib=[];function jb(a,b){ib[a]={input:[],m:[],R:b};kb(a,lb)}
var lb={open:function(a){var b=ib[a.node.ha];if(!b)throw new O(43);a.u=b;a.seekable=!1},close:function(a){a.u.R.flush(a.u)},flush:function(a){a.u.R.flush(a.u)},read:function(a,b,c,d){if(!a.u||!a.u.R.Aa)throw new O(60);for(var e=0,g=0;g<d;g++){try{var h=a.u.R.Aa(a.u)}catch(l){throw new O(29);}if(void 0===h&&0===e)throw new O(6);if(null===h||void 0===h)break;e++;b[c+g]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.u||!a.u.R.qa)throw new O(60);try{for(var e=0;e<d;e++)a.u.R.qa(a.u,
b[c+e])}catch(g){throw new O(29);}d&&(a.node.timestamp=Date.now());return e}},nb={Aa:function(a){if(!a.input.length){var b=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=mb(b,!0)}return a.input.shift()},qa:function(a,b){null===b||10===b?(ha(C(a.m,0)),a.m=[]):0!=b&&a.m.push(b)},flush:function(a){a.m&&0<a.m.length&&(ha(C(a.m,0)),a.m=[])}},ob={qa:function(a,
b){null===b||10===b?(y(C(a.m,0)),a.m=[]):0!=b&&a.m.push(b)},flush:function(a){a.m&&0<a.m.length&&(y(C(a.m,0)),a.m=[])}},P={B:null,G:function(){return P.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new O(63);P.B||(P.B={dir:{node:{I:P.g.I,D:P.g.D,V:P.g.V,da:P.g.da,Ea:P.g.Ea,Ga:P.g.Ga,Fa:P.g.Fa,Da:P.g.Da,ia:P.g.ia},stream:{K:P.f.K}},file:{node:{I:P.g.I,D:P.g.D},stream:{K:P.f.K,read:P.f.read,write:P.f.write,ta:P.f.ta,ea:P.f.ea,ga:P.f.ga}},link:{node:{I:P.g.I,
D:P.g.D,X:P.g.X},stream:{}},va:{node:{I:P.g.I,D:P.g.D},stream:pb}});c=qb(a,b,c,d);16384===(c.mode&61440)?(c.g=P.B.dir.node,c.f=P.B.dir.stream,c.c={}):32768===(c.mode&61440)?(c.g=P.B.file.node,c.f=P.B.file.stream,c.j=0,c.c=null):40960===(c.mode&61440)?(c.g=P.B.link.node,c.f=P.B.link.stream):8192===(c.mode&61440)&&(c.g=P.B.va.node,c.f=P.B.va.stream);c.timestamp=Date.now();a&&(a.c[b]=c);return c},jb:function(a){if(a.c&&a.c.subarray){for(var b=[],c=0;c<a.j;++c)b.push(a.c[c]);return b}return a.c},kb:function(a){return a.c?
a.c.subarray?a.c.subarray(0,a.j):new Uint8Array(a.c):new Uint8Array(0)},wa:function(a,b){var c=a.c?a.c.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.c,a.c=new Uint8Array(b),0<a.j&&a.c.set(c.subarray(0,a.j),0))},Xa:function(a,b){if(a.j!=b)if(0==b)a.c=null,a.j=0;else{if(!a.c||a.c.subarray){var c=a.c;a.c=new Uint8Array(b);c&&a.c.set(c.subarray(0,Math.min(b,a.j)))}else if(a.c||(a.c=[]),a.c.length>b)a.c.length=b;else for(;a.c.length<b;)a.c.push(0);a.j=b}},g:{I:function(a){var b=
{};b.ib=8192===(a.mode&61440)?a.id:1;b.mb=a.id;b.mode=a.mode;b.pb=1;b.uid=0;b.lb=0;b.ha=a.ha;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.j:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.fb=new Date(a.timestamp);b.ob=new Date(a.timestamp);b.hb=new Date(a.timestamp);b.Ha=4096;b.gb=Math.ceil(b.size/b.Ha);return b},D:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&P.Xa(a,b.size)},V:function(){throw rb[44];},
da:function(a,b,c,d){return P.createNode(a,b,c,d)},Ea:function(a,b,c){if(16384===(a.mode&61440)){try{var d=sb(b,c)}catch(g){}if(d)for(var e in d.c)throw new O(55);}delete a.parent.c[a.name];a.name=c;b.c[c]=a;a.parent=b},Ga:function(a,b){delete a.c[b]},Fa:function(a,b){var c=sb(a,b),d;for(d in c.c)throw new O(55);delete a.c[b]},Da:function(a){var b=[".",".."],c;for(c in a.c)a.c.hasOwnProperty(c)&&b.push(c);return b},ia:function(a,b,c){a=P.createNode(a,b,41471,0);a.link=c;return a},X:function(a){if(40960!==
(a.mode&61440))throw new O(28);return a.link}},f:{read:function(a,b,c,d,e){var g=a.node.c;if(e>=a.node.j)return 0;a=Math.min(a.node.j-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write:function(a,b,c,d,e,g){b.buffer===I.buffer&&(g=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.c||a.c.subarray)){if(g)return a.c=b.subarray(c,c+d),a.j=d;if(0===a.j&&0===e)return a.c=b.slice(c,c+d),a.j=d;if(e+d<=a.j)return a.c.set(b.subarray(c,c+
d),e),d}P.wa(a,e+d);if(a.c.subarray&&b.subarray)a.c.set(b.subarray(c,c+d),e);else for(g=0;g<d;g++)a.c[e+g]=b[c+g];a.j=Math.max(a.j,e+d);return d},K:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.j);if(0>b)throw new O(28);return b},ta:function(a,b,c){P.wa(a.node,b+c);a.node.j=Math.max(a.node.j,b+c)},ea:function(a,b,c,d,e,g){la(0===b);if(32768!==(a.node.mode&61440))throw new O(43);a=a.node.c;if(g&2||a.buffer!==G){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):
a=Array.prototype.slice.call(a,d,d+c);d=!0;g=16384*Math.ceil(c/16384);for(b=tb(g);c<g;)I[b+c++]=0;c=b;if(!c)throw new O(48);I.set(a,c)}else d=!1,c=a.byteOffset;return{h:c,ma:d}},ga:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new O(43);if(e&2)return 0;P.f.write(a,b,0,d,c,!1);return 0}}},ub=null,vb={},wb=[],xb=1,yb=null,zb=!0,Ab={},O=null,rb={};
function Bb(a,b){a=hb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={za:!0,ra:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.ra)throw new O(32);a=db(a.split("/").filter(function(h){return!!h}),!1);var e=ub;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;e=sb(e,a[d]);c=eb(c+"/"+a[d]);e.fa&&(!g||g&&b.za)&&(e=e.fa.root);if(!g||b.ya)for(g=0;40960===(e.mode&61440);)if(e=Cb(c),c=hb(fb(c),e),e=Bb(c,{ra:b.ra}).node,40<g++)throw new O(32);}return{path:c,node:e}}
function Db(a){for(var b;;){if(a===a.parent)return a=a.G.Ba,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Eb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%yb.length}function sb(a,b){var c;if(c=(c=Fb(a,"x"))?c:a.g.V?0:2)throw new O(c,a);for(c=yb[Eb(a.id,b)];c;c=c.Ra){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.g.V(a,b)}function qb(a,b,c,d){a=new Gb(a,b,c,d);b=Eb(a.parent.id,a.name);a.Ra=yb[b];return yb[b]=a}
var Hb={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Ib(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Fb(a,b){if(zb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0}function Jb(a,b){try{return sb(a,b),20}catch(c){}return Fb(a,"wx")}
function Kb(){var a=4096;for(var b=0;b<=a;b++)if(!wb[b])return b;throw new O(33);}function Lb(a){Mb||(Mb=function(){},Mb.prototype={});var b=new Mb,c;for(c in a)b[c]=a[c];a=b;b=Kb();a.H=b;return wb[b]=a}var pb={open:function(a){a.f=vb[a.node.ha].f;a.f.open&&a.f.open(a)},K:function(){throw new O(70);}};function kb(a,b){vb[a]={f:b}}
function Nb(a,b){var c="/"===b,d=!b;if(c&&ub)throw new O(10);if(!c&&!d){var e=Bb(b,{za:!1});b=e.path;e=e.node;if(e.fa)throw new O(10);if(16384!==(e.mode&61440))throw new O(54);}b={type:a,qb:{},Ba:b,Qa:[]};a=a.G(b);a.G=b;b.root=a;c?ub=a:e&&(e.fa=b,e.G&&e.G.Qa.push(b))}function Ob(a,b,c){var d=Bb(a,{parent:!0}).node;a=gb(a);if(!a||"."===a||".."===a)throw new O(28);var e=Jb(d,a);if(e)throw new O(e);if(!d.g.da)throw new O(63);return d.g.da(d,a,b,c)}function Q(a){Ob(a,16895,0)}
function Pb(a,b,c){"undefined"===typeof c&&(c=b,b=438);Ob(a,b|8192,c)}function Qb(a,b){if(!hb(a))throw new O(44);var c=Bb(b,{parent:!0}).node;if(!c)throw new O(44);b=gb(b);var d=Jb(c,b);if(d)throw new O(d);if(!c.g.ia)throw new O(63);c.g.ia(c,b,a)}function Cb(a){a=Bb(a).node;if(!a)throw new O(44);if(!a.g.X)throw new O(28);return hb(Db(a.parent),a.g.X(a))}
function Rb(a,b){if(""===a)throw new O(44);if("string"===typeof b){var c=Hb[b];if("undefined"===typeof c)throw Error("Unknown file open mode: "+b);b=c}var d=b&64?("undefined"===typeof d?438:d)&4095|32768:0;if("object"===typeof a)var e=a;else{a=eb(a);try{e=Bb(a,{ya:!(b&131072)}).node}catch(h){}}c=!1;if(b&64)if(e){if(b&128)throw new O(20);}else e=Ob(a,d,0),c=!0;if(!e)throw new O(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new O(54);if(!c&&(d=e?40960===(e.mode&61440)?
32:16384===(e.mode&61440)&&("r"!==Ib(b)||b&512)?31:Fb(e,Ib(b)):44))throw new O(d);if(b&512){d=e;var g;"string"===typeof d?g=Bb(d,{ya:!0}).node:g=d;if(!g.g.D)throw new O(63);if(16384===(g.mode&61440))throw new O(31);if(32768!==(g.mode&61440))throw new O(28);if(d=Fb(g,"w"))throw new O(d);g.g.D(g,{size:0,timestamp:Date.now()})}b&=-131713;e=Lb({node:e,path:Db(e),flags:b,seekable:!0,position:0,f:e.f,eb:[],error:!1});e.f.open&&e.f.open(e);!f.logReadFiles||b&1||(Sb||(Sb={}),a in Sb||(Sb[a]=1,y("FS.trackingDelegate error on read file: "+
a)));try{Ab.onOpenFile&&(e=0,1!==(b&2097155)&&(e|=1),0!==(b&2097155)&&(e|=2),Ab.onOpenFile(a,e))}catch(h){y("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+h.message)}}function Tb(a,b,c){if(null===a.H)throw new O(8);if(!a.seekable||!a.f.K)throw new O(70);if(0!=c&&1!=c&&2!=c)throw new O(28);a.position=a.f.K(a,b,c);a.eb=[]}
function Ub(){O||(O=function(a,b){this.node=b;this.Ya=function(c){this.O=c};this.Ya(a);this.message="FS error"},O.prototype=Error(),O.prototype.constructor=O,[44].forEach(function(a){rb[a]=new O(a);rb[a].stack="<generic error, no stack>"}))}var Vb;function Wb(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function Xb(a,b,c){a=eb("/dev/"+a);var d=Wb(!!b,!!c);Yb||(Yb=64);var e=Yb++<<8|0;kb(e,{open:function(g){g.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(g,h,l,n){for(var m=0,r=0;r<n;r++){try{var x=b()}catch(t){throw new O(29);}if(void 0===x&&0===m)throw new O(6);if(null===x||void 0===x)break;m++;h[l+r]=x}m&&(g.node.timestamp=Date.now());return m},write:function(g,h,l,n){for(var m=0;m<n;m++)try{c(h[l+m])}catch(r){throw new O(29);}n&&(g.node.timestamp=Date.now());return m}});
Pb(a,d,e)}var Yb,Zb={},Mb,Sb,$b={};function ac(a){a=wb[a];if(!a)throw new O(8);return a}function bc(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var cc=void 0;function R(a){for(var b="";D[a];)b+=cc[D[a++]];return b}var dc={},ec={},fc={};function gc(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}
function hc(a,b){a=gc(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}function ic(a){var b=Error,c=hc(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}
var jc=void 0;function S(a){throw new jc(a);}var kc=void 0;function lc(a){throw new kc(a);}function mc(a,b,c){function d(l){l=c(l);l.length!==a.length&&lc("Mismatched type converter count");for(var n=0;n<a.length;++n)T(a[n],l[n])}a.forEach(function(l){fc[l]=b});var e=Array(b.length),g=[],h=0;b.forEach(function(l,n){ec.hasOwnProperty(l)?e[n]=ec[l]:(g.push(l),dc.hasOwnProperty(l)||(dc[l]=[]),dc[l].push(function(){e[n]=ec[l];++h;h===g.length&&d(e)}))});0===g.length&&d(e)}
function T(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||S('type "'+d+'" must have a positive integer typeid pointer');if(ec.hasOwnProperty(a)){if(c.Na)return;S("Cannot register type '"+d+"' twice")}ec[a]=b;delete fc[a];dc.hasOwnProperty(a)&&(b=dc[a],delete dc[a],b.forEach(function(e){e()}))}function nc(a){return{count:a.count,N:a.N,W:a.W,h:a.h,l:a.l,s:a.s,v:a.v}}
function oc(a){S(a.b.l.i.name+" instance already deleted")}var pc=!1;function qc(){}function rc(a){--a.count.value;0===a.count.value&&(a.s?a.v.L(a.s):a.l.i.L(a.h))}function sc(a){if("undefined"===typeof FinalizationGroup)return sc=function(b){return b},a;pc=new FinalizationGroup(function(b){for(var c=b.next();!c.done;c=b.next())c=c.value,c.h?rc(c):console.warn("object already deleted: "+c.h)});sc=function(b){pc.register(b,b.b,b.b);return b};qc=function(b){pc.unregister(b.b)};return sc(a)}
var tc=void 0,uc=[];function vc(){for(;uc.length;){var a=uc.pop();a.b.N=!1;a["delete"]()}}function U(){}var wc={};function xc(a,b,c){if(void 0===a[b].C){var d=a[b];a[b]=function(){a[b].C.hasOwnProperty(arguments.length)||S("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].C+")!");return a[b].C[arguments.length].apply(this,arguments)};a[b].C=[];a[b].C[d.aa]=d}}
function yc(a,b){f.hasOwnProperty(a)?(S("Cannot register public name '"+a+"' twice"),xc(f,a,a),f.hasOwnProperty(void 0)&&S("Cannot register multiple overloads of a function with the same number of arguments (undefined)!"),f[a].C[void 0]=b):f[a]=b}function zc(a,b,c,d,e,g,h,l){this.name=a;this.constructor=b;this.P=c;this.L=d;this.A=e;this.La=g;this.$=h;this.Ja=l;this.Ua=[]}
function Ac(a,b,c){for(;b!==c;)b.$||S("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.$(a),b=b.A;return a}function Bc(a,b){if(null===b)return this.pa&&S("null is not a valid "+this.name),0;b.b||S('Cannot pass "'+Cc(b)+'" as a '+this.name);b.b.h||S("Cannot pass deleted object as a pointer of type "+this.name);return Ac(b.b.h,b.b.l.i,this.i)}
function Dc(a,b){if(null===b){this.pa&&S("null is not a valid "+this.name);if(this.ca){var c=this.Va();null!==a&&a.push(this.L,c);return c}return 0}b.b||S('Cannot pass "'+Cc(b)+'" as a '+this.name);b.b.h||S("Cannot pass deleted object as a pointer of type "+this.name);!this.ba&&b.b.l.ba&&S("Cannot convert argument of type "+(b.b.v?b.b.v.name:b.b.l.name)+" to parameter type "+this.name);c=Ac(b.b.h,b.b.l.i,this.i);if(this.ca)switch(void 0===b.b.s&&S("Passing raw pointer to smart pointer is illegal"),
this.Za){case 0:b.b.v===this?c=b.b.s:S("Cannot convert argument of type "+(b.b.v?b.b.v.name:b.b.l.name)+" to parameter type "+this.name);break;case 1:c=b.b.s;break;case 2:if(b.b.v===this)c=b.b.s;else{var d=b.clone();c=this.Wa(c,Gc(function(){d["delete"]()}));null!==a&&a.push(this.L,c)}break;default:S("Unsupporting sharing policy")}return c}
function Hc(a,b){if(null===b)return this.pa&&S("null is not a valid "+this.name),0;b.b||S('Cannot pass "'+Cc(b)+'" as a '+this.name);b.b.h||S("Cannot pass deleted object as a pointer of type "+this.name);b.b.l.ba&&S("Cannot convert argument of type "+b.b.l.name+" to parameter type "+this.name);return Ac(b.b.h,b.b.l.i,this.i)}function Ic(a){return this.fromWireType(J[a>>2])}function Jc(a,b,c){if(b===c)return a;if(void 0===c.A)return null;a=Jc(a,b,c.A);return null===a?null:c.Ja(a)}var Kc={};
function Lc(a,b){for(void 0===b&&S("ptr should not be undefined");a.A;)b=a.$(b),a=a.A;return Kc[b]}function Mc(a,b){b.l&&b.h||lc("makeClassHandle requires ptr and ptrType");!!b.v!==!!b.s&&lc("Both smartPtrType and smartPtr must be specified");b.count={value:1};return sc(Object.create(a,{b:{value:b}}))}function V(a,b,c,d){this.name=a;this.i=b;this.pa=c;this.ba=d;this.ca=!1;this.L=this.Wa=this.Va=this.Ca=this.Za=this.Sa=void 0;void 0!==b.A?this.toWireType=Dc:(this.toWireType=d?Bc:Hc,this.F=null)}
function Nc(a,b){f.hasOwnProperty(a)||lc("Replacing nonexistant public symbol");f[a]=b;f[a].aa=void 0}function Oc(a,b){a=R(a);var c=f["dynCall_"+a];for(var d=[],e=1;e<a.length;++e)d.push("a"+e);e="return function dynCall_"+(a+"_"+b)+"("+d.join(", ")+") {\n";e+="    return dynCall(rawFunction"+(d.length?", ":"")+d.join(", ")+");\n";c=(new Function("dynCall","rawFunction",e+"};\n"))(c,b);"function"!==typeof c&&S("unknown function pointer with signature "+a+": "+b);return c}var Pc=void 0;
function Qc(a){a=Rc(a);var b=R(a);M(a);return b}function Sc(a,b){function c(g){e[g]||ec[g]||(fc[g]?fc[g].forEach(c):(d.push(g),e[g]=!0))}var d=[],e={};b.forEach(c);throw new Pc(a+": "+d.map(Qc).join([", "]));}function Tc(a,b){for(var c=[],d=0;d<a;d++)c.push(E[(b>>2)+d]);return c}function Uc(a){for(;a.length;){var b=a.pop();a.pop()(b)}}
function Vc(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=hc(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}var Wc=[],W=[{},{value:void 0},{value:null},{value:!0},{value:!1}];
function Gc(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Wc.length?Wc.pop():W.length;W[b]={M:1,value:a};return b}}function Cc(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}function Xc(a,b){switch(b){case 2:return function(c){return this.fromWireType(Aa[c>>2])};case 3:return function(c){return this.fromWireType(Ba[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function Yc(a,b,c){switch(b){case 0:return c?function(d){return I[d]}:function(d){return D[d]};case 1:return c?function(d){return ua[d>>1]}:function(d){return ta[d>>1]};case 2:return c?function(d){return E[d>>2]}:function(d){return J[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var Zc;Zc=function(){return performance.now()};var $c={};
function ad(){if(!bd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in $c)a[b]=$c[b];var c=[];for(b in a)c.push(b+"="+a[b]);bd=c}return bd}var bd;function cd(a){return 0===a%4&&(0!==a%100||0===a%400)}function dd(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}
var ed=[31,29,31,30,31,30,31,31,30,31,30,31],fd=[31,28,31,30,31,30,31,31,30,31,30,31];function gd(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(cd(a.getFullYear())?ed:fd)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function hd(a,b,c,d){function e(k,q,w){for(k="number"===typeof k?k.toString():k||"";k.length<q;)k=w[0]+k;return k}function g(k,q){return e(k,q,"0")}function h(k,q){function w(F){return 0>F?-1:0<F?1:0}var u;0===(u=w(k.getFullYear()-q.getFullYear()))&&0===(u=w(k.getMonth()-q.getMonth()))&&(u=w(k.getDate()-q.getDate()));return u}function l(k){switch(k.getDay()){case 0:return new Date(k.getFullYear()-1,11,29);case 1:return k;case 2:return new Date(k.getFullYear(),0,3);case 3:return new Date(k.getFullYear(),
0,2);case 4:return new Date(k.getFullYear(),0,1);case 5:return new Date(k.getFullYear()-1,11,31);case 6:return new Date(k.getFullYear()-1,11,30)}}function n(k){k=gd(new Date(k.o+1900,0,1),k.la);var q=new Date(k.getFullYear()+1,0,4),w=l(new Date(k.getFullYear(),0,4));q=l(q);return 0>=h(w,k)?0>=h(q,k)?k.getFullYear()+1:k.getFullYear():k.getFullYear()-1}var m=E[d+40>>2];d={bb:E[d>>2],ab:E[d+4>>2],ja:E[d+8>>2],Z:E[d+12>>2],S:E[d+16>>2],o:E[d+20>>2],ka:E[d+24>>2],la:E[d+28>>2],rb:E[d+32>>2],$a:E[d+36>>
2],cb:m?m?C(D,m,void 0):"":""};c=c?C(D,c,void 0):"";m={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var r in m)c=c.replace(new RegExp(r,"g"),m[r]);var x="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
t="January February March April May June July August September October November December".split(" ");m={"%a":function(k){return x[k.ka].substring(0,3)},"%A":function(k){return x[k.ka]},"%b":function(k){return t[k.S].substring(0,3)},"%B":function(k){return t[k.S]},"%C":function(k){return g((k.o+1900)/100|0,2)},"%d":function(k){return g(k.Z,2)},"%e":function(k){return e(k.Z,2," ")},"%g":function(k){return n(k).toString().substring(2)},"%G":function(k){return n(k)},"%H":function(k){return g(k.ja,2)},
"%I":function(k){k=k.ja;0==k?k=12:12<k&&(k-=12);return g(k,2)},"%j":function(k){return g(k.Z+dd(cd(k.o+1900)?ed:fd,k.S-1),3)},"%m":function(k){return g(k.S+1,2)},"%M":function(k){return g(k.ab,2)},"%n":function(){return"\n"},"%p":function(k){return 0<=k.ja&&12>k.ja?"AM":"PM"},"%S":function(k){return g(k.bb,2)},"%t":function(){return"\t"},"%u":function(k){return k.ka||7},"%U":function(k){var q=new Date(k.o+1900,0,1),w=0===q.getDay()?q:gd(q,7-q.getDay());k=new Date(k.o+1900,k.S,k.Z);return 0>h(w,k)?
g(Math.ceil((31-w.getDate()+(dd(cd(k.getFullYear())?ed:fd,k.getMonth()-1)-31)+k.getDate())/7),2):0===h(w,q)?"01":"00"},"%V":function(k){var q=new Date(k.o+1901,0,4),w=l(new Date(k.o+1900,0,4));q=l(q);var u=gd(new Date(k.o+1900,0,1),k.la);return 0>h(u,w)?"53":0>=h(q,u)?"01":g(Math.ceil((w.getFullYear()<k.o+1900?k.la+32-w.getDate():k.la+1-w.getDate())/7),2)},"%w":function(k){return k.ka},"%W":function(k){var q=new Date(k.o,0,1),w=1===q.getDay()?q:gd(q,0===q.getDay()?1:7-q.getDay()+1);k=new Date(k.o+
1900,k.S,k.Z);return 0>h(w,k)?g(Math.ceil((31-w.getDate()+(dd(cd(k.getFullYear())?ed:fd,k.getMonth()-1)-31)+k.getDate())/7),2):0===h(w,q)?"01":"00"},"%y":function(k){return(k.o+1900).toString().substring(2)},"%Y":function(k){return k.o+1900},"%z":function(k){k=k.$a;var q=0<=k;k=Math.abs(k)/60;return(q?"+":"-")+String("0000"+(k/60*100+k%60)).slice(-4)},"%Z":function(k){return k.cb},"%%":function(){return"%"}};for(r in m)0<=c.indexOf(r)&&(c=c.replace(new RegExp(r,"g"),m[r](d)));r=mb(c,!1);if(r.length>
b)return 0;I.set(r,a);return r.length-1}function Gb(a,b,c,d){a||(a=this);this.parent=a;this.G=a.G;this.fa=null;this.id=xb++;this.name=b;this.mode=c;this.g={};this.f={};this.ha=d}Object.defineProperties(Gb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});Ub();yb=Array(4096);Nb(P,"/");Q("/tmp");Q("/home");Q("/home/web_user");
(function(){Q("/dev");kb(259,{read:function(){return 0},write:function(c,d,e,g){return g}});Pb("/dev/null",259);jb(1280,nb);jb(1536,ob);Pb("/dev/tty",1280);Pb("/dev/tty1",1536);if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}b||(b=function(){A("random_device")});Xb("random",b);Xb("urandom",b);Q("/dev/shm");Q("/dev/shm/tmp")})();Q("/proc");Q("/proc/self");Q("/proc/self/fd");
Nb({G:function(){var a=qb("/proc/self","fd",16895,73);a.g={V:function(b,c){var d=wb[+c];if(!d)throw new O(8);b={parent:null,G:{Ba:"fake"},g:{X:function(){return d.path}}};return b.parent=b}};return a}},"/proc/self/fd");for(var id=Array(256),jd=0;256>jd;++jd)id[jd]=String.fromCharCode(jd);cc=id;jc=f.BindingError=ic("BindingError");kc=f.InternalError=ic("InternalError");
U.prototype.isAliasOf=function(a){if(!(this instanceof U&&a instanceof U))return!1;var b=this.b.l.i,c=this.b.h,d=a.b.l.i;for(a=a.b.h;b.A;)c=b.$(c),b=b.A;for(;d.A;)a=d.$(a),d=d.A;return b===d&&c===a};U.prototype.clone=function(){this.b.h||oc(this);if(this.b.W)return this.b.count.value+=1,this;var a=sc(Object.create(Object.getPrototypeOf(this),{b:{value:nc(this.b)}}));a.b.count.value+=1;a.b.N=!1;return a};
U.prototype["delete"]=function(){this.b.h||oc(this);this.b.N&&!this.b.W&&S("Object already scheduled for deletion");qc(this);rc(this.b);this.b.W||(this.b.s=void 0,this.b.h=void 0)};U.prototype.isDeleted=function(){return!this.b.h};U.prototype.deleteLater=function(){this.b.h||oc(this);this.b.N&&!this.b.W&&S("Object already scheduled for deletion");uc.push(this);1===uc.length&&tc&&tc(vc);this.b.N=!0;return this};V.prototype.Ma=function(a){this.Ca&&(a=this.Ca(a));return a};
V.prototype.U=function(a){this.L&&this.L(a)};V.prototype.argPackAdvance=8;V.prototype.readValueFromPointer=Ic;V.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
V.prototype.fromWireType=function(a){function b(){return this.ca?Mc(this.i.P,{l:this.Sa,h:c,v:this,s:a}):Mc(this.i.P,{l:this,h:a})}var c=this.Ma(a);if(!c)return this.U(a),null;var d=Lc(this.i,c);if(void 0!==d){if(0===d.b.count.value)return d.b.h=c,d.b.s=a,d.clone();d=d.clone();this.U(a);return d}d=this.i.La(c);d=wc[d];if(!d)return b.call(this);d=this.ba?d.Ia:d.pointerType;var e=Jc(c,this.i,d.i);return null===e?b.call(this):this.ca?Mc(d.i.P,{l:d,h:e,v:this,s:a}):Mc(d.i.P,{l:d,h:e})};
f.getInheritedInstanceCount=function(){return Object.keys(Kc).length};f.getLiveInheritedInstances=function(){var a=[],b;for(b in Kc)Kc.hasOwnProperty(b)&&a.push(Kc[b]);return a};f.flushPendingDeletes=vc;f.setDelayFunction=function(a){tc=a;uc.length&&tc&&tc(vc)};Pc=f.UnboundTypeError=ic("UnboundTypeError");f.count_emval_handles=function(){for(var a=0,b=5;b<W.length;++b)void 0!==W[b]&&++a;return a};f.get_first_emval=function(){for(var a=5;a<W.length;++a)if(void 0!==W[a])return W[a];return null};
function mb(a,b){var c=Array(oa(a)+1);a=na(a,c,0,c.length);b&&(c.length=a);return c}
var Xd={__cxa_allocate_exception:function(a){return tb(a)},__cxa_atexit:function(){},__cxa_begin_catch:function(a){var b=L[a];b&&!b.ua&&(b.ua=!0,kd.sa--);b&&(b.Y=!1);Ya.push(a);(b=Za(a))&&L[b].M++;return a},__cxa_current_primary_exception:function(){var a=Ya[Ya.length-1]||0;if(a){var b=Za(a);b&&L[b].M++}return a},__cxa_decrement_exception_refcount:function(a){$a(Za(a))},__cxa_end_catch:function(){X(0);var a=Ya.pop();a&&($a(Za(a)),N=0)},__cxa_find_matching_catch_2:function(){var a=N;if(!a)return z=
0;var b=L[a],c=b.type;if(!c)return z=0,a|0;var d=Array.prototype.slice.call(arguments);ld(c);E[27452]=a;a=109808;for(var e=0;e<d.length;e++)if(d[e]&&md(d[e],c,a))return a=E[a>>2],b.T.push(a),z=d[e],a|0;a=E[a>>2];z=c;return a|0},__cxa_find_matching_catch_3:function(){var a=N;if(!a)return z=0;var b=L[a],c=b.type;if(!c)return z=0,a|0;var d=Array.prototype.slice.call(arguments);ld(c);E[27452]=a;a=109808;for(var e=0;e<d.length;e++)if(d[e]&&md(d[e],c,a))return a=E[a>>2],b.T.push(a),z=d[e],a|0;a=E[a>>2];
z=c;return a|0},__cxa_find_matching_catch_4:function(){var a=N;if(!a)return z=0;var b=L[a],c=b.type;if(!c)return z=0,a|0;var d=Array.prototype.slice.call(arguments);ld(c);E[27452]=a;a=109808;for(var e=0;e<d.length;e++)if(d[e]&&md(d[e],c,a))return a=E[a>>2],b.T.push(a),z=d[e],a|0;a=E[a>>2];z=c;return a|0},__cxa_find_matching_catch_6:function(){var a=N;if(!a)return z=0;var b=L[a],c=b.type;if(!c)return z=0,a|0;var d=Array.prototype.slice.call(arguments);ld(c);E[27452]=a;a=109808;for(var e=0;e<d.length;e++)if(d[e]&&
md(d[e],c,a))return a=E[a>>2],b.T.push(a),z=d[e],a|0;a=E[a>>2];z=c;return a|0},__cxa_free_exception:function(a){return M(a)},__cxa_increment_exception_refcount:function(a){(a=Za(a))&&L[a].M++},__cxa_rethrow:ab,__cxa_rethrow_primary_exception:function(a){a&&(a=Za(a),Ya.push(a),L[a].Y=!0,ab())},__cxa_throw:function(a,b,c){L[a]={h:a,T:[a],type:b,U:c,M:0,ua:!1,Y:!1};N=a;"uncaught_exception"in kd?kd.sa++:kd.sa=1;throw a;},__cxa_uncaught_exceptions:function(){return kd.sa},__map_file:function(){bb(63);
return-1},__resumeException:function(a){N||(N=a);throw a;},__sys_mmap2:function(a,b,c,d,e,g){try{a:{g<<=12;var h=!1;if(0!==(d&16)&&0!==a%16384)var l=-28;else{if(0!==(d&32)){var n=nd(16384,b);if(!n){l=-48;break a}od(n,0,b);h=!0}else{var m=wb[e];if(!m){l=-8;break a}var r=g;if(0!==(c&2)&&0===(d&2)&&2!==(m.flags&2097155))throw new O(2);if(1===(m.flags&2097155))throw new O(2);if(!m.f.ea)throw new O(43);var x=m.f.ea(m,a,b,r,c,d);n=x.h;h=x.ma}$b[n]={Pa:n,Oa:b,ma:h,H:e,Ta:c,flags:d,offset:g};l=n}}return l}catch(t){return"undefined"!==
typeof Zb&&t instanceof O||A(t),-t.O}},__sys_munmap:function(a,b){try{if(-1===(a|0)||0===b)var c=-28;else{var d=$b[a];if(d&&b===d.Oa){var e=wb[d.H];d.Ta&2&&e&&e.f.ga&&e.f.ga(e,D.slice(a,a+b),d.offset,b,d.flags);$b[a]=null;d.ma&&M(d.Pa)}c=0}return c}catch(g){return"undefined"!==typeof Zb&&g instanceof O||A(g),-g.O}},_embind_register_bool:function(a,b,c,d,e){var g=bc(c);b=R(b);T(a,{name:b,fromWireType:function(h){return!!h},toWireType:function(h,l){return l?d:e},argPackAdvance:8,readValueFromPointer:function(h){if(1===
c)var l=I;else if(2===c)l=ua;else if(4===c)l=E;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(l[h>>g])},F:null})},_embind_register_class:function(a,b,c,d,e,g,h,l,n,m,r,x,t){r=R(r);g=Oc(e,g);l&&(l=Oc(h,l));m&&(m=Oc(n,m));t=Oc(x,t);var k=gc(r);yc(k,function(){Sc("Cannot construct "+r+" due to unbound types",[d])});mc([a,b,c],d?[d]:[],function(q){q=q[0];if(d){var w=q.i;var u=w.P}else u=U.prototype;q=hc(k,function(){if(Object.getPrototypeOf(this)!==F)throw new jc("Use 'new' to construct "+
r);if(void 0===H.J)throw new jc(r+" has no accessible constructor");var ea=H.J[arguments.length];if(void 0===ea)throw new jc("Tried to invoke ctor of "+r+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(H.J).toString()+") parameters instead!");return ea.apply(this,arguments)});var F=Object.create(u,{constructor:{value:q}});q.prototype=F;var H=new zc(r,q,F,t,w,g,l,m);w=new V(r,H,!0,!1);u=new V(r+"*",H,!1,!1);var ra=new V(r+" const*",H,!1,!0);wc[a]={pointerType:u,
Ia:ra};Nc(k,q);return[w,u,ra]})},_embind_register_class_constructor:function(a,b,c,d,e,g){la(0<b);var h=Tc(b,c);e=Oc(d,e);var l=[g],n=[];mc([],[a],function(m){m=m[0];var r="constructor "+m.name;void 0===m.i.J&&(m.i.J=[]);if(void 0!==m.i.J[b-1])throw new jc("Cannot register multiple constructors with identical number of parameters ("+(b-1)+") for class '"+m.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");m.i.J[b-1]=function(){Sc("Cannot construct "+
m.name+" due to unbound types",h)};mc([],h,function(x){m.i.J[b-1]=function(){arguments.length!==b-1&&S(r+" called with "+arguments.length+" arguments, expected "+(b-1));n.length=0;l.length=b;for(var t=1;t<b;++t)l[t]=x[t].toWireType(n,arguments[t-1]);t=e.apply(null,l);Uc(n);return x[0].fromWireType(t)};return[]});return[]})},_embind_register_class_function:function(a,b,c,d,e,g,h,l){var n=Tc(c,d);b=R(b);g=Oc(e,g);mc([],[a],function(m){function r(){Sc("Cannot call "+x+" due to unbound types",n)}m=m[0];
var x=m.name+"."+b;l&&m.i.Ua.push(b);var t=m.i.P,k=t[b];void 0===k||void 0===k.C&&k.className!==m.name&&k.aa===c-2?(r.aa=c-2,r.className=m.name,t[b]=r):(xc(t,b,x),t[b].C[c-2]=r);mc([],n,function(q){var w=x,u=m,F=g,H=q.length;2>H&&S("argTypes array size mismatch! Must at least get return value and 'this' types!");var ra=null!==q[1]&&null!==u,ea=!1;for(u=1;u<q.length;++u)if(null!==q[u]&&void 0===q[u].F){ea=!0;break}var Ec="void"!==q[0].name,fa="",sa="";for(u=0;u<H-2;++u)fa+=(0!==u?", ":"")+"arg"+u,
sa+=(0!==u?", ":"")+"arg"+u+"Wired";w="return function "+gc(w)+"("+fa+") {\nif (arguments.length !== "+(H-2)+") {\nthrowBindingError('function "+w+" called with ' + arguments.length + ' arguments, expected "+(H-2)+" args!');\n}\n";ea&&(w+="var destructors = [];\n");var Fc=ea?"destructors":"null";fa="throwBindingError invoker fn runDestructors retType classParam".split(" ");F=[S,F,h,Uc,q[0],q[1]];ra&&(w+="var thisWired = classParam.toWireType("+Fc+", this);\n");for(u=0;u<H-2;++u)w+="var arg"+u+"Wired = argType"+
u+".toWireType("+Fc+", arg"+u+"); // "+q[u+2].name+"\n",fa.push("argType"+u),F.push(q[u+2]);ra&&(sa="thisWired"+(0<sa.length?", ":"")+sa);w+=(Ec?"var rv = ":"")+"invoker(fn"+(0<sa.length?", ":"")+sa+");\n";if(ea)w+="runDestructors(destructors);\n";else for(u=ra?1:2;u<q.length;++u)H=1===u?"thisWired":"arg"+(u-2)+"Wired",null!==q[u].F&&(w+=H+"_dtor("+H+"); // "+q[u].name+"\n",fa.push(H+"_dtor"),F.push(q[u].F));Ec&&(w+="var ret = retType.fromWireType(rv);\nreturn ret;\n");fa.push(w+"}\n");q=Vc(fa).apply(null,
F);void 0===t[b].C?(q.aa=c-2,t[b]=q):t[b].C[c-2]=q;return[]});return[]})},_embind_register_emval:function(a,b){b=R(b);T(a,{name:b,fromWireType:function(c){var d=W[c].value;4<c&&0===--W[c].M&&(W[c]=void 0,Wc.push(c));return d},toWireType:function(c,d){return Gc(d)},argPackAdvance:8,readValueFromPointer:Ic,F:null})},_embind_register_float:function(a,b,c){c=bc(c);b=R(b);T(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,e){if("number"!==typeof e&&"boolean"!==typeof e)throw new TypeError('Cannot convert "'+
Cc(e)+'" to '+this.name);return e},argPackAdvance:8,readValueFromPointer:Xc(b,c),F:null})},_embind_register_integer:function(a,b,c,d,e){function g(m){return m}b=R(b);-1===e&&(e=4294967295);var h=bc(c);if(0===d){var l=32-8*c;g=function(m){return m<<l>>>l}}var n=-1!=b.indexOf("unsigned");T(a,{name:b,fromWireType:g,toWireType:function(m,r){if("number"!==typeof r&&"boolean"!==typeof r)throw new TypeError('Cannot convert "'+Cc(r)+'" to '+this.name);if(r<d||r>e)throw new TypeError('Passing a number "'+
Cc(r)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+e+"]!");return n?r>>>0:r|0},argPackAdvance:8,readValueFromPointer:Yc(b,h,0!==d),F:null})},_embind_register_memory_view:function(a,b,c){function d(g){g>>=2;var h=J;return new e(G,h[g+1],h[g])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=R(c);T(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{Na:!0})},_embind_register_std_string:function(a,
b){b=R(b);var c="std::string"===b;T(a,{name:b,fromWireType:function(d){var e=J[d>>2];if(c)for(var g=d+4,h=0;h<=e;++h){var l=d+4+h;if(h==e||0==D[l]){g=g?C(D,g,l-g):"";if(void 0===n)var n=g;else n+=String.fromCharCode(0),n+=g;g=l+1}}else{n=Array(e);for(h=0;h<e;++h)n[h]=String.fromCharCode(D[d+4+h]);n=n.join("")}M(d);return n},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var g="string"===typeof e;g||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array||
S("Cannot pass non-string to std::string");var h=(c&&g?function(){return oa(e)}:function(){return e.length})(),l=tb(4+h+1);J[l>>2]=h;if(c&&g)na(e,D,l+4,h+1);else if(g)for(g=0;g<h;++g){var n=e.charCodeAt(g);255<n&&(M(l),S("String has UTF-16 code units that do not fit in 8 bits"));D[l+4+g]=n}else for(g=0;g<h;++g)D[l+4+g]=e[g];null!==d&&d.push(M,l);return l},argPackAdvance:8,readValueFromPointer:Ic,F:function(d){M(d)}})},_embind_register_std_wstring:function(a,b,c){c=R(c);if(2===b){var d=qa;var e=va;
var g=wa;var h=function(){return ta};var l=1}else 4===b&&(d=xa,e=ya,g=za,h=function(){return J},l=2);T(a,{name:c,fromWireType:function(n){for(var m=J[n>>2],r=h(),x,t=n+4,k=0;k<=m;++k){var q=n+4+k*b;if(k==m||0==r[q>>l])t=d(t,q-t),void 0===x?x=t:(x+=String.fromCharCode(0),x+=t),t=q+b}M(n);return x},toWireType:function(n,m){"string"!==typeof m&&S("Cannot pass non-string to C++ string type "+c);var r=g(m),x=tb(4+r+b);J[x>>2]=r>>l;e(m,x+4,r+b);null!==n&&n.push(M,x);return x},argPackAdvance:8,readValueFromPointer:Ic,
F:function(n){M(n)}})},_embind_register_void:function(a,b){b=R(b);T(a,{nb:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},abort:function(){A()},clock_gettime:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=Zc();else return bb(28),-1;E[b>>2]=a/1E3|0;E[b+4>>2]=a%1E3*1E6|0;return 0},emscripten_get_sbrk_ptr:function(){return 109648},emscripten_memcpy_big:function(a,b,c){D.copyWithin(a,b,b+c)},emscripten_resize_heap:function(a){a>>>=0;var b=D.length;if(2147483648<
a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(16777216,a,d);0<d%65536&&(d+=65536-d%65536);a:{try{B.grow(Math.min(2147483648,d)-G.byteLength+65535>>>16);Ca(B.buffer);var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1},environ_get:function(a,b){var c=0;ad().forEach(function(d,e){var g=b+c;e=E[a+4*e>>2]=g;for(g=0;g<d.length;++g)I[e++>>0]=d.charCodeAt(g);I[e>>0]=0;c+=d.length+1});return 0},environ_sizes_get:function(a,b){var c=ad();E[a>>2]=c.length;var d=
0;c.forEach(function(e){d+=e.length+1});E[b>>2]=d;return 0},fd_close:function(a){try{var b=ac(a);if(null===b.H)throw new O(8);b.oa&&(b.oa=null);try{b.f.close&&b.f.close(b)}catch(c){throw c;}finally{wb[b.H]=null}b.H=null;return 0}catch(c){return"undefined"!==typeof Zb&&c instanceof O||A(c),c.O}},fd_read:function(a,b,c,d){try{a:{for(var e=ac(a),g=a=0;g<c;g++){var h=E[b+(8*g+4)>>2],l=e,n=E[b+8*g>>2],m=h,r=void 0,x=I;if(0>m||0>r)throw new O(28);if(null===l.H)throw new O(8);if(1===(l.flags&2097155))throw new O(8);
if(16384===(l.node.mode&61440))throw new O(31);if(!l.f.read)throw new O(28);var t="undefined"!==typeof r;if(!t)r=l.position;else if(!l.seekable)throw new O(70);var k=l.f.read(l,x,n,m,r);t||(l.position+=k);var q=k;if(0>q){var w=-1;break a}a+=q;if(q<h)break}w=a}E[d>>2]=w;return 0}catch(u){return"undefined"!==typeof Zb&&u instanceof O||A(u),u.O}},fd_seek:function(a,b,c,d,e){try{var g=ac(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Tb(g,a,d);Wa=[g.position>>>0,(Va=
g.position,1<=+Ka(Va)?0<Va?(Na(+Ma(Va/4294967296),4294967295)|0)>>>0:~~+La((Va-+(~~Va>>>0))/4294967296)>>>0:0)];E[e>>2]=Wa[0];E[e+4>>2]=Wa[1];g.oa&&0===a&&0===d&&(g.oa=null);return 0}catch(h){return"undefined"!==typeof Zb&&h instanceof O||A(h),h.O}},fd_write:function(a,b,c,d){try{a:{for(var e=ac(a),g=a=0;g<c;g++){var h=e,l=E[b+8*g>>2],n=E[b+(8*g+4)>>2],m=void 0,r=I;if(0>n||0>m)throw new O(28);if(null===h.H)throw new O(8);if(0===(h.flags&2097155))throw new O(8);if(16384===(h.node.mode&61440))throw new O(31);
if(!h.f.write)throw new O(28);h.seekable&&h.flags&1024&&Tb(h,0,2);var x="undefined"!==typeof m;if(!x)m=h.position;else if(!h.seekable)throw new O(70);var t=h.f.write(h,r,l,n,m,void 0);x||(h.position+=t);try{if(h.path&&Ab.onWriteToFile)Ab.onWriteToFile(h.path)}catch(w){y("FS.trackingDelegate['onWriteToFile']('"+h.path+"') threw an exception: "+w.message)}var k=t;if(0>k){var q=-1;break a}a+=k}q=a}E[d>>2]=q;return 0}catch(w){return"undefined"!==typeof Zb&&w instanceof O||A(w),w.O}},getTempRet0:function(){return z|
0},invoke_diii:pd,invoke_fiii:qd,invoke_i:rd,invoke_idiii:sd,invoke_ii:td,invoke_iid:ud,invoke_iif:vd,invoke_iii:wd,invoke_iiii:xd,invoke_iiiii:yd,invoke_iiiiii:zd,invoke_iiiiiii:Ad,invoke_iiiiiiii:Bd,invoke_iiiiiiiiiii:Cd,invoke_iiiiiiiiiiii:Dd,invoke_iiiiiiiiiiiii:Ed,invoke_iiiiiij:Fd,invoke_iij:Gd,invoke_iijj:Hd,invoke_ijj:Id,invoke_ijjiii:Jd,invoke_ji:Kd,invoke_jii:Ld,invoke_jiiii:Md,invoke_v:Nd,invoke_vi:Od,invoke_vii:Pd,invoke_viii:Qd,invoke_viiii:Rd,invoke_viiiii:Sd,invoke_viiiiii:Td,invoke_viiiiiii:Ud,
invoke_viiiiiiiiii:Vd,invoke_viiiiiiiiiiiiiii:Wd,llvm_eh_typeid_for:function(a){return a},memory:B,nanosleep:function(a,b){if(0===a)return bb(28),-1;var c=E[a>>2];a=E[a+4>>2];if(0>a||999999999<a||0>c)return bb(28),-1;0!==b&&(E[b>>2]=0,E[b+4>>2]=0);b=1E6*c+a/1E3;for(c=Zc();Zc()-c<b/1E3;);},setTempRet0:function(a){z=a|0},strftime_l:function(a,b,c,d){return hd(a,b,c,d)},sysconf:function(a){switch(a){case 30:return 16384;case 85:return 131072;case 132:case 133:case 12:case 137:case 138:case 15:case 235:case 16:case 17:case 18:case 19:case 20:case 149:case 13:case 10:case 236:case 153:case 9:case 21:case 22:case 159:case 154:case 14:case 77:case 78:case 139:case 80:case 81:case 82:case 68:case 67:case 164:case 11:case 29:case 47:case 48:case 95:case 52:case 51:case 46:case 79:return 200809;
case 27:case 246:case 127:case 128:case 23:case 24:case 160:case 161:case 181:case 182:case 242:case 183:case 184:case 243:case 244:case 245:case 165:case 178:case 179:case 49:case 50:case 168:case 169:case 175:case 170:case 171:case 172:case 97:case 76:case 32:case 173:case 35:return-1;case 176:case 177:case 7:case 155:case 8:case 157:case 125:case 126:case 92:case 93:case 129:case 130:case 131:case 94:case 91:return 1;case 74:case 60:case 69:case 70:case 4:return 1024;case 31:case 42:case 72:return 32;
case 87:case 26:case 33:return 2147483647;case 34:case 1:return 47839;case 38:case 36:return 99;case 43:case 37:return 2048;case 0:return 2097152;case 3:return 65536;case 28:return 32768;case 44:return 32767;case 75:return 16384;case 39:return 1E3;case 89:return 700;case 71:return 256;case 40:return 255;case 2:return 100;case 180:return 64;case 25:return 20;case 5:return 16;case 6:return 6;case 73:return 4;case 84:return"object"===typeof navigator?navigator.hardwareConcurrency||1:1}bb(28);return-1},
table:ja};
(function(){function a(e){f.asm=e.exports;K--;f.monitorRunDependencies&&f.monitorRunDependencies(K);0==K&&(null!==Oa&&(clearInterval(Oa),Oa=null),Pa&&(e=Pa,Pa=null,e()))}function b(e){a(e.instance)}function c(e){return Ua().then(function(g){return WebAssembly.instantiate(g,d)}).then(e,function(g){y("failed to asynchronously prepare wasm: "+g);A(g)})}var d={env:Xd,wasi_snapshot_preview1:Xd};K++;f.monitorRunDependencies&&f.monitorRunDependencies(K);if(f.instantiateWasm)try{return f.instantiateWasm(d,a)}catch(e){return y("Module.instantiateWasm callback failed with error: "+
e),!1}(function(){if(ia||"function"!==typeof WebAssembly.instantiateStreaming||Qa()||"function"!==typeof fetch)return c(b);fetch(Ra,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(g){y("wasm streaming compile failed: "+g);y("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();
var Xa=f.___wasm_call_ctors=function(){return(Xa=f.___wasm_call_ctors=f.asm.__wasm_call_ctors).apply(null,arguments)},od=f._memset=function(){return(od=f._memset=f.asm.memset).apply(null,arguments)},cb=f.___errno_location=function(){return(cb=f.___errno_location=f.asm.__errno_location).apply(null,arguments)},M=f._free=function(){return(M=f._free=f.asm.free).apply(null,arguments)},tb=f._malloc=function(){return(tb=f._malloc=f.asm.malloc).apply(null,arguments)},Rc=f.___getTypeName=function(){return(Rc=
f.___getTypeName=f.asm.__getTypeName).apply(null,arguments)};f.___embind_register_native_and_builtin_types=function(){return(f.___embind_register_native_and_builtin_types=f.asm.__embind_register_native_and_builtin_types).apply(null,arguments)};f.__get_tzname=function(){return(f.__get_tzname=f.asm._get_tzname).apply(null,arguments)};f.__get_daylight=function(){return(f.__get_daylight=f.asm._get_daylight).apply(null,arguments)};
f.__get_timezone=function(){return(f.__get_timezone=f.asm._get_timezone).apply(null,arguments)};var X=f._setThrew=function(){return(X=f._setThrew=f.asm.setThrew).apply(null,arguments)},Y=f.stackSave=function(){return(Y=f.stackSave=f.asm.stackSave).apply(null,arguments)},Z=f.stackRestore=function(){return(Z=f.stackRestore=f.asm.stackRestore).apply(null,arguments)};f.stackAlloc=function(){return(f.stackAlloc=f.asm.stackAlloc).apply(null,arguments)};
var kd=f.__ZSt18uncaught_exceptionv=function(){return(kd=f.__ZSt18uncaught_exceptionv=f.asm._ZSt18uncaught_exceptionv).apply(null,arguments)},md=f.___cxa_can_catch=function(){return(md=f.___cxa_can_catch=f.asm.__cxa_can_catch).apply(null,arguments)},ld=f.___cxa_is_pointer_type=function(){return(ld=f.___cxa_is_pointer_type=f.asm.__cxa_is_pointer_type).apply(null,arguments)},nd=f._memalign=function(){return(nd=f._memalign=f.asm.memalign).apply(null,arguments)},Yd=f.dynCall_v=function(){return(Yd=f.dynCall_v=
f.asm.dynCall_v).apply(null,arguments)},Zd=f.dynCall_vi=function(){return(Zd=f.dynCall_vi=f.asm.dynCall_vi).apply(null,arguments)},$d=f.dynCall_vii=function(){return($d=f.dynCall_vii=f.asm.dynCall_vii).apply(null,arguments)},ae=f.dynCall_viii=function(){return(ae=f.dynCall_viii=f.asm.dynCall_viii).apply(null,arguments)},be=f.dynCall_viiii=function(){return(be=f.dynCall_viiii=f.asm.dynCall_viiii).apply(null,arguments)},ce=f.dynCall_viiiii=function(){return(ce=f.dynCall_viiiii=f.asm.dynCall_viiiii).apply(null,
arguments)},de=f.dynCall_viiiiii=function(){return(de=f.dynCall_viiiiii=f.asm.dynCall_viiiiii).apply(null,arguments)},ee=f.dynCall_viiiiiii=function(){return(ee=f.dynCall_viiiiiii=f.asm.dynCall_viiiiiii).apply(null,arguments)},fe=f.dynCall_viiiiiiiiii=function(){return(fe=f.dynCall_viiiiiiiiii=f.asm.dynCall_viiiiiiiiii).apply(null,arguments)},ge=f.dynCall_viiiiiiiiiiiiiii=function(){return(ge=f.dynCall_viiiiiiiiiiiiiii=f.asm.dynCall_viiiiiiiiiiiiiii).apply(null,arguments)},he=f.dynCall_i=function(){return(he=
f.dynCall_i=f.asm.dynCall_i).apply(null,arguments)},ie=f.dynCall_ii=function(){return(ie=f.dynCall_ii=f.asm.dynCall_ii).apply(null,arguments)},je=f.dynCall_iii=function(){return(je=f.dynCall_iii=f.asm.dynCall_iii).apply(null,arguments)},ke=f.dynCall_iiii=function(){return(ke=f.dynCall_iiii=f.asm.dynCall_iiii).apply(null,arguments)},le=f.dynCall_iiiii=function(){return(le=f.dynCall_iiiii=f.asm.dynCall_iiiii).apply(null,arguments)},me=f.dynCall_iiiiii=function(){return(me=f.dynCall_iiiiii=f.asm.dynCall_iiiiii).apply(null,
arguments)},ne=f.dynCall_iiiiiii=function(){return(ne=f.dynCall_iiiiiii=f.asm.dynCall_iiiiiii).apply(null,arguments)},oe=f.dynCall_iiiiiiii=function(){return(oe=f.dynCall_iiiiiiii=f.asm.dynCall_iiiiiiii).apply(null,arguments)},pe=f.dynCall_iiiiiiiiiii=function(){return(pe=f.dynCall_iiiiiiiiiii=f.asm.dynCall_iiiiiiiiiii).apply(null,arguments)},qe=f.dynCall_iiiiiiiiiiii=function(){return(qe=f.dynCall_iiiiiiiiiiii=f.asm.dynCall_iiiiiiiiiiii).apply(null,arguments)},re=f.dynCall_iiiiiiiiiiiii=function(){return(re=
f.dynCall_iiiiiiiiiiiii=f.asm.dynCall_iiiiiiiiiiiii).apply(null,arguments)},se=f.dynCall_iiiiiij=function(){return(se=f.dynCall_iiiiiij=f.asm.dynCall_iiiiiij).apply(null,arguments)},te=f.dynCall_iij=function(){return(te=f.dynCall_iij=f.asm.dynCall_iij).apply(null,arguments)},ue=f.dynCall_iijj=function(){return(ue=f.dynCall_iijj=f.asm.dynCall_iijj).apply(null,arguments)},ve=f.dynCall_iif=function(){return(ve=f.dynCall_iif=f.asm.dynCall_iif).apply(null,arguments)},we=f.dynCall_iid=function(){return(we=
f.dynCall_iid=f.asm.dynCall_iid).apply(null,arguments)},xe=f.dynCall_ijj=function(){return(xe=f.dynCall_ijj=f.asm.dynCall_ijj).apply(null,arguments)},ye=f.dynCall_ijjiii=function(){return(ye=f.dynCall_ijjiii=f.asm.dynCall_ijjiii).apply(null,arguments)},ze=f.dynCall_idiii=function(){return(ze=f.dynCall_idiii=f.asm.dynCall_idiii).apply(null,arguments)},Ae=f.dynCall_ji=function(){return(Ae=f.dynCall_ji=f.asm.dynCall_ji).apply(null,arguments)},Be=f.dynCall_jii=function(){return(Be=f.dynCall_jii=f.asm.dynCall_jii).apply(null,
arguments)},Ce=f.dynCall_jiiii=function(){return(Ce=f.dynCall_jiiii=f.asm.dynCall_jiiii).apply(null,arguments)},De=f.dynCall_fiii=function(){return(De=f.dynCall_fiii=f.asm.dynCall_fiii).apply(null,arguments)},Ee=f.dynCall_diii=function(){return(Ee=f.dynCall_diii=f.asm.dynCall_diii).apply(null,arguments)};f.__growWasmMemory=function(){return(f.__growWasmMemory=f.asm.__growWasmMemory).apply(null,arguments)};f.dynCall_viijii=function(){return(f.dynCall_viijii=f.asm.dynCall_viijii).apply(null,arguments)};
f.dynCall_vj=function(){return(f.dynCall_vj=f.asm.dynCall_vj).apply(null,arguments)};f.dynCall_viij=function(){return(f.dynCall_viij=f.asm.dynCall_viij).apply(null,arguments)};f.dynCall_vij=function(){return(f.dynCall_vij=f.asm.dynCall_vij).apply(null,arguments)};f.dynCall_iidiiii=function(){return(f.dynCall_iidiiii=f.asm.dynCall_iidiiii).apply(null,arguments)};f.dynCall_jiji=function(){return(f.dynCall_jiji=f.asm.dynCall_jiji).apply(null,arguments)};
f.dynCall_iiiiiiiii=function(){return(f.dynCall_iiiiiiiii=f.asm.dynCall_iiiiiiiii).apply(null,arguments)};f.dynCall_iiiiij=function(){return(f.dynCall_iiiiij=f.asm.dynCall_iiiiij).apply(null,arguments)};f.dynCall_iiiiid=function(){return(f.dynCall_iiiiid=f.asm.dynCall_iiiiid).apply(null,arguments)};f.dynCall_iiiiijj=function(){return(f.dynCall_iiiiijj=f.asm.dynCall_iiiiijj).apply(null,arguments)};f.dynCall_iiiiiijj=function(){return(f.dynCall_iiiiiijj=f.asm.dynCall_iiiiiijj).apply(null,arguments)};
function td(a,b){var c=Y();try{return ie(a,b)}catch(d){Z(c);if(d!==d+0&&"longjmp"!==d)throw d;X(1,0)}}function Rd(a,b,c,d,e){var g=Y();try{be(a,b,c,d,e)}catch(h){Z(g);if(h!==h+0&&"longjmp"!==h)throw h;X(1,0)}}function wd(a,b,c){var d=Y();try{return je(a,b,c)}catch(e){Z(d);if(e!==e+0&&"longjmp"!==e)throw e;X(1,0)}}function Pd(a,b,c){var d=Y();try{$d(a,b,c)}catch(e){Z(d);if(e!==e+0&&"longjmp"!==e)throw e;X(1,0)}}
function Od(a,b){var c=Y();try{Zd(a,b)}catch(d){Z(c);if(d!==d+0&&"longjmp"!==d)throw d;X(1,0)}}function Qd(a,b,c,d){var e=Y();try{ae(a,b,c,d)}catch(g){Z(e);if(g!==g+0&&"longjmp"!==g)throw g;X(1,0)}}function Nd(a){var b=Y();try{Yd(a)}catch(c){Z(b);if(c!==c+0&&"longjmp"!==c)throw c;X(1,0)}}function xd(a,b,c,d){var e=Y();try{return ke(a,b,c,d)}catch(g){Z(e);if(g!==g+0&&"longjmp"!==g)throw g;X(1,0)}}
function Td(a,b,c,d,e,g,h){var l=Y();try{de(a,b,c,d,e,g,h)}catch(n){Z(l);if(n!==n+0&&"longjmp"!==n)throw n;X(1,0)}}function zd(a,b,c,d,e,g){var h=Y();try{return me(a,b,c,d,e,g)}catch(l){Z(h);if(l!==l+0&&"longjmp"!==l)throw l;X(1,0)}}function yd(a,b,c,d,e){var g=Y();try{return le(a,b,c,d,e)}catch(h){Z(g);if(h!==h+0&&"longjmp"!==h)throw h;X(1,0)}}function rd(a){var b=Y();try{return he(a)}catch(c){Z(b);if(c!==c+0&&"longjmp"!==c)throw c;X(1,0)}}
function Ad(a,b,c,d,e,g,h){var l=Y();try{return ne(a,b,c,d,e,g,h)}catch(n){Z(l);if(n!==n+0&&"longjmp"!==n)throw n;X(1,0)}}function Sd(a,b,c,d,e,g){var h=Y();try{ce(a,b,c,d,e,g)}catch(l){Z(h);if(l!==l+0&&"longjmp"!==l)throw l;X(1,0)}}function ud(a,b,c){var d=Y();try{return we(a,b,c)}catch(e){Z(d);if(e!==e+0&&"longjmp"!==e)throw e;X(1,0)}}function sd(a,b,c,d,e){var g=Y();try{return ze(a,b,c,d,e)}catch(h){Z(g);if(h!==h+0&&"longjmp"!==h)throw h;X(1,0)}}
function vd(a,b,c){var d=Y();try{return ve(a,b,c)}catch(e){Z(d);if(e!==e+0&&"longjmp"!==e)throw e;X(1,0)}}function Bd(a,b,c,d,e,g,h,l){var n=Y();try{return oe(a,b,c,d,e,g,h,l)}catch(m){Z(n);if(m!==m+0&&"longjmp"!==m)throw m;X(1,0)}}function Cd(a,b,c,d,e,g,h,l,n,m,r){var x=Y();try{return pe(a,b,c,d,e,g,h,l,n,m,r)}catch(t){Z(x);if(t!==t+0&&"longjmp"!==t)throw t;X(1,0)}}
function Ed(a,b,c,d,e,g,h,l,n,m,r,x,t){var k=Y();try{return re(a,b,c,d,e,g,h,l,n,m,r,x,t)}catch(q){Z(k);if(q!==q+0&&"longjmp"!==q)throw q;X(1,0)}}function qd(a,b,c,d){var e=Y();try{return De(a,b,c,d)}catch(g){Z(e);if(g!==g+0&&"longjmp"!==g)throw g;X(1,0)}}function pd(a,b,c,d){var e=Y();try{return Ee(a,b,c,d)}catch(g){Z(e);if(g!==g+0&&"longjmp"!==g)throw g;X(1,0)}}function Ud(a,b,c,d,e,g,h,l){var n=Y();try{ee(a,b,c,d,e,g,h,l)}catch(m){Z(n);if(m!==m+0&&"longjmp"!==m)throw m;X(1,0)}}
function Dd(a,b,c,d,e,g,h,l,n,m,r,x){var t=Y();try{return qe(a,b,c,d,e,g,h,l,n,m,r,x)}catch(k){Z(t);if(k!==k+0&&"longjmp"!==k)throw k;X(1,0)}}function Vd(a,b,c,d,e,g,h,l,n,m,r){var x=Y();try{fe(a,b,c,d,e,g,h,l,n,m,r)}catch(t){Z(x);if(t!==t+0&&"longjmp"!==t)throw t;X(1,0)}}function Wd(a,b,c,d,e,g,h,l,n,m,r,x,t,k,q,w){var u=Y();try{ge(a,b,c,d,e,g,h,l,n,m,r,x,t,k,q,w)}catch(F){Z(u);if(F!==F+0&&"longjmp"!==F)throw F;X(1,0)}}
function Gd(a,b,c,d){var e=Y();try{return te(a,b,c,d)}catch(g){Z(e);if(g!==g+0&&"longjmp"!==g)throw g;X(1,0)}}function Id(a,b,c,d,e){var g=Y();try{return xe(a,b,c,d,e)}catch(h){Z(g);if(h!==h+0&&"longjmp"!==h)throw h;X(1,0)}}function Jd(a,b,c,d,e,g,h,l){var n=Y();try{return ye(a,b,c,d,e,g,h,l)}catch(m){Z(n);if(m!==m+0&&"longjmp"!==m)throw m;X(1,0)}}function Kd(a,b){var c=Y();try{return Ae(a,b)}catch(d){Z(c);if(d!==d+0&&"longjmp"!==d)throw d;X(1,0)}}
function Fd(a,b,c,d,e,g,h,l){var n=Y();try{return se(a,b,c,d,e,g,h,l)}catch(m){Z(n);if(m!==m+0&&"longjmp"!==m)throw m;X(1,0)}}function Hd(a,b,c,d,e,g){var h=Y();try{return ue(a,b,c,d,e,g)}catch(l){Z(h);if(l!==l+0&&"longjmp"!==l)throw l;X(1,0)}}function Ld(a,b,c){var d=Y();try{return Be(a,b,c)}catch(e){Z(d);if(e!==e+0&&"longjmp"!==e)throw e;X(1,0)}}function Md(a,b,c,d,e){var g=Y();try{return Ce(a,b,c,d,e)}catch(h){Z(g);if(h!==h+0&&"longjmp"!==h)throw h;X(1,0)}}var Fe;
Pa=function Ge(){Fe||He();Fe||(Pa=Ge)};
function He(){function a(){if(!Fe&&(Fe=!0,f.calledRun=!0,!ka)){f.noFSInit||Vb||(Vb=!0,Ub(),f.stdin=f.stdin,f.stdout=f.stdout,f.stderr=f.stderr,f.stdin?Xb("stdin",f.stdin):Qb("/dev/tty","/dev/stdin"),f.stdout?Xb("stdout",null,f.stdout):Qb("/dev/tty","/dev/stdout"),f.stderr?Xb("stderr",null,f.stderr):Qb("/dev/tty1","/dev/stderr"),Rb("/dev/stdin","r"),Rb("/dev/stdout","w"),Rb("/dev/stderr","w"));Ea(Ga);zb=!1;Ea(Ha);aa(f);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(f.postRun)for("function"==
typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var b=f.postRun.shift();Ia.unshift(b)}Ea(Ia)}}if(!(0<K)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Ja();Ea(Fa);0<K||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);a()},1)):a())}}f.run=He;if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();noExitRuntime=!0;He();


  return Tiro.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
      module.exports = Tiro;
    else if (typeof define === 'function' && define['amd'])
      define([], function() { return Tiro; });
    else if (typeof exports === 'object')
      exports["Tiro"] = Tiro;
    